// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"context"
	"time"

	"github.com/rs/zerolog"
	"github.com/rs/zerolog/log"
	"github.com/sah4ez/ducalis-tg/internal/transport/viewer"
	"github.com/sah4ez/ducalis-tg/pkg/contract"
	"github.com/sah4ez/ducalis-tg/pkg/types"
)

type loggerAuthService struct {
	next contract.AuthService
}

func loggerMiddlewareAuthService() MiddlewareAuthService {
	return func(next contract.AuthService) contract.AuthService {
		return &loggerAuthService{next: next}
	}
}

func (m loggerAuthService) Register(ctx context.Context, req types.RegisterRequest) (user *types.User, token string, err error) {
	logger := log.Ctx(ctx).With().Str("service", "AuthService").Str("method", "register").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method":  "authService.register",
				"request": viewer.Sprintf("%+v", requestAuthServiceRegister{Req: req}),
				"response": viewer.Sprintf("%+v", responseAuthServiceRegister{
					Token: token,
					User:  user,
				}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call register")
			return
		}
		logger.Info().Func(logHandle).Msg("call register")
	}(time.Now())
	return m.next.Register(ctx, req)
}

func (m loggerAuthService) Login(ctx context.Context, email string, password string) (user *types.User, token string, err error) {
	logger := log.Ctx(ctx).With().Str("service", "AuthService").Str("method", "login").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method": "authService.login",
				"request": viewer.Sprintf("%+v", requestAuthServiceLogin{
					Email:    email,
					Password: password,
				}),
				"response": viewer.Sprintf("%+v", responseAuthServiceLogin{
					Token: token,
					User:  user,
				}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call login")
			return
		}
		logger.Info().Func(logHandle).Msg("call login")
	}(time.Now())
	return m.next.Login(ctx, email, password)
}

func (m loggerAuthService) OAuthAuthorize(ctx context.Context, provider string, redirectURL string) (authURL string, err error) {
	logger := log.Ctx(ctx).With().Str("service", "AuthService").Str("method", "oAuthAuthorize").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method": "authService.oAuthAuthorize",
				"request": viewer.Sprintf("%+v", requestAuthServiceOAuthAuthorize{
					Provider:    provider,
					RedirectURL: redirectURL,
				}),
				"response": viewer.Sprintf("%+v", responseAuthServiceOAuthAuthorize{AuthURL: authURL}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call oAuthAuthorize")
			return
		}
		logger.Info().Func(logHandle).Msg("call oAuthAuthorize")
	}(time.Now())
	return m.next.OAuthAuthorize(ctx, provider, redirectURL)
}

func (m loggerAuthService) OAuthCallback(ctx context.Context, provider string, code string, state string) (user *types.User, token string, err error) {
	logger := log.Ctx(ctx).With().Str("service", "AuthService").Str("method", "oAuthCallback").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method": "authService.oAuthCallback",
				"request": viewer.Sprintf("%+v", requestAuthServiceOAuthCallback{
					Code:     code,
					Provider: provider,
					State:    state,
				}),
				"response": viewer.Sprintf("%+v", responseAuthServiceOAuthCallback{
					Token: token,
					User:  user,
				}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call oAuthCallback")
			return
		}
		logger.Info().Func(logHandle).Msg("call oAuthCallback")
	}(time.Now())
	return m.next.OAuthCallback(ctx, provider, code, state)
}

func (m loggerAuthService) GetMe(ctx context.Context, userID string) (user *types.User, err error) {
	logger := log.Ctx(ctx).With().Str("service", "AuthService").Str("method", "getMe").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method":   "authService.getMe",
				"request":  viewer.Sprintf("%+v", requestAuthServiceGetMe{UserID: userID}),
				"response": viewer.Sprintf("%+v", responseAuthServiceGetMe{User: user}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call getMe")
			return
		}
		logger.Info().Func(logHandle).Msg("call getMe")
	}(time.Now())
	return m.next.GetMe(ctx, userID)
}

func (m loggerAuthService) RefreshToken(ctx context.Context, refreshToken string) (token string, err error) {
	logger := log.Ctx(ctx).With().Str("service", "AuthService").Str("method", "refreshToken").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method":   "authService.refreshToken",
				"request":  viewer.Sprintf("%+v", requestAuthServiceRefreshToken{RefreshToken: refreshToken}),
				"response": viewer.Sprintf("%+v", responseAuthServiceRefreshToken{Token: token}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call refreshToken")
			return
		}
		logger.Info().Func(logHandle).Msg("call refreshToken")
	}(time.Now())
	return m.next.RefreshToken(ctx, refreshToken)
}
