// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import "github.com/sah4ez/ducalis-tg/pkg/types"

type requestAuthServiceRegister struct {
	Req types.RegisterRequest `json:"req,omitempty"`
}

type responseAuthServiceRegister struct {
	User  *types.User `json:"user,omitempty"`
	Token string      `json:"token,omitempty"`
}

type requestAuthServiceLogin struct {
	Email    string `json:"email,omitempty"`
	Password string `json:"password,omitempty"`
}

type responseAuthServiceLogin struct {
	User  *types.User `json:"user,omitempty"`
	Token string      `json:"token,omitempty"`
}

type requestAuthServiceOAuthAuthorize struct {
	Provider    string `json:"provider,omitempty"`
	RedirectURL string `json:"redirectURL,omitempty"`
}

type responseAuthServiceOAuthAuthorize struct {
	AuthURL string `json:"authURL,omitempty"`
}

type requestAuthServiceOAuthCallback struct {
	Provider string `json:"provider,omitempty"`
	Code     string `json:"code,omitempty"`
	State    string `json:"state,omitempty"`
}

type responseAuthServiceOAuthCallback struct {
	User  *types.User `json:"user,omitempty"`
	Token string      `json:"token,omitempty"`
}

type requestAuthServiceGetMe struct {
	UserID string `json:"userID,omitempty"`
}

type responseAuthServiceGetMe struct {
	User *types.User `json:"user,omitempty"`
}

type requestAuthServiceRefreshToken struct {
	RefreshToken string `json:"refreshToken,omitempty"`
}

type responseAuthServiceRefreshToken struct {
	Token string `json:"token,omitempty"`
}
