// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"github.com/gofiber/fiber/v2"
	"github.com/sah4ez/ducalis-tg/pkg/contract"
)

type httpAuthService struct {
	errorHandler     ErrorHandler
	maxBatchSize     int
	maxParallelBatch int
	svc              *serverAuthService
	base             contract.AuthService
}

func NewAuthService(svcAuthService contract.AuthService) (srv *httpAuthService) {

	srv = &httpAuthService{
		base: svcAuthService,
		svc:  newServerAuthService(svcAuthService),
	}
	return
}

func (http *httpAuthService) Service() *serverAuthService {
	return http.svc
}

func (http *httpAuthService) WithLog() *httpAuthService {
	http.svc.WithLog()
	return http
}

func (http *httpAuthService) WithTrace() *httpAuthService {
	http.svc.WithTrace()
	return http
}

func (http *httpAuthService) WithMetrics() *httpAuthService {
	http.svc.WithMetrics()
	return http
}

func (http *httpAuthService) WithErrorHandler(handler ErrorHandler) *httpAuthService {
	http.errorHandler = handler
	return http
}

func (http *httpAuthService) SetRoutes(route *fiber.App) {
	route.Post("/api/v1/auth/authService", http.serveBatch)
}
