// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"github.com/gofiber/fiber/v2"
	"github.com/sah4ez/ducalis-tg/pkg/contract"
)

type httpIntegrationService struct {
	errorHandler     ErrorHandler
	maxBatchSize     int
	maxParallelBatch int
	svc              *serverIntegrationService
	base             contract.IntegrationService
}

func NewIntegrationService(svcIntegrationService contract.IntegrationService) (srv *httpIntegrationService) {

	srv = &httpIntegrationService{
		base: svcIntegrationService,
		svc:  newServerIntegrationService(svcIntegrationService),
	}
	return
}

func (http *httpIntegrationService) Service() *serverIntegrationService {
	return http.svc
}

func (http *httpIntegrationService) WithLog() *httpIntegrationService {
	http.svc.WithLog()
	return http
}

func (http *httpIntegrationService) WithTrace() *httpIntegrationService {
	http.svc.WithTrace()
	return http
}

func (http *httpIntegrationService) WithMetrics() *httpIntegrationService {
	http.svc.WithMetrics()
	return http
}

func (http *httpIntegrationService) WithErrorHandler(handler ErrorHandler) *httpIntegrationService {
	http.errorHandler = handler
	return http
}

func (http *httpIntegrationService) SetRoutes(route *fiber.App) {
	route.Post("/api/v1/integrations/integrationService", http.serveBatch)
}
