// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"context"
	"fmt"

	"github.com/sah4ez/ducalis-tg/pkg/contract"
	"github.com/sah4ez/ducalis-tg/pkg/types"
	otel "go.opentelemetry.io/otel"
	trace "go.opentelemetry.io/otel/trace"
)

type traceTaskService struct {
	next contract.TaskService
}

func traceMiddlewareTaskService(next contract.TaskService) contract.TaskService {
	return &traceTaskService{next: next}
}

func (svc traceTaskService) Create(ctx context.Context, req types.CreateTaskRequest) (task *types.Task, err error) {

	var span trace.Span
	ctx, span = otel.Tracer(fmt.Sprintf("tg:%s", VersionTg)).Start(ctx, "taskService.create")
	defer func() {
		span.RecordError(err)
		span.End()
	}()
	return svc.next.Create(ctx, req)
}

func (svc traceTaskService) Get(ctx context.Context, id string) (task *types.Task, err error) {

	var span trace.Span
	ctx, span = otel.Tracer(fmt.Sprintf("tg:%s", VersionTg)).Start(ctx, "taskService.get")
	defer func() {
		span.RecordError(err)
		span.End()
	}()
	return svc.next.Get(ctx, id)
}

func (svc traceTaskService) Update(ctx context.Context, id string, req types.UpdateTaskRequest) (task *types.Task, err error) {

	var span trace.Span
	ctx, span = otel.Tracer(fmt.Sprintf("tg:%s", VersionTg)).Start(ctx, "taskService.update")
	defer func() {
		span.RecordError(err)
		span.End()
	}()
	return svc.next.Update(ctx, id, req)
}

func (svc traceTaskService) Delete(ctx context.Context, id string) (err error) {

	var span trace.Span
	ctx, span = otel.Tracer(fmt.Sprintf("tg:%s", VersionTg)).Start(ctx, "taskService.delete")
	defer func() {
		span.RecordError(err)
		span.End()
	}()
	return svc.next.Delete(ctx, id)
}

func (svc traceTaskService) List(ctx context.Context, req types.ListTasksRequest) (tasks []types.Task, total int, err error) {

	var span trace.Span
	ctx, span = otel.Tracer(fmt.Sprintf("tg:%s", VersionTg)).Start(ctx, "taskService.list")
	defer func() {
		span.RecordError(err)
		span.End()
	}()
	return svc.next.List(ctx, req)
}

func (svc traceTaskService) SetScores(ctx context.Context, taskID string, scores map[string]float64) (task *types.Task, err error) {

	var span trace.Span
	ctx, span = otel.Tracer(fmt.Sprintf("tg:%s", VersionTg)).Start(ctx, "taskService.setScores")
	defer func() {
		span.RecordError(err)
		span.End()
	}()
	return svc.next.SetScores(ctx, taskID, scores)
}

func (svc traceTaskService) Vote(ctx context.Context, taskID string, userID string, weight float64) (task *types.Task, err error) {

	var span trace.Span
	ctx, span = otel.Tracer(fmt.Sprintf("tg:%s", VersionTg)).Start(ctx, "taskService.vote")
	defer func() {
		span.RecordError(err)
		span.End()
	}()
	return svc.next.Vote(ctx, taskID, userID, weight)
}

func (svc traceTaskService) RemoveVote(ctx context.Context, taskID string, userID string) (task *types.Task, err error) {

	var span trace.Span
	ctx, span = otel.Tracer(fmt.Sprintf("tg:%s", VersionTg)).Start(ctx, "taskService.removeVote")
	defer func() {
		span.RecordError(err)
		span.End()
	}()
	return svc.next.RemoveVote(ctx, taskID, userID)
}

func (svc traceTaskService) Estimate(ctx context.Context, taskID string, userID string, value float64) (task *types.Task, err error) {

	var span trace.Span
	ctx, span = otel.Tracer(fmt.Sprintf("tg:%s", VersionTg)).Start(ctx, "taskService.estimate")
	defer func() {
		span.RecordError(err)
		span.End()
	}()
	return svc.next.Estimate(ctx, taskID, userID, value)
}

func (svc traceTaskService) SetDependencies(ctx context.Context, taskID string, dependencyIDs []string) (task *types.Task, err error) {

	var span trace.Span
	ctx, span = otel.Tracer(fmt.Sprintf("tg:%s", VersionTg)).Start(ctx, "taskService.setDependencies")
	defer func() {
		span.RecordError(err)
		span.End()
	}()
	return svc.next.SetDependencies(ctx, taskID, dependencyIDs)
}

func (svc traceTaskService) GetRanked(ctx context.Context, workspaceID string, limit int, offset int) (tasks []types.TaskWithRank, err error) {

	var span trace.Span
	ctx, span = otel.Tracer(fmt.Sprintf("tg:%s", VersionTg)).Start(ctx, "taskService.getRanked")
	defer func() {
		span.RecordError(err)
		span.End()
	}()
	return svc.next.GetRanked(ctx, workspaceID, limit, offset)
}
