// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import "github.com/sah4ez/ducalis-tg/pkg/types"

type requestWorkspaceServiceCreate struct {
	Req types.CreateWorkspaceRequest `json:"req,omitempty"`
}

type responseWorkspaceServiceCreate struct {
	Workspace *types.Workspace `json:"workspace,omitempty"`
}

type requestWorkspaceServiceGet struct {
	Id string `json:"id,omitempty"`
}

type responseWorkspaceServiceGet struct {
	Workspace *types.Workspace `json:"workspace,omitempty"`
}

type requestWorkspaceServiceUpdate struct {
	Id  string                       `json:"id,omitempty"`
	Req types.UpdateWorkspaceRequest `json:"req,omitempty"`
}

type responseWorkspaceServiceUpdate struct {
	Workspace *types.Workspace `json:"workspace,omitempty"`
}

type requestWorkspaceServiceDelete struct {
	Id string `json:"id,omitempty"`
}

// Formal exchange type, please do not delete.
type responseWorkspaceServiceDelete struct{}

type requestWorkspaceServiceList struct {
	UserID string `json:"userID,omitempty"`
	Limit  int    `json:"limit,omitempty"`
	Offset int    `json:"offset,omitempty"`
}

type responseWorkspaceServiceList struct {
	Workspaces []types.Workspace `json:"workspaces,omitempty"`
	Total      int               `json:"total,omitempty"`
}

type requestWorkspaceServiceSetScoringConfig struct {
	WorkspaceID string              `json:"workspaceID,omitempty"`
	Config      types.ScoringConfig `json:"config,omitempty"`
}

type responseWorkspaceServiceSetScoringConfig struct {
	Workspace *types.Workspace `json:"workspace,omitempty"`
}

type requestWorkspaceServiceInviteMember struct {
	WorkspaceID string `json:"workspaceID,omitempty"`
	Email       string `json:"email,omitempty"`
	Role        string `json:"role,omitempty"`
}

type responseWorkspaceServiceInviteMember struct {
	Member *types.Member `json:"member,omitempty"`
}

type requestWorkspaceServiceListMembers struct {
	WorkspaceID string `json:"workspaceID,omitempty"`
}

type responseWorkspaceServiceListMembers struct {
	Members []types.Member `json:"members,omitempty"`
}

type requestWorkspaceServiceRemoveMember struct {
	WorkspaceID string `json:"workspaceID,omitempty"`
	MemberID    string `json:"memberID,omitempty"`
}

// Formal exchange type, please do not delete.
type responseWorkspaceServiceRemoveMember struct{}
