// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"github.com/gofiber/fiber/v2"
	"github.com/sah4ez/ducalis-tg/pkg/contract"
)

type httpWorkspaceService struct {
	errorHandler     ErrorHandler
	maxBatchSize     int
	maxParallelBatch int
	svc              *serverWorkspaceService
	base             contract.WorkspaceService
}

func NewWorkspaceService(svcWorkspaceService contract.WorkspaceService) (srv *httpWorkspaceService) {

	srv = &httpWorkspaceService{
		base: svcWorkspaceService,
		svc:  newServerWorkspaceService(svcWorkspaceService),
	}
	return
}

func (http *httpWorkspaceService) Service() *serverWorkspaceService {
	return http.svc
}

func (http *httpWorkspaceService) WithLog() *httpWorkspaceService {
	http.svc.WithLog()
	return http
}

func (http *httpWorkspaceService) WithTrace() *httpWorkspaceService {
	http.svc.WithTrace()
	return http
}

func (http *httpWorkspaceService) WithMetrics() *httpWorkspaceService {
	http.svc.WithMetrics()
	return http
}

func (http *httpWorkspaceService) WithErrorHandler(handler ErrorHandler) *httpWorkspaceService {
	http.errorHandler = handler
	return http
}

func (http *httpWorkspaceService) SetRoutes(route *fiber.App) {
	route.Post("/api/v1/workspaces/workspaceService", http.serveBatch)
}
