package main

import (
	"context"
	"fmt"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/cors"
	"github.com/rs/zerolog"

	"github.com/sah4ez/priora/internal/service"
	"github.com/sah4ez/priora/internal/storage/postgres"
	// "github.com/sah4ez/priora/internal/transport" // Generated by tg
)

// Config holds application configuration
type Config struct {
	DatabaseURL    string
	RedisURL       string
	Bind           string
	MetricsBind    string
	HealthBind     string
	JWTSecret      string
	LogLevel       string
}

func main() {
	// Load config from environment
	cfg := Config{
		DatabaseURL:    getEnv("DATABASE_URL", "postgres://priora:priora123@localhost:5432/priora?sslmode=disable"),
		RedisURL:       getEnv("REDIS_URL", "redis://localhost:6379/0"),
		Bind:           getEnv("BIND", ":8080"),
		MetricsBind:    getEnv("METRICS_BIND", ":9090"),
		HealthBind:     getEnv("HEALTH_BIND", ":9091"),
		JWTSecret:      getEnv("JWT_SECRET", "change-me-in-production"),
		LogLevel:       getEnv("LOG_LEVEL", "debug"),
	}

	// Setup logger
	logger := zerolog.New(os.Stdout).With().Timestamp().Logger()
	if cfg.LogLevel == "debug" {
		logger = logger.Level(zerolog.DebugLevel)
	} else {
		logger = logger.Level(zerolog.InfoLevel)
	}

	logger.Info().Msg("starting priora server")

	// Connect to database
	db, err := postgres.New(cfg.DatabaseURL)
	if err != nil {
		logger.Fatal().Err(err).Msg("failed to connect to database")
	}
	defer db.Close()

	logger.Info().Msg("connected to database")

	// Initialize services
	workspaceSvc := service.NewWorkspaceService(db, logger)
	taskSvc := service.NewTaskService(db, logger)
	integrationSvc := service.NewIntegrationService(db, logger)
	authSvc := service.NewAuthService(db, logger, cfg.JWTSecret)

	// Create fiber app
	app := fiber.New(fiber.Config{
		AppName:               "Priora API v1.0.0",
		ReadTimeout:           30 * time.Second,
		WriteTimeout:          30 * time.Second,
		DisableStartupMessage: false,
	})

	// Middleware
	app.Use(cors.New(cors.Config{
		AllowOrigins: "*",
		AllowMethods: "GET,POST,PUT,PATCH,DELETE,OPTIONS",
		AllowHeaders: "Origin,Content-Type,Accept,Authorization,X-Request-ID",
	}))

	// Health check endpoint (before auth middleware)
	app.Get("/health", func(c *fiber.Ctx) error {
		return c.JSON(fiber.Map{
			"status":  "ok",
			"version": "1.0.0",
		})
	})

	// API routes
	api := app.Group("/api/v1")

	// Auth routes (public)
	auth := api.Group("/auth")
	_ = auth // TODO: register auth handlers

	// Protected routes
	// TODO: Add auth middleware here

	workspaces := api.Group("/workspaces")
	_ = workspaces // TODO: register workspace handlers

	tasks := api.Group("/tasks")
	_ = tasks // TODO: register task handlers

	integrations := api.Group("/integrations")
	_ = integrations // TODO: register integration handlers

	// Placeholder routes for MVP
	api.Get("/", func(c *fiber.Ctx) error {
		return c.JSON(fiber.Map{
			"service": "priora",
			"version": "1.0.0",
			"docs":    "/api/v1/swagger",
		})
	})

	// Register tg-generated handlers
	// After running `make generate`, uncomment:
	// transport.RegisterWorkspaceService(app, workspaceSvc)
	// transport.RegisterTaskService(app, taskSvc)
	// transport.RegisterIntegrationService(app, integrationSvc)
	// transport.RegisterAuthService(app, authSvc)

	// Temporary direct handlers for MVP testing
	registerTempHandlers(api, workspaceSvc, taskSvc, authSvc)

	// Graceful shutdown
	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)

	go func() {
		<-quit
		logger.Info().Msg("shutting down server...")

		ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
		defer cancel()

		if err := app.ShutdownWithContext(ctx); err != nil {
			logger.Error().Err(err).Msg("server shutdown error")
		}
	}()

	// Start health server
	go func() {
		http.HandleFunc("/health", func(w http.ResponseWriter, r *http.Request) {
			w.WriteHeader(http.StatusOK)
			w.Write([]byte("OK"))
		})
		logger.Info().Str("bind", cfg.HealthBind).Msg("health server listening")
		http.ListenAndServe(cfg.HealthBind, nil)
	}()

	// Start main server
	logger.Info().Str("bind", cfg.Bind).Msg("server listening")
	if err := app.Listen(cfg.Bind); err != nil {
		logger.Fatal().Err(err).Msg("server error")
	}
}

func getEnv(key, fallback string) string {
	if value, exists := os.LookupEnv(key); exists {
		return value
	}
	return fallback
}

// Temporary handlers for testing before tg generation
func registerTempHandlers(api fiber.Router, workspaceSvc *service.WorkspaceService, taskSvc *service.TaskService, authSvc *service.AuthService) {
	api.Post("/workspaces", func(c *fiber.Ctx) error {
		return c.JSON(fiber.Map{"message": "use tg-generated handlers"})
	})
}
