// Code generated by 'T'ool 'G'ateway. DO NOT EDIT.
package transport

import (
	"github.com/gofiber/fiber/v2"
	"github.com/sah4ez/ducalis-tg/pkg/contract"
)

type httpAuthService struct {
	errorHandler ErrorHandler
	svc          *serverAuthService
	base         contract.AuthService
}

func newAuthService(svcAuthService contract.AuthService) (srv *httpAuthService) {

	srv = &httpAuthService{
		base: svcAuthService,
		svc:  newServerAuthService(svcAuthService),
	}
	return
}

func (http *httpAuthService) Service() *serverAuthService {
	return http.svc
}

func (http *httpAuthService) WithMetrics(metrics *Metrics) *httpAuthService {
	http.svc.WithMetrics(metrics)
	return http
}

func (http *httpAuthService) WithErrorHandler(handler ErrorHandler) *httpAuthService {
	http.errorHandler = handler
	return http
}

func (http *httpAuthService) WithRedirect() *httpAuthService {
	return http
}

func (http *httpAuthService) SetRoutes(route *fiber.App) {
	route.Post("/api/v1/auth/register", http.serveRegister)
	route.Post("/api/v1/auth/login", http.serveLogin)
	route.Get("/api/v1/auth/oauth/:provider", http.serveOAuthAuthorize)
	route.Get("/api/v1/auth/oauth/:provider/callback", http.serveOAuthCallback)
	route.Get("/api/v1/auth/me", http.serveGetMe)
	route.Post("/api/v1/auth/refresh", http.serveRefreshToken)
}
