// Code generated by 'T'ool 'G'ateway. DO NOT EDIT.
package transport

import "github.com/sah4ez/ducalis-tg/pkg/types"

type requestAuthServiceRegister struct {
	Req types.RegisterRequest `json:"req"`
}

type responseAuthServiceRegister struct {
	User  *types.User `json:"user"`
	Token string      `json:"token"`
}

type requestAuthServiceLogin struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type responseAuthServiceLogin struct {
	User  *types.User `json:"user"`
	Token string      `json:"token"`
}

type requestAuthServiceOAuthAuthorize struct {
	Provider    string `json:"-"`
	RedirectURL string `json:"redirectURL"`
}

type responseAuthServiceOAuthAuthorize struct {
	AuthURL string `json:"authURL"`
}

type requestAuthServiceOAuthCallback struct {
	Provider string `json:"-"`
	Code     string `json:"code"`
	State    string `json:"state"`
}

type responseAuthServiceOAuthCallback struct {
	User  *types.User `json:"user"`
	Token string      `json:"token"`
}

type requestAuthServiceGetMe struct {
	UserID string `json:"userID"`
}

type responseAuthServiceGetMe struct {
	User *types.User `json:"user"`
}

type requestAuthServiceRefreshToken struct {
	RefreshToken string `json:"refreshToken"`
}

type responseAuthServiceRefreshToken struct {
	Token string `json:"token"`
}
