// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"context"

	"github.com/sah4ez/ducalis-tg/pkg/contract"
	"github.com/sah4ez/ducalis-tg/pkg/types"
)

type AuthServiceRegister func(ctx context.Context, req types.RegisterRequest) (user *types.User, token string, err error)
type AuthServiceLogin func(ctx context.Context, email string, password string) (user *types.User, token string, err error)
type AuthServiceOAuthAuthorize func(ctx context.Context, provider string, redirectURL string) (authURL string, err error)
type AuthServiceOAuthCallback func(ctx context.Context, provider string, code string, state string) (user *types.User, token string, err error)
type AuthServiceGetMe func(ctx context.Context, userID string) (user *types.User, err error)
type AuthServiceRefreshToken func(ctx context.Context, refreshToken string) (token string, err error)

type MiddlewareAuthService func(next contract.AuthService) contract.AuthService

type MiddlewareAuthServiceRegister func(next AuthServiceRegister) AuthServiceRegister
type MiddlewareAuthServiceLogin func(next AuthServiceLogin) AuthServiceLogin
type MiddlewareAuthServiceOAuthAuthorize func(next AuthServiceOAuthAuthorize) AuthServiceOAuthAuthorize
type MiddlewareAuthServiceOAuthCallback func(next AuthServiceOAuthCallback) AuthServiceOAuthCallback
type MiddlewareAuthServiceGetMe func(next AuthServiceGetMe) AuthServiceGetMe
type MiddlewareAuthServiceRefreshToken func(next AuthServiceRefreshToken) AuthServiceRefreshToken
