// Code generated by 'T'ool 'G'ateway. DO NOT EDIT.
package transport

import (
	"context"
	"strconv"
	"time"

	"github.com/gofiber/fiber/v2"
	"github.com/sah4ez/ducalis-tg/internal/transport/srvctx"
	"github.com/sah4ez/ducalis-tg/pkg/contract"
	"github.com/sah4ez/ducalis-tg/pkg/types"
)

const (
	metricServiceAuthService = "authService"
)
const metricMethodAuthServiceRegister = "register"
const metricMethodAuthServiceLogin = "login"
const metricMethodAuthServiceOAuthAuthorize = "oAuthAuthorize"
const metricMethodAuthServiceOAuthCallback = "oAuthCallback"
const metricMethodAuthServiceGetMe = "getMe"
const metricMethodAuthServiceRefreshToken = "refreshToken"

type metricsAuthService struct {
	next    contract.AuthService
	metrics *Metrics
}

func metricsMiddlewareAuthService(next contract.AuthService, metrics *Metrics) contract.AuthService {
	return &metricsAuthService{
		metrics: metrics,
		next:    next,
	}
}

func (m metricsAuthService) Register(ctx context.Context, req types.RegisterRequest) (user *types.User, token string, err error) {

	defer func(_begin_ time.Time) {
		if m.metrics == nil {
			return
		}
		var (
			success = true
			errCode int
		)
		if err != nil {
			success = false
			errCode = fiber.StatusInternalServerError
			ec, ok := err.(withErrorCode)
			if ok {
				errCode = ec.Code()
			}
		}
		clientID := srvctx.GetClientID(ctx)
		if success {
			m.metrics.RequestCount.WithLabelValues(metricServiceAuthService, metricMethodAuthServiceRegister, metricSuccessTrue, metricErrCodeSuccess, clientID).Add(1)
			m.metrics.RequestLatency.WithLabelValues(metricServiceAuthService, metricMethodAuthServiceRegister, metricSuccessTrue, metricErrCodeSuccess, clientID).Observe(float64(time.Since(_begin_).Seconds()))
		} else {
			errCodeStr := strconv.Itoa(errCode)
			m.metrics.RequestCount.WithLabelValues(metricServiceAuthService, metricMethodAuthServiceRegister, metricSuccessFalse, errCodeStr, clientID).Add(1)
			m.metrics.RequestLatency.WithLabelValues(metricServiceAuthService, metricMethodAuthServiceRegister, metricSuccessFalse, errCodeStr, clientID).Observe(float64(time.Since(_begin_).Seconds()))
		}
	}(time.Now())

	return m.next.Register(ctx, req)
}

func (m metricsAuthService) Login(ctx context.Context, email string, password string) (user *types.User, token string, err error) {

	defer func(_begin_ time.Time) {
		if m.metrics == nil {
			return
		}
		var (
			success = true
			errCode int
		)
		if err != nil {
			success = false
			errCode = fiber.StatusInternalServerError
			ec, ok := err.(withErrorCode)
			if ok {
				errCode = ec.Code()
			}
		}
		clientID := srvctx.GetClientID(ctx)
		if success {
			m.metrics.RequestCount.WithLabelValues(metricServiceAuthService, metricMethodAuthServiceLogin, metricSuccessTrue, metricErrCodeSuccess, clientID).Add(1)
			m.metrics.RequestLatency.WithLabelValues(metricServiceAuthService, metricMethodAuthServiceLogin, metricSuccessTrue, metricErrCodeSuccess, clientID).Observe(float64(time.Since(_begin_).Seconds()))
		} else {
			errCodeStr := strconv.Itoa(errCode)
			m.metrics.RequestCount.WithLabelValues(metricServiceAuthService, metricMethodAuthServiceLogin, metricSuccessFalse, errCodeStr, clientID).Add(1)
			m.metrics.RequestLatency.WithLabelValues(metricServiceAuthService, metricMethodAuthServiceLogin, metricSuccessFalse, errCodeStr, clientID).Observe(float64(time.Since(_begin_).Seconds()))
		}
	}(time.Now())

	return m.next.Login(ctx, email, password)
}

func (m metricsAuthService) OAuthAuthorize(ctx context.Context, provider string, redirectURL string) (authURL string, err error) {

	defer func(_begin_ time.Time) {
		if m.metrics == nil {
			return
		}
		var (
			success = true
			errCode int
		)
		if err != nil {
			success = false
			errCode = fiber.StatusInternalServerError
			ec, ok := err.(withErrorCode)
			if ok {
				errCode = ec.Code()
			}
		}
		clientID := srvctx.GetClientID(ctx)
		if success {
			m.metrics.RequestCount.WithLabelValues(metricServiceAuthService, metricMethodAuthServiceOAuthAuthorize, metricSuccessTrue, metricErrCodeSuccess, clientID).Add(1)
			m.metrics.RequestLatency.WithLabelValues(metricServiceAuthService, metricMethodAuthServiceOAuthAuthorize, metricSuccessTrue, metricErrCodeSuccess, clientID).Observe(float64(time.Since(_begin_).Seconds()))
		} else {
			errCodeStr := strconv.Itoa(errCode)
			m.metrics.RequestCount.WithLabelValues(metricServiceAuthService, metricMethodAuthServiceOAuthAuthorize, metricSuccessFalse, errCodeStr, clientID).Add(1)
			m.metrics.RequestLatency.WithLabelValues(metricServiceAuthService, metricMethodAuthServiceOAuthAuthorize, metricSuccessFalse, errCodeStr, clientID).Observe(float64(time.Since(_begin_).Seconds()))
		}
	}(time.Now())

	return m.next.OAuthAuthorize(ctx, provider, redirectURL)
}

func (m metricsAuthService) OAuthCallback(ctx context.Context, provider string, code string, state string) (user *types.User, token string, err error) {

	defer func(_begin_ time.Time) {
		if m.metrics == nil {
			return
		}
		var (
			success = true
			errCode int
		)
		if err != nil {
			success = false
			errCode = fiber.StatusInternalServerError
			ec, ok := err.(withErrorCode)
			if ok {
				errCode = ec.Code()
			}
		}
		clientID := srvctx.GetClientID(ctx)
		if success {
			m.metrics.RequestCount.WithLabelValues(metricServiceAuthService, metricMethodAuthServiceOAuthCallback, metricSuccessTrue, metricErrCodeSuccess, clientID).Add(1)
			m.metrics.RequestLatency.WithLabelValues(metricServiceAuthService, metricMethodAuthServiceOAuthCallback, metricSuccessTrue, metricErrCodeSuccess, clientID).Observe(float64(time.Since(_begin_).Seconds()))
		} else {
			errCodeStr := strconv.Itoa(errCode)
			m.metrics.RequestCount.WithLabelValues(metricServiceAuthService, metricMethodAuthServiceOAuthCallback, metricSuccessFalse, errCodeStr, clientID).Add(1)
			m.metrics.RequestLatency.WithLabelValues(metricServiceAuthService, metricMethodAuthServiceOAuthCallback, metricSuccessFalse, errCodeStr, clientID).Observe(float64(time.Since(_begin_).Seconds()))
		}
	}(time.Now())

	return m.next.OAuthCallback(ctx, provider, code, state)
}

func (m metricsAuthService) GetMe(ctx context.Context, userID string) (user *types.User, err error) {

	defer func(_begin_ time.Time) {
		if m.metrics == nil {
			return
		}
		var (
			success = true
			errCode int
		)
		if err != nil {
			success = false
			errCode = fiber.StatusInternalServerError
			ec, ok := err.(withErrorCode)
			if ok {
				errCode = ec.Code()
			}
		}
		clientID := srvctx.GetClientID(ctx)
		if success {
			m.metrics.RequestCount.WithLabelValues(metricServiceAuthService, metricMethodAuthServiceGetMe, metricSuccessTrue, metricErrCodeSuccess, clientID).Add(1)
			m.metrics.RequestLatency.WithLabelValues(metricServiceAuthService, metricMethodAuthServiceGetMe, metricSuccessTrue, metricErrCodeSuccess, clientID).Observe(float64(time.Since(_begin_).Seconds()))
		} else {
			errCodeStr := strconv.Itoa(errCode)
			m.metrics.RequestCount.WithLabelValues(metricServiceAuthService, metricMethodAuthServiceGetMe, metricSuccessFalse, errCodeStr, clientID).Add(1)
			m.metrics.RequestLatency.WithLabelValues(metricServiceAuthService, metricMethodAuthServiceGetMe, metricSuccessFalse, errCodeStr, clientID).Observe(float64(time.Since(_begin_).Seconds()))
		}
	}(time.Now())

	return m.next.GetMe(ctx, userID)
}

func (m metricsAuthService) RefreshToken(ctx context.Context, refreshToken string) (token string, err error) {

	defer func(_begin_ time.Time) {
		if m.metrics == nil {
			return
		}
		var (
			success = true
			errCode int
		)
		if err != nil {
			success = false
			errCode = fiber.StatusInternalServerError
			ec, ok := err.(withErrorCode)
			if ok {
				errCode = ec.Code()
			}
		}
		clientID := srvctx.GetClientID(ctx)
		if success {
			m.metrics.RequestCount.WithLabelValues(metricServiceAuthService, metricMethodAuthServiceRefreshToken, metricSuccessTrue, metricErrCodeSuccess, clientID).Add(1)
			m.metrics.RequestLatency.WithLabelValues(metricServiceAuthService, metricMethodAuthServiceRefreshToken, metricSuccessTrue, metricErrCodeSuccess, clientID).Observe(float64(time.Since(_begin_).Seconds()))
		} else {
			errCodeStr := strconv.Itoa(errCode)
			m.metrics.RequestCount.WithLabelValues(metricServiceAuthService, metricMethodAuthServiceRefreshToken, metricSuccessFalse, errCodeStr, clientID).Add(1)
			m.metrics.RequestLatency.WithLabelValues(metricServiceAuthService, metricMethodAuthServiceRefreshToken, metricSuccessFalse, errCodeStr, clientID).Observe(float64(time.Since(_begin_).Seconds()))
		}
	}(time.Now())

	return m.next.RefreshToken(ctx, refreshToken)
}
