// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"context"
	"fmt"

	"github.com/sah4ez/ducalis-tg/pkg/contract"
	"github.com/sah4ez/ducalis-tg/pkg/types"
	otel "go.opentelemetry.io/otel"
	trace "go.opentelemetry.io/otel/trace"
)

type traceAuthService struct {
	next contract.AuthService
}

func traceMiddlewareAuthService(next contract.AuthService) contract.AuthService {
	return &traceAuthService{next: next}
}

func (svc traceAuthService) Register(ctx context.Context, req types.RegisterRequest) (user *types.User, token string, err error) {

	var span trace.Span
	ctx, span = otel.Tracer(fmt.Sprintf("tg:%s", VersionTg)).Start(ctx, "authService.register")
	defer func() {
		span.RecordError(err)
		span.End()
	}()
	return svc.next.Register(ctx, req)
}

func (svc traceAuthService) Login(ctx context.Context, email string, password string) (user *types.User, token string, err error) {

	var span trace.Span
	ctx, span = otel.Tracer(fmt.Sprintf("tg:%s", VersionTg)).Start(ctx, "authService.login")
	defer func() {
		span.RecordError(err)
		span.End()
	}()
	return svc.next.Login(ctx, email, password)
}

func (svc traceAuthService) OAuthAuthorize(ctx context.Context, provider string, redirectURL string) (authURL string, err error) {

	var span trace.Span
	ctx, span = otel.Tracer(fmt.Sprintf("tg:%s", VersionTg)).Start(ctx, "authService.oAuthAuthorize")
	defer func() {
		span.RecordError(err)
		span.End()
	}()
	return svc.next.OAuthAuthorize(ctx, provider, redirectURL)
}

func (svc traceAuthService) OAuthCallback(ctx context.Context, provider string, code string, state string) (user *types.User, token string, err error) {

	var span trace.Span
	ctx, span = otel.Tracer(fmt.Sprintf("tg:%s", VersionTg)).Start(ctx, "authService.oAuthCallback")
	defer func() {
		span.RecordError(err)
		span.End()
	}()
	return svc.next.OAuthCallback(ctx, provider, code, state)
}

func (svc traceAuthService) GetMe(ctx context.Context, userID string) (user *types.User, err error) {

	var span trace.Span
	ctx, span = otel.Tracer(fmt.Sprintf("tg:%s", VersionTg)).Start(ctx, "authService.getMe")
	defer func() {
		span.RecordError(err)
		span.End()
	}()
	return svc.next.GetMe(ctx, userID)
}

func (svc traceAuthService) RefreshToken(ctx context.Context, refreshToken string) (token string, err error) {

	var span trace.Span
	ctx, span = otel.Tracer(fmt.Sprintf("tg:%s", VersionTg)).Start(ctx, "authService.refreshToken")
	defer func() {
		span.RecordError(err)
		span.End()
	}()
	return svc.next.RefreshToken(ctx, refreshToken)
}
