// Code generated by 'T'ool 'G'ateway. DO NOT EDIT.
package transport

import (
	"context"

	"github.com/sah4ez/ducalis-tg/pkg/contract"
	"github.com/sah4ez/ducalis-tg/pkg/types"
)

type serverAuthService struct {
	svc            contract.AuthService
	register       AuthServiceRegister
	login          AuthServiceLogin
	oAuthAuthorize AuthServiceOAuthAuthorize
	oAuthCallback  AuthServiceOAuthCallback
	getMe          AuthServiceGetMe
	refreshToken   AuthServiceRefreshToken
}

type MiddlewareSetAuthService interface {
	Wrap(m MiddlewareAuthService)
	WrapRegister(m MiddlewareAuthServiceRegister)
	WrapLogin(m MiddlewareAuthServiceLogin)
	WrapOAuthAuthorize(m MiddlewareAuthServiceOAuthAuthorize)
	WrapOAuthCallback(m MiddlewareAuthServiceOAuthCallback)
	WrapGetMe(m MiddlewareAuthServiceGetMe)
	WrapRefreshToken(m MiddlewareAuthServiceRefreshToken)

	WithMetrics(metrics *Metrics)
}

func newServerAuthService(svc contract.AuthService) *serverAuthService {
	return &serverAuthService{
		getMe:          svc.GetMe,
		login:          svc.Login,
		oAuthAuthorize: svc.OAuthAuthorize,
		oAuthCallback:  svc.OAuthCallback,
		refreshToken:   svc.RefreshToken,
		register:       svc.Register,
		svc:            svc,
	}
}

func (srv *serverAuthService) Wrap(m MiddlewareAuthService) {
	srv.svc = m(srv.svc)
	srv.register = srv.svc.Register
	srv.login = srv.svc.Login
	srv.oAuthAuthorize = srv.svc.OAuthAuthorize
	srv.oAuthCallback = srv.svc.OAuthCallback
	srv.getMe = srv.svc.GetMe
	srv.refreshToken = srv.svc.RefreshToken
}

func (srv *serverAuthService) Register(ctx context.Context, req types.RegisterRequest) (user *types.User, token string, err error) {
	return srv.register(ctx, req)
}

func (srv *serverAuthService) Login(ctx context.Context, email string, password string) (user *types.User, token string, err error) {
	return srv.login(ctx, email, password)
}

func (srv *serverAuthService) OAuthAuthorize(ctx context.Context, provider string, redirectURL string) (authURL string, err error) {
	return srv.oAuthAuthorize(ctx, provider, redirectURL)
}

func (srv *serverAuthService) OAuthCallback(ctx context.Context, provider string, code string, state string) (user *types.User, token string, err error) {
	return srv.oAuthCallback(ctx, provider, code, state)
}

func (srv *serverAuthService) GetMe(ctx context.Context, userID string) (user *types.User, err error) {
	return srv.getMe(ctx, userID)
}

func (srv *serverAuthService) RefreshToken(ctx context.Context, refreshToken string) (token string, err error) {
	return srv.refreshToken(ctx, refreshToken)
}

func (srv *serverAuthService) WrapRegister(m MiddlewareAuthServiceRegister) {
	srv.register = m(srv.register)
}

func (srv *serverAuthService) WrapLogin(m MiddlewareAuthServiceLogin) {
	srv.login = m(srv.login)
}

func (srv *serverAuthService) WrapOAuthAuthorize(m MiddlewareAuthServiceOAuthAuthorize) {
	srv.oAuthAuthorize = m(srv.oAuthAuthorize)
}

func (srv *serverAuthService) WrapOAuthCallback(m MiddlewareAuthServiceOAuthCallback) {
	srv.oAuthCallback = m(srv.oAuthCallback)
}

func (srv *serverAuthService) WrapGetMe(m MiddlewareAuthServiceGetMe) {
	srv.getMe = m(srv.getMe)
}

func (srv *serverAuthService) WrapRefreshToken(m MiddlewareAuthServiceRefreshToken) {
	srv.refreshToken = m(srv.refreshToken)
}

func (srv *serverAuthService) WithMetrics(metrics *Metrics) {
	srv.Wrap(func(next contract.AuthService) contract.AuthService {
		return metricsMiddlewareAuthService(next, metrics)
	})
}
