// Code generated by 'T'ool 'G'ateway. DO NOT EDIT.
package transport

import (
	"context"
	"strconv"
	"time"

	"github.com/gofiber/fiber/v2"
	"github.com/sah4ez/ducalis-tg/internal/transport/srvctx"
	"github.com/sah4ez/ducalis-tg/pkg/contract"
	"github.com/sah4ez/ducalis-tg/pkg/types"
)

const (
	metricServiceIntegrationService = "integrationService"
)
const metricMethodIntegrationServiceCreateGitHub = "createGitHub"
const metricMethodIntegrationServiceCreateJira = "createJira"
const metricMethodIntegrationServiceCreateLinear = "createLinear"
const metricMethodIntegrationServiceList = "list"
const metricMethodIntegrationServiceDelete = "delete"
const metricMethodIntegrationServiceSync = "sync"
const metricMethodIntegrationServiceGetSyncStatus = "getSyncStatus"

type metricsIntegrationService struct {
	next    contract.IntegrationService
	metrics *Metrics
}

func metricsMiddlewareIntegrationService(next contract.IntegrationService, metrics *Metrics) contract.IntegrationService {
	return &metricsIntegrationService{
		metrics: metrics,
		next:    next,
	}
}

func (m metricsIntegrationService) CreateGitHub(ctx context.Context, req types.CreateGitHubIntegrationRequest) (integration *types.Integration, err error) {

	defer func(_begin_ time.Time) {
		if m.metrics == nil {
			return
		}
		var (
			success = true
			errCode int
		)
		if err != nil {
			success = false
			errCode = fiber.StatusInternalServerError
			ec, ok := err.(withErrorCode)
			if ok {
				errCode = ec.Code()
			}
		}
		clientID := srvctx.GetClientID(ctx)
		if success {
			m.metrics.RequestCount.WithLabelValues(metricServiceIntegrationService, metricMethodIntegrationServiceCreateGitHub, metricSuccessTrue, metricErrCodeSuccess, clientID).Add(1)
			m.metrics.RequestLatency.WithLabelValues(metricServiceIntegrationService, metricMethodIntegrationServiceCreateGitHub, metricSuccessTrue, metricErrCodeSuccess, clientID).Observe(float64(time.Since(_begin_).Seconds()))
		} else {
			errCodeStr := strconv.Itoa(errCode)
			m.metrics.RequestCount.WithLabelValues(metricServiceIntegrationService, metricMethodIntegrationServiceCreateGitHub, metricSuccessFalse, errCodeStr, clientID).Add(1)
			m.metrics.RequestLatency.WithLabelValues(metricServiceIntegrationService, metricMethodIntegrationServiceCreateGitHub, metricSuccessFalse, errCodeStr, clientID).Observe(float64(time.Since(_begin_).Seconds()))
		}
	}(time.Now())

	return m.next.CreateGitHub(ctx, req)
}

func (m metricsIntegrationService) CreateJira(ctx context.Context, req types.CreateJiraIntegrationRequest) (integration *types.Integration, err error) {

	defer func(_begin_ time.Time) {
		if m.metrics == nil {
			return
		}
		var (
			success = true
			errCode int
		)
		if err != nil {
			success = false
			errCode = fiber.StatusInternalServerError
			ec, ok := err.(withErrorCode)
			if ok {
				errCode = ec.Code()
			}
		}
		clientID := srvctx.GetClientID(ctx)
		if success {
			m.metrics.RequestCount.WithLabelValues(metricServiceIntegrationService, metricMethodIntegrationServiceCreateJira, metricSuccessTrue, metricErrCodeSuccess, clientID).Add(1)
			m.metrics.RequestLatency.WithLabelValues(metricServiceIntegrationService, metricMethodIntegrationServiceCreateJira, metricSuccessTrue, metricErrCodeSuccess, clientID).Observe(float64(time.Since(_begin_).Seconds()))
		} else {
			errCodeStr := strconv.Itoa(errCode)
			m.metrics.RequestCount.WithLabelValues(metricServiceIntegrationService, metricMethodIntegrationServiceCreateJira, metricSuccessFalse, errCodeStr, clientID).Add(1)
			m.metrics.RequestLatency.WithLabelValues(metricServiceIntegrationService, metricMethodIntegrationServiceCreateJira, metricSuccessFalse, errCodeStr, clientID).Observe(float64(time.Since(_begin_).Seconds()))
		}
	}(time.Now())

	return m.next.CreateJira(ctx, req)
}

func (m metricsIntegrationService) CreateLinear(ctx context.Context, req types.CreateLinearIntegrationRequest) (integration *types.Integration, err error) {

	defer func(_begin_ time.Time) {
		if m.metrics == nil {
			return
		}
		var (
			success = true
			errCode int
		)
		if err != nil {
			success = false
			errCode = fiber.StatusInternalServerError
			ec, ok := err.(withErrorCode)
			if ok {
				errCode = ec.Code()
			}
		}
		clientID := srvctx.GetClientID(ctx)
		if success {
			m.metrics.RequestCount.WithLabelValues(metricServiceIntegrationService, metricMethodIntegrationServiceCreateLinear, metricSuccessTrue, metricErrCodeSuccess, clientID).Add(1)
			m.metrics.RequestLatency.WithLabelValues(metricServiceIntegrationService, metricMethodIntegrationServiceCreateLinear, metricSuccessTrue, metricErrCodeSuccess, clientID).Observe(float64(time.Since(_begin_).Seconds()))
		} else {
			errCodeStr := strconv.Itoa(errCode)
			m.metrics.RequestCount.WithLabelValues(metricServiceIntegrationService, metricMethodIntegrationServiceCreateLinear, metricSuccessFalse, errCodeStr, clientID).Add(1)
			m.metrics.RequestLatency.WithLabelValues(metricServiceIntegrationService, metricMethodIntegrationServiceCreateLinear, metricSuccessFalse, errCodeStr, clientID).Observe(float64(time.Since(_begin_).Seconds()))
		}
	}(time.Now())

	return m.next.CreateLinear(ctx, req)
}

func (m metricsIntegrationService) List(ctx context.Context, workspaceID string) (integrations []types.Integration, err error) {

	defer func(_begin_ time.Time) {
		if m.metrics == nil {
			return
		}
		var (
			success = true
			errCode int
		)
		if err != nil {
			success = false
			errCode = fiber.StatusInternalServerError
			ec, ok := err.(withErrorCode)
			if ok {
				errCode = ec.Code()
			}
		}
		clientID := srvctx.GetClientID(ctx)
		if success {
			m.metrics.RequestCount.WithLabelValues(metricServiceIntegrationService, metricMethodIntegrationServiceList, metricSuccessTrue, metricErrCodeSuccess, clientID).Add(1)
			m.metrics.RequestLatency.WithLabelValues(metricServiceIntegrationService, metricMethodIntegrationServiceList, metricSuccessTrue, metricErrCodeSuccess, clientID).Observe(float64(time.Since(_begin_).Seconds()))
		} else {
			errCodeStr := strconv.Itoa(errCode)
			m.metrics.RequestCount.WithLabelValues(metricServiceIntegrationService, metricMethodIntegrationServiceList, metricSuccessFalse, errCodeStr, clientID).Add(1)
			m.metrics.RequestLatency.WithLabelValues(metricServiceIntegrationService, metricMethodIntegrationServiceList, metricSuccessFalse, errCodeStr, clientID).Observe(float64(time.Since(_begin_).Seconds()))
		}
	}(time.Now())

	return m.next.List(ctx, workspaceID)
}

func (m metricsIntegrationService) Delete(ctx context.Context, id string) (err error) {

	defer func(_begin_ time.Time) {
		if m.metrics == nil {
			return
		}
		var (
			success = true
			errCode int
		)
		if err != nil {
			success = false
			errCode = fiber.StatusInternalServerError
			ec, ok := err.(withErrorCode)
			if ok {
				errCode = ec.Code()
			}
		}
		clientID := srvctx.GetClientID(ctx)
		if success {
			m.metrics.RequestCount.WithLabelValues(metricServiceIntegrationService, metricMethodIntegrationServiceDelete, metricSuccessTrue, metricErrCodeSuccess, clientID).Add(1)
			m.metrics.RequestLatency.WithLabelValues(metricServiceIntegrationService, metricMethodIntegrationServiceDelete, metricSuccessTrue, metricErrCodeSuccess, clientID).Observe(float64(time.Since(_begin_).Seconds()))
		} else {
			errCodeStr := strconv.Itoa(errCode)
			m.metrics.RequestCount.WithLabelValues(metricServiceIntegrationService, metricMethodIntegrationServiceDelete, metricSuccessFalse, errCodeStr, clientID).Add(1)
			m.metrics.RequestLatency.WithLabelValues(metricServiceIntegrationService, metricMethodIntegrationServiceDelete, metricSuccessFalse, errCodeStr, clientID).Observe(float64(time.Since(_begin_).Seconds()))
		}
	}(time.Now())

	return m.next.Delete(ctx, id)
}

func (m metricsIntegrationService) Sync(ctx context.Context, id string) (result types.SyncResult, err error) {

	defer func(_begin_ time.Time) {
		if m.metrics == nil {
			return
		}
		var (
			success = true
			errCode int
		)
		if err != nil {
			success = false
			errCode = fiber.StatusInternalServerError
			ec, ok := err.(withErrorCode)
			if ok {
				errCode = ec.Code()
			}
		}
		clientID := srvctx.GetClientID(ctx)
		if success {
			m.metrics.RequestCount.WithLabelValues(metricServiceIntegrationService, metricMethodIntegrationServiceSync, metricSuccessTrue, metricErrCodeSuccess, clientID).Add(1)
			m.metrics.RequestLatency.WithLabelValues(metricServiceIntegrationService, metricMethodIntegrationServiceSync, metricSuccessTrue, metricErrCodeSuccess, clientID).Observe(float64(time.Since(_begin_).Seconds()))
		} else {
			errCodeStr := strconv.Itoa(errCode)
			m.metrics.RequestCount.WithLabelValues(metricServiceIntegrationService, metricMethodIntegrationServiceSync, metricSuccessFalse, errCodeStr, clientID).Add(1)
			m.metrics.RequestLatency.WithLabelValues(metricServiceIntegrationService, metricMethodIntegrationServiceSync, metricSuccessFalse, errCodeStr, clientID).Observe(float64(time.Since(_begin_).Seconds()))
		}
	}(time.Now())

	return m.next.Sync(ctx, id)
}

func (m metricsIntegrationService) GetSyncStatus(ctx context.Context, id string) (status types.SyncStatus, err error) {

	defer func(_begin_ time.Time) {
		if m.metrics == nil {
			return
		}
		var (
			success = true
			errCode int
		)
		if err != nil {
			success = false
			errCode = fiber.StatusInternalServerError
			ec, ok := err.(withErrorCode)
			if ok {
				errCode = ec.Code()
			}
		}
		clientID := srvctx.GetClientID(ctx)
		if success {
			m.metrics.RequestCount.WithLabelValues(metricServiceIntegrationService, metricMethodIntegrationServiceGetSyncStatus, metricSuccessTrue, metricErrCodeSuccess, clientID).Add(1)
			m.metrics.RequestLatency.WithLabelValues(metricServiceIntegrationService, metricMethodIntegrationServiceGetSyncStatus, metricSuccessTrue, metricErrCodeSuccess, clientID).Observe(float64(time.Since(_begin_).Seconds()))
		} else {
			errCodeStr := strconv.Itoa(errCode)
			m.metrics.RequestCount.WithLabelValues(metricServiceIntegrationService, metricMethodIntegrationServiceGetSyncStatus, metricSuccessFalse, errCodeStr, clientID).Add(1)
			m.metrics.RequestLatency.WithLabelValues(metricServiceIntegrationService, metricMethodIntegrationServiceGetSyncStatus, metricSuccessFalse, errCodeStr, clientID).Observe(float64(time.Since(_begin_).Seconds()))
		}
	}(time.Now())

	return m.next.GetSyncStatus(ctx, id)
}
