// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"context"
	"time"

	"github.com/rs/zerolog"
	"github.com/rs/zerolog/log"
	"github.com/sah4ez/ducalis-tg/internal/transport/viewer"
	"github.com/sah4ez/ducalis-tg/pkg/contract"
	"github.com/sah4ez/ducalis-tg/pkg/types"
)

type loggerIntegrationService struct {
	next contract.IntegrationService
}

func loggerMiddlewareIntegrationService() MiddlewareIntegrationService {
	return func(next contract.IntegrationService) contract.IntegrationService {
		return &loggerIntegrationService{next: next}
	}
}

func (m loggerIntegrationService) CreateGitHub(ctx context.Context, req types.CreateGitHubIntegrationRequest) (integration *types.Integration, err error) {
	logger := log.Ctx(ctx).With().Str("service", "IntegrationService").Str("method", "createGitHub").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method":   "integrationService.createGitHub",
				"request":  viewer.Sprintf("%+v", requestIntegrationServiceCreateGitHub{Req: req}),
				"response": viewer.Sprintf("%+v", responseIntegrationServiceCreateGitHub{Integration: integration}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call createGitHub")
			return
		}
		logger.Info().Func(logHandle).Msg("call createGitHub")
	}(time.Now())
	return m.next.CreateGitHub(ctx, req)
}

func (m loggerIntegrationService) CreateJira(ctx context.Context, req types.CreateJiraIntegrationRequest) (integration *types.Integration, err error) {
	logger := log.Ctx(ctx).With().Str("service", "IntegrationService").Str("method", "createJira").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method":   "integrationService.createJira",
				"request":  viewer.Sprintf("%+v", requestIntegrationServiceCreateJira{Req: req}),
				"response": viewer.Sprintf("%+v", responseIntegrationServiceCreateJira{Integration: integration}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call createJira")
			return
		}
		logger.Info().Func(logHandle).Msg("call createJira")
	}(time.Now())
	return m.next.CreateJira(ctx, req)
}

func (m loggerIntegrationService) CreateLinear(ctx context.Context, req types.CreateLinearIntegrationRequest) (integration *types.Integration, err error) {
	logger := log.Ctx(ctx).With().Str("service", "IntegrationService").Str("method", "createLinear").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method":   "integrationService.createLinear",
				"request":  viewer.Sprintf("%+v", requestIntegrationServiceCreateLinear{Req: req}),
				"response": viewer.Sprintf("%+v", responseIntegrationServiceCreateLinear{Integration: integration}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call createLinear")
			return
		}
		logger.Info().Func(logHandle).Msg("call createLinear")
	}(time.Now())
	return m.next.CreateLinear(ctx, req)
}

func (m loggerIntegrationService) List(ctx context.Context, workspaceID string) (integrations []types.Integration, err error) {
	logger := log.Ctx(ctx).With().Str("service", "IntegrationService").Str("method", "list").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method":   "integrationService.list",
				"request":  viewer.Sprintf("%+v", requestIntegrationServiceList{WorkspaceID: workspaceID}),
				"response": viewer.Sprintf("%+v", responseIntegrationServiceList{Integrations: integrations}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call list")
			return
		}
		logger.Info().Func(logHandle).Msg("call list")
	}(time.Now())
	return m.next.List(ctx, workspaceID)
}

func (m loggerIntegrationService) Delete(ctx context.Context, id string) (err error) {
	logger := log.Ctx(ctx).With().Str("service", "IntegrationService").Str("method", "delete").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method":   "integrationService.delete",
				"request":  viewer.Sprintf("%+v", requestIntegrationServiceDelete{Id: id}),
				"response": viewer.Sprintf("%+v", responseIntegrationServiceDelete{}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call delete")
			return
		}
		logger.Info().Func(logHandle).Msg("call delete")
	}(time.Now())
	return m.next.Delete(ctx, id)
}

func (m loggerIntegrationService) Sync(ctx context.Context, id string) (result types.SyncResult, err error) {
	logger := log.Ctx(ctx).With().Str("service", "IntegrationService").Str("method", "sync").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method":   "integrationService.sync",
				"request":  viewer.Sprintf("%+v", requestIntegrationServiceSync{Id: id}),
				"response": viewer.Sprintf("%+v", responseIntegrationServiceSync{Result: result}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call sync")
			return
		}
		logger.Info().Func(logHandle).Msg("call sync")
	}(time.Now())
	return m.next.Sync(ctx, id)
}

func (m loggerIntegrationService) GetSyncStatus(ctx context.Context, id string) (status types.SyncStatus, err error) {
	logger := log.Ctx(ctx).With().Str("service", "IntegrationService").Str("method", "getSyncStatus").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method":   "integrationService.getSyncStatus",
				"request":  viewer.Sprintf("%+v", requestIntegrationServiceGetSyncStatus{Id: id}),
				"response": viewer.Sprintf("%+v", responseIntegrationServiceGetSyncStatus{Status: status}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call getSyncStatus")
			return
		}
		logger.Info().Func(logHandle).Msg("call getSyncStatus")
	}(time.Now())
	return m.next.GetSyncStatus(ctx, id)
}
