// Code generated by 'T'ool 'G'ateway. DO NOT EDIT.
package transport

import (
	"context"

	"github.com/sah4ez/ducalis-tg/pkg/contract"
	"github.com/sah4ez/ducalis-tg/pkg/types"
)

type serverIntegrationService struct {
	svc           contract.IntegrationService
	createGitHub  IntegrationServiceCreateGitHub
	createJira    IntegrationServiceCreateJira
	createLinear  IntegrationServiceCreateLinear
	list          IntegrationServiceList
	delete        IntegrationServiceDelete
	sync          IntegrationServiceSync
	getSyncStatus IntegrationServiceGetSyncStatus
}

type MiddlewareSetIntegrationService interface {
	Wrap(m MiddlewareIntegrationService)
	WrapCreateGitHub(m MiddlewareIntegrationServiceCreateGitHub)
	WrapCreateJira(m MiddlewareIntegrationServiceCreateJira)
	WrapCreateLinear(m MiddlewareIntegrationServiceCreateLinear)
	WrapList(m MiddlewareIntegrationServiceList)
	WrapDelete(m MiddlewareIntegrationServiceDelete)
	WrapSync(m MiddlewareIntegrationServiceSync)
	WrapGetSyncStatus(m MiddlewareIntegrationServiceGetSyncStatus)

	WithMetrics(metrics *Metrics)
}

func newServerIntegrationService(svc contract.IntegrationService) *serverIntegrationService {
	return &serverIntegrationService{
		createGitHub:  svc.CreateGitHub,
		createJira:    svc.CreateJira,
		createLinear:  svc.CreateLinear,
		delete:        svc.Delete,
		getSyncStatus: svc.GetSyncStatus,
		list:          svc.List,
		svc:           svc,
		sync:          svc.Sync,
	}
}

func (srv *serverIntegrationService) Wrap(m MiddlewareIntegrationService) {
	srv.svc = m(srv.svc)
	srv.createGitHub = srv.svc.CreateGitHub
	srv.createJira = srv.svc.CreateJira
	srv.createLinear = srv.svc.CreateLinear
	srv.list = srv.svc.List
	srv.delete = srv.svc.Delete
	srv.sync = srv.svc.Sync
	srv.getSyncStatus = srv.svc.GetSyncStatus
}

func (srv *serverIntegrationService) CreateGitHub(ctx context.Context, req types.CreateGitHubIntegrationRequest) (integration *types.Integration, err error) {
	return srv.createGitHub(ctx, req)
}

func (srv *serverIntegrationService) CreateJira(ctx context.Context, req types.CreateJiraIntegrationRequest) (integration *types.Integration, err error) {
	return srv.createJira(ctx, req)
}

func (srv *serverIntegrationService) CreateLinear(ctx context.Context, req types.CreateLinearIntegrationRequest) (integration *types.Integration, err error) {
	return srv.createLinear(ctx, req)
}

func (srv *serverIntegrationService) List(ctx context.Context, workspaceID string) (integrations []types.Integration, err error) {
	return srv.list(ctx, workspaceID)
}

func (srv *serverIntegrationService) Delete(ctx context.Context, id string) (err error) {
	return srv.delete(ctx, id)
}

func (srv *serverIntegrationService) Sync(ctx context.Context, id string) (result types.SyncResult, err error) {
	return srv.sync(ctx, id)
}

func (srv *serverIntegrationService) GetSyncStatus(ctx context.Context, id string) (status types.SyncStatus, err error) {
	return srv.getSyncStatus(ctx, id)
}

func (srv *serverIntegrationService) WrapCreateGitHub(m MiddlewareIntegrationServiceCreateGitHub) {
	srv.createGitHub = m(srv.createGitHub)
}

func (srv *serverIntegrationService) WrapCreateJira(m MiddlewareIntegrationServiceCreateJira) {
	srv.createJira = m(srv.createJira)
}

func (srv *serverIntegrationService) WrapCreateLinear(m MiddlewareIntegrationServiceCreateLinear) {
	srv.createLinear = m(srv.createLinear)
}

func (srv *serverIntegrationService) WrapList(m MiddlewareIntegrationServiceList) {
	srv.list = m(srv.list)
}

func (srv *serverIntegrationService) WrapDelete(m MiddlewareIntegrationServiceDelete) {
	srv.delete = m(srv.delete)
}

func (srv *serverIntegrationService) WrapSync(m MiddlewareIntegrationServiceSync) {
	srv.sync = m(srv.sync)
}

func (srv *serverIntegrationService) WrapGetSyncStatus(m MiddlewareIntegrationServiceGetSyncStatus) {
	srv.getSyncStatus = m(srv.getSyncStatus)
}

func (srv *serverIntegrationService) WithMetrics(metrics *Metrics) {
	srv.Wrap(func(next contract.IntegrationService) contract.IntegrationService {
		return metricsMiddlewareIntegrationService(next, metrics)
	})
}
