// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import "github.com/sah4ez/ducalis-tg/pkg/types"

type requestIntegrationServiceCreateGitHub struct {
	Req types.CreateGitHubIntegrationRequest `json:"req,omitempty"`
}

type responseIntegrationServiceCreateGitHub struct {
	Integration *types.Integration `json:"integration,omitempty"`
}

type requestIntegrationServiceCreateJira struct {
	Req types.CreateJiraIntegrationRequest `json:"req,omitempty"`
}

type responseIntegrationServiceCreateJira struct {
	Integration *types.Integration `json:"integration,omitempty"`
}

type requestIntegrationServiceCreateLinear struct {
	Req types.CreateLinearIntegrationRequest `json:"req,omitempty"`
}

type responseIntegrationServiceCreateLinear struct {
	Integration *types.Integration `json:"integration,omitempty"`
}

type requestIntegrationServiceList struct {
	WorkspaceID string `json:"workspaceID,omitempty"`
}

type responseIntegrationServiceList struct {
	Integrations []types.Integration `json:"integrations,omitempty"`
}

type requestIntegrationServiceDelete struct {
	Id string `json:"id,omitempty"`
}

// Formal exchange type, please do not delete.
type responseIntegrationServiceDelete struct{}

type requestIntegrationServiceSync struct {
	Id string `json:"id,omitempty"`
}

type responseIntegrationServiceSync struct {
	Result types.SyncResult `json:"result,omitempty"`
}

type requestIntegrationServiceGetSyncStatus struct {
	Id string `json:"id,omitempty"`
}

type responseIntegrationServiceGetSyncStatus struct {
	Status types.SyncStatus `json:"status,omitempty"`
}
