// Code generated by 'T'ool 'G'ateway. DO NOT EDIT.
package transport

import "github.com/sah4ez/ducalis-tg/pkg/types"

type requestIntegrationServiceCreateGitHub struct {
	Req types.CreateGitHubIntegrationRequest `json:"req"`
}

type responseIntegrationServiceCreateGitHub struct {
	Integration *types.Integration `json:"integration"`
}

type requestIntegrationServiceCreateJira struct {
	Req types.CreateJiraIntegrationRequest `json:"req"`
}

type responseIntegrationServiceCreateJira struct {
	Integration *types.Integration `json:"integration"`
}

type requestIntegrationServiceCreateLinear struct {
	Req types.CreateLinearIntegrationRequest `json:"req"`
}

type responseIntegrationServiceCreateLinear struct {
	Integration *types.Integration `json:"integration"`
}

type requestIntegrationServiceList struct {
	WorkspaceID string `json:"-"`
}

type responseIntegrationServiceList struct {
	Integrations []types.Integration `json:"integrations"`
}

type requestIntegrationServiceDelete struct {
	Id string `json:"-"`
}

type responseIntegrationServiceDelete struct{}

type requestIntegrationServiceSync struct {
	Id string `json:"-"`
}

type responseIntegrationServiceSync struct {
	Result types.SyncResult `json:"result"`
}

type requestIntegrationServiceGetSyncStatus struct {
	Id string `json:"-"`
}

type responseIntegrationServiceGetSyncStatus struct {
	Status types.SyncStatus `json:"status"`
}
