// Code generated by 'T'ool 'G'ateway. DO NOT EDIT.
package transport

import (
	"context"
	"encoding/json"
	"strconv"

	"github.com/gofiber/fiber/v2"
	"github.com/sah4ez/ducalis-tg/internal/transport/srvctx"
)

func (http *httpIntegrationService) createGitHub(ctx context.Context, request requestIntegrationServiceCreateGitHub) (response responseIntegrationServiceCreateGitHub, err error) {

	ctx = withMethodLogger(ctx, "integrationService", "createGitHub")

	if response.Integration, err = http.svc.CreateGitHub(ctx, request.Req); err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpIntegrationService) serveCreateGitHub(ftx *fiber.Ctx) (err error) {

	clientID := srvctx.GetClientID(ftx.UserContext())
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		defer func() {
			if err == nil {
				server.metrics.EntryRequestsTotal.WithLabelValues("rest", "ok", clientID).Inc()
			}
		}()
	}
	var request requestIntegrationServiceCreateGitHub
	ftx.Response().SetStatusCode(201)
	bodyStream := ensureBodyReader(ftx.Context().RequestBodyStream())
	if err = json.NewDecoder(bodyStream).Decode(&request); err != nil {
		if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
			server.metrics.ErrorResponsesTotal.WithLabelValues("rest", "400", clientID).Inc()
		}
		ftx.Response().SetStatusCode(fiber.StatusBadRequest)
		_, err = ftx.WriteString("request body could not be decoded: " + err.Error())
		return
	}

	var response responseIntegrationServiceCreateGitHub
	if response, err = http.createGitHub(ftx.UserContext(), request); err == nil {
		var iResponse any = response
		if redirect, ok := iResponse.(withRedirect); ok {
			return ftx.Redirect(redirect.RedirectTo())
		}

		return sendResponse(ftx, response)
	}
	var statusCode int
	if errCoder, ok := err.(withErrorCode); ok {
		statusCode = errCoder.Code()
		ftx.Status(statusCode)
	} else {
		statusCode = fiber.StatusInternalServerError
		ftx.Status(statusCode)
	}
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		server.metrics.ErrorResponsesTotal.WithLabelValues("rest", strconv.Itoa(statusCode), clientID).Inc()
	}
	return sendResponse(ftx, err)
}
func (http *httpIntegrationService) createJira(ctx context.Context, request requestIntegrationServiceCreateJira) (response responseIntegrationServiceCreateJira, err error) {

	ctx = withMethodLogger(ctx, "integrationService", "createJira")

	if response.Integration, err = http.svc.CreateJira(ctx, request.Req); err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpIntegrationService) serveCreateJira(ftx *fiber.Ctx) (err error) {

	clientID := srvctx.GetClientID(ftx.UserContext())
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		defer func() {
			if err == nil {
				server.metrics.EntryRequestsTotal.WithLabelValues("rest", "ok", clientID).Inc()
			}
		}()
	}
	var request requestIntegrationServiceCreateJira
	ftx.Response().SetStatusCode(201)
	bodyStream := ensureBodyReader(ftx.Context().RequestBodyStream())
	if err = json.NewDecoder(bodyStream).Decode(&request); err != nil {
		if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
			server.metrics.ErrorResponsesTotal.WithLabelValues("rest", "400", clientID).Inc()
		}
		ftx.Response().SetStatusCode(fiber.StatusBadRequest)
		_, err = ftx.WriteString("request body could not be decoded: " + err.Error())
		return
	}

	var response responseIntegrationServiceCreateJira
	if response, err = http.createJira(ftx.UserContext(), request); err == nil {
		var iResponse any = response
		if redirect, ok := iResponse.(withRedirect); ok {
			return ftx.Redirect(redirect.RedirectTo())
		}

		return sendResponse(ftx, response)
	}
	var statusCode int
	if errCoder, ok := err.(withErrorCode); ok {
		statusCode = errCoder.Code()
		ftx.Status(statusCode)
	} else {
		statusCode = fiber.StatusInternalServerError
		ftx.Status(statusCode)
	}
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		server.metrics.ErrorResponsesTotal.WithLabelValues("rest", strconv.Itoa(statusCode), clientID).Inc()
	}
	return sendResponse(ftx, err)
}
func (http *httpIntegrationService) createLinear(ctx context.Context, request requestIntegrationServiceCreateLinear) (response responseIntegrationServiceCreateLinear, err error) {

	ctx = withMethodLogger(ctx, "integrationService", "createLinear")

	if response.Integration, err = http.svc.CreateLinear(ctx, request.Req); err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpIntegrationService) serveCreateLinear(ftx *fiber.Ctx) (err error) {

	clientID := srvctx.GetClientID(ftx.UserContext())
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		defer func() {
			if err == nil {
				server.metrics.EntryRequestsTotal.WithLabelValues("rest", "ok", clientID).Inc()
			}
		}()
	}
	var request requestIntegrationServiceCreateLinear
	ftx.Response().SetStatusCode(201)
	bodyStream := ensureBodyReader(ftx.Context().RequestBodyStream())
	if err = json.NewDecoder(bodyStream).Decode(&request); err != nil {
		if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
			server.metrics.ErrorResponsesTotal.WithLabelValues("rest", "400", clientID).Inc()
		}
		ftx.Response().SetStatusCode(fiber.StatusBadRequest)
		_, err = ftx.WriteString("request body could not be decoded: " + err.Error())
		return
	}

	var response responseIntegrationServiceCreateLinear
	if response, err = http.createLinear(ftx.UserContext(), request); err == nil {
		var iResponse any = response
		if redirect, ok := iResponse.(withRedirect); ok {
			return ftx.Redirect(redirect.RedirectTo())
		}

		return sendResponse(ftx, response)
	}
	var statusCode int
	if errCoder, ok := err.(withErrorCode); ok {
		statusCode = errCoder.Code()
		ftx.Status(statusCode)
	} else {
		statusCode = fiber.StatusInternalServerError
		ftx.Status(statusCode)
	}
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		server.metrics.ErrorResponsesTotal.WithLabelValues("rest", strconv.Itoa(statusCode), clientID).Inc()
	}
	return sendResponse(ftx, err)
}
func (http *httpIntegrationService) list(ctx context.Context, request requestIntegrationServiceList) (response responseIntegrationServiceList, err error) {

	ctx = withMethodLogger(ctx, "integrationService", "list")

	if response.Integrations, err = http.svc.List(ctx, request.WorkspaceID); err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpIntegrationService) serveList(ftx *fiber.Ctx) (err error) {

	clientID := srvctx.GetClientID(ftx.UserContext())
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		defer func() {
			if err == nil {
				server.metrics.EntryRequestsTotal.WithLabelValues("rest", "ok", clientID).Inc()
			}
		}()
	}
	var request requestIntegrationServiceList

	if _workspaceID_ := ftx.Params("workspaceID"); _workspaceID_ != "" {
		request.WorkspaceID = _workspaceID_
	}

	var response responseIntegrationServiceList
	if response, err = http.list(ftx.UserContext(), request); err == nil {
		var iResponse any = response
		if redirect, ok := iResponse.(withRedirect); ok {
			return ftx.Redirect(redirect.RedirectTo())
		}

		return sendResponse(ftx, response)
	}
	var statusCode int
	if errCoder, ok := err.(withErrorCode); ok {
		statusCode = errCoder.Code()
		ftx.Status(statusCode)
	} else {
		statusCode = fiber.StatusInternalServerError
		ftx.Status(statusCode)
	}
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		server.metrics.ErrorResponsesTotal.WithLabelValues("rest", strconv.Itoa(statusCode), clientID).Inc()
	}
	return sendResponse(ftx, err)
}
func (http *httpIntegrationService) delete(ctx context.Context, request requestIntegrationServiceDelete) (response responseIntegrationServiceDelete, err error) {

	ctx = withMethodLogger(ctx, "integrationService", "delete")

	if err = http.svc.Delete(ctx, request.Id); err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpIntegrationService) serveDelete(ftx *fiber.Ctx) (err error) {

	clientID := srvctx.GetClientID(ftx.UserContext())
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		defer func() {
			if err == nil {
				server.metrics.EntryRequestsTotal.WithLabelValues("rest", "ok", clientID).Inc()
			}
		}()
	}
	var request requestIntegrationServiceDelete
	ftx.Response().SetStatusCode(204)

	if _id_ := ftx.Params("id"); _id_ != "" {
		request.Id = _id_
	}

	var response responseIntegrationServiceDelete
	if response, err = http.delete(ftx.UserContext(), request); err == nil {
		var iResponse any = response
		if redirect, ok := iResponse.(withRedirect); ok {
			return ftx.Redirect(redirect.RedirectTo())
		}

		return sendResponse(ftx, response)
	}
	var statusCode int
	if errCoder, ok := err.(withErrorCode); ok {
		statusCode = errCoder.Code()
		ftx.Status(statusCode)
	} else {
		statusCode = fiber.StatusInternalServerError
		ftx.Status(statusCode)
	}
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		server.metrics.ErrorResponsesTotal.WithLabelValues("rest", strconv.Itoa(statusCode), clientID).Inc()
	}
	return sendResponse(ftx, err)
}
func (http *httpIntegrationService) sync(ctx context.Context, request requestIntegrationServiceSync) (response responseIntegrationServiceSync, err error) {

	ctx = withMethodLogger(ctx, "integrationService", "sync")

	if response.Result, err = http.svc.Sync(ctx, request.Id); err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpIntegrationService) serveSync(ftx *fiber.Ctx) (err error) {

	clientID := srvctx.GetClientID(ftx.UserContext())
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		defer func() {
			if err == nil {
				server.metrics.EntryRequestsTotal.WithLabelValues("rest", "ok", clientID).Inc()
			}
		}()
	}
	var request requestIntegrationServiceSync

	if _id_ := ftx.Params("id"); _id_ != "" {
		request.Id = _id_
	}

	var response responseIntegrationServiceSync
	if response, err = http.sync(ftx.UserContext(), request); err == nil {
		var iResponse any = response
		if redirect, ok := iResponse.(withRedirect); ok {
			return ftx.Redirect(redirect.RedirectTo())
		}

		return sendResponse(ftx, response)
	}
	var statusCode int
	if errCoder, ok := err.(withErrorCode); ok {
		statusCode = errCoder.Code()
		ftx.Status(statusCode)
	} else {
		statusCode = fiber.StatusInternalServerError
		ftx.Status(statusCode)
	}
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		server.metrics.ErrorResponsesTotal.WithLabelValues("rest", strconv.Itoa(statusCode), clientID).Inc()
	}
	return sendResponse(ftx, err)
}
func (http *httpIntegrationService) getSyncStatus(ctx context.Context, request requestIntegrationServiceGetSyncStatus) (response responseIntegrationServiceGetSyncStatus, err error) {

	ctx = withMethodLogger(ctx, "integrationService", "getSyncStatus")

	if response.Status, err = http.svc.GetSyncStatus(ctx, request.Id); err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpIntegrationService) serveGetSyncStatus(ftx *fiber.Ctx) (err error) {

	clientID := srvctx.GetClientID(ftx.UserContext())
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		defer func() {
			if err == nil {
				server.metrics.EntryRequestsTotal.WithLabelValues("rest", "ok", clientID).Inc()
			}
		}()
	}
	var request requestIntegrationServiceGetSyncStatus

	if _id_ := ftx.Params("id"); _id_ != "" {
		request.Id = _id_
	}

	var response responseIntegrationServiceGetSyncStatus
	if response, err = http.getSyncStatus(ftx.UserContext(), request); err == nil {
		var iResponse any = response
		if redirect, ok := iResponse.(withRedirect); ok {
			return ftx.Redirect(redirect.RedirectTo())
		}

		return sendResponse(ftx, response)
	}
	var statusCode int
	if errCoder, ok := err.(withErrorCode); ok {
		statusCode = errCoder.Code()
		ftx.Status(statusCode)
	} else {
		statusCode = fiber.StatusInternalServerError
		ftx.Status(statusCode)
	}
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		server.metrics.ErrorResponsesTotal.WithLabelValues("rest", strconv.Itoa(statusCode), clientID).Inc()
	}
	return sendResponse(ftx, err)
}
