// Code generated by 'T'ool 'G'ateway. DO NOT EDIT.
package transport

import (
	"context"

	"github.com/sah4ez/ducalis-tg/pkg/contract"
	"github.com/sah4ez/ducalis-tg/pkg/types"
)

type IntegrationServiceCreateGitHub func(ctx context.Context, req types.CreateGitHubIntegrationRequest) (integration *types.Integration, err error)
type IntegrationServiceCreateJira func(ctx context.Context, req types.CreateJiraIntegrationRequest) (integration *types.Integration, err error)
type IntegrationServiceCreateLinear func(ctx context.Context, req types.CreateLinearIntegrationRequest) (integration *types.Integration, err error)
type IntegrationServiceList func(ctx context.Context, workspaceID string) (integrations []types.Integration, err error)
type IntegrationServiceDelete func(ctx context.Context, id string) (err error)
type IntegrationServiceSync func(ctx context.Context, id string) (result types.SyncResult, err error)
type IntegrationServiceGetSyncStatus func(ctx context.Context, id string) (status types.SyncStatus, err error)

type MiddlewareIntegrationService func(next contract.IntegrationService) contract.IntegrationService

type MiddlewareIntegrationServiceCreateGitHub func(next IntegrationServiceCreateGitHub) IntegrationServiceCreateGitHub
type MiddlewareIntegrationServiceCreateJira func(next IntegrationServiceCreateJira) IntegrationServiceCreateJira
type MiddlewareIntegrationServiceCreateLinear func(next IntegrationServiceCreateLinear) IntegrationServiceCreateLinear
type MiddlewareIntegrationServiceList func(next IntegrationServiceList) IntegrationServiceList
type MiddlewareIntegrationServiceDelete func(next IntegrationServiceDelete) IntegrationServiceDelete
type MiddlewareIntegrationServiceSync func(next IntegrationServiceSync) IntegrationServiceSync
type MiddlewareIntegrationServiceGetSyncStatus func(next IntegrationServiceGetSyncStatus) IntegrationServiceGetSyncStatus
