// Code generated by 'T'ool 'G'ateway. DO NOT EDIT.
package transport

import (
	"github.com/gofiber/fiber/v2"
	"github.com/sah4ez/ducalis-tg/pkg/contract"
)

type httpIntegrationService struct {
	errorHandler ErrorHandler
	svc          *serverIntegrationService
	base         contract.IntegrationService
}

func newIntegrationService(svcIntegrationService contract.IntegrationService) (srv *httpIntegrationService) {

	srv = &httpIntegrationService{
		base: svcIntegrationService,
		svc:  newServerIntegrationService(svcIntegrationService),
	}
	return
}

func (http *httpIntegrationService) Service() *serverIntegrationService {
	return http.svc
}

func (http *httpIntegrationService) WithMetrics(metrics *Metrics) *httpIntegrationService {
	http.svc.WithMetrics(metrics)
	return http
}

func (http *httpIntegrationService) WithErrorHandler(handler ErrorHandler) *httpIntegrationService {
	http.errorHandler = handler
	return http
}

func (http *httpIntegrationService) WithRedirect() *httpIntegrationService {
	return http
}

func (http *httpIntegrationService) SetRoutes(route *fiber.App) {
	route.Post("/api/v1/integrations/github", http.serveCreateGitHub)
	route.Post("/api/v1/integrations/jira", http.serveCreateJira)
	route.Post("/api/v1/integrations/linear", http.serveCreateLinear)
	route.Get("/api/v1/workspaces/:workspaceID/integrations", http.serveList)
	route.Delete("/api/v1/integrations/:id", http.serveDelete)
	route.Post("/api/v1/integrations/:id/sync", http.serveSync)
	route.Get("/api/v1/integrations/:id/status", http.serveGetSyncStatus)
}
