// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"context"
	"fmt"

	"github.com/sah4ez/ducalis-tg/pkg/contract"
	"github.com/sah4ez/ducalis-tg/pkg/types"
	otel "go.opentelemetry.io/otel"
	trace "go.opentelemetry.io/otel/trace"
)

type traceIntegrationService struct {
	next contract.IntegrationService
}

func traceMiddlewareIntegrationService(next contract.IntegrationService) contract.IntegrationService {
	return &traceIntegrationService{next: next}
}

func (svc traceIntegrationService) CreateGitHub(ctx context.Context, req types.CreateGitHubIntegrationRequest) (integration *types.Integration, err error) {

	var span trace.Span
	ctx, span = otel.Tracer(fmt.Sprintf("tg:%s", VersionTg)).Start(ctx, "integrationService.createGitHub")
	defer func() {
		span.RecordError(err)
		span.End()
	}()
	return svc.next.CreateGitHub(ctx, req)
}

func (svc traceIntegrationService) CreateJira(ctx context.Context, req types.CreateJiraIntegrationRequest) (integration *types.Integration, err error) {

	var span trace.Span
	ctx, span = otel.Tracer(fmt.Sprintf("tg:%s", VersionTg)).Start(ctx, "integrationService.createJira")
	defer func() {
		span.RecordError(err)
		span.End()
	}()
	return svc.next.CreateJira(ctx, req)
}

func (svc traceIntegrationService) CreateLinear(ctx context.Context, req types.CreateLinearIntegrationRequest) (integration *types.Integration, err error) {

	var span trace.Span
	ctx, span = otel.Tracer(fmt.Sprintf("tg:%s", VersionTg)).Start(ctx, "integrationService.createLinear")
	defer func() {
		span.RecordError(err)
		span.End()
	}()
	return svc.next.CreateLinear(ctx, req)
}

func (svc traceIntegrationService) List(ctx context.Context, workspaceID string) (integrations []types.Integration, err error) {

	var span trace.Span
	ctx, span = otel.Tracer(fmt.Sprintf("tg:%s", VersionTg)).Start(ctx, "integrationService.list")
	defer func() {
		span.RecordError(err)
		span.End()
	}()
	return svc.next.List(ctx, workspaceID)
}

func (svc traceIntegrationService) Delete(ctx context.Context, id string) (err error) {

	var span trace.Span
	ctx, span = otel.Tracer(fmt.Sprintf("tg:%s", VersionTg)).Start(ctx, "integrationService.delete")
	defer func() {
		span.RecordError(err)
		span.End()
	}()
	return svc.next.Delete(ctx, id)
}

func (svc traceIntegrationService) Sync(ctx context.Context, id string) (result types.SyncResult, err error) {

	var span trace.Span
	ctx, span = otel.Tracer(fmt.Sprintf("tg:%s", VersionTg)).Start(ctx, "integrationService.sync")
	defer func() {
		span.RecordError(err)
		span.End()
	}()
	return svc.next.Sync(ctx, id)
}

func (svc traceIntegrationService) GetSyncStatus(ctx context.Context, id string) (status types.SyncStatus, err error) {

	var span trace.Span
	ctx, span = otel.Tracer(fmt.Sprintf("tg:%s", VersionTg)).Start(ctx, "integrationService.getSyncStatus")
	defer func() {
		span.RecordError(err)
		span.End()
	}()
	return svc.next.GetSyncStatus(ctx, id)
}
