// Code generated by 'T'ool 'G'ateway. DO NOT EDIT.
package transport

import (
	"context"
	"encoding/json"
	"strconv"

	"github.com/gofiber/fiber/v2"
	"github.com/sah4ez/ducalis-tg/internal/transport/srvctx"
)

func (http *httpTaskService) create(ctx context.Context, request requestTaskServiceCreate) (response responseTaskServiceCreate, err error) {

	ctx = withMethodLogger(ctx, "taskService", "create")

	if response.Task, err = http.svc.Create(ctx, request.Req); err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpTaskService) serveCreate(ftx *fiber.Ctx) (err error) {

	clientID := srvctx.GetClientID(ftx.UserContext())
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		defer func() {
			if err == nil {
				server.metrics.EntryRequestsTotal.WithLabelValues("rest", "ok", clientID).Inc()
			}
		}()
	}
	var request requestTaskServiceCreate
	ftx.Response().SetStatusCode(201)
	bodyStream := ensureBodyReader(ftx.Context().RequestBodyStream())
	if err = json.NewDecoder(bodyStream).Decode(&request); err != nil {
		if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
			server.metrics.ErrorResponsesTotal.WithLabelValues("rest", "400", clientID).Inc()
		}
		ftx.Response().SetStatusCode(fiber.StatusBadRequest)
		_, err = ftx.WriteString("request body could not be decoded: " + err.Error())
		return
	}

	var response responseTaskServiceCreate
	if response, err = http.create(ftx.UserContext(), request); err == nil {
		var iResponse any = response
		if redirect, ok := iResponse.(withRedirect); ok {
			return ftx.Redirect(redirect.RedirectTo())
		}

		return sendResponse(ftx, response)
	}
	var statusCode int
	if errCoder, ok := err.(withErrorCode); ok {
		statusCode = errCoder.Code()
		ftx.Status(statusCode)
	} else {
		statusCode = fiber.StatusInternalServerError
		ftx.Status(statusCode)
	}
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		server.metrics.ErrorResponsesTotal.WithLabelValues("rest", strconv.Itoa(statusCode), clientID).Inc()
	}
	return sendResponse(ftx, err)
}
func (http *httpTaskService) get(ctx context.Context, request requestTaskServiceGet) (response responseTaskServiceGet, err error) {

	ctx = withMethodLogger(ctx, "taskService", "get")

	if response.Task, err = http.svc.Get(ctx, request.Id); err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpTaskService) serveGet(ftx *fiber.Ctx) (err error) {

	clientID := srvctx.GetClientID(ftx.UserContext())
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		defer func() {
			if err == nil {
				server.metrics.EntryRequestsTotal.WithLabelValues("rest", "ok", clientID).Inc()
			}
		}()
	}
	var request requestTaskServiceGet

	if _id_ := ftx.Params("id"); _id_ != "" {
		request.Id = _id_
	}

	var response responseTaskServiceGet
	if response, err = http.get(ftx.UserContext(), request); err == nil {
		var iResponse any = response
		if redirect, ok := iResponse.(withRedirect); ok {
			return ftx.Redirect(redirect.RedirectTo())
		}

		return sendResponse(ftx, response.Task)
	}
	var statusCode int
	if errCoder, ok := err.(withErrorCode); ok {
		statusCode = errCoder.Code()
		ftx.Status(statusCode)
	} else {
		statusCode = fiber.StatusInternalServerError
		ftx.Status(statusCode)
	}
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		server.metrics.ErrorResponsesTotal.WithLabelValues("rest", strconv.Itoa(statusCode), clientID).Inc()
	}
	return sendResponse(ftx, err)
}
func (http *httpTaskService) update(ctx context.Context, request requestTaskServiceUpdate) (response responseTaskServiceUpdate, err error) {

	ctx = withMethodLogger(ctx, "taskService", "update")

	if response.Task, err = http.svc.Update(ctx, request.Id, request.Req); err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpTaskService) serveUpdate(ftx *fiber.Ctx) (err error) {

	clientID := srvctx.GetClientID(ftx.UserContext())
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		defer func() {
			if err == nil {
				server.metrics.EntryRequestsTotal.WithLabelValues("rest", "ok", clientID).Inc()
			}
		}()
	}
	var request requestTaskServiceUpdate
	bodyStream := ensureBodyReader(ftx.Context().RequestBodyStream())
	if err = json.NewDecoder(bodyStream).Decode(&request); err != nil {
		if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
			server.metrics.ErrorResponsesTotal.WithLabelValues("rest", "400", clientID).Inc()
		}
		ftx.Response().SetStatusCode(fiber.StatusBadRequest)
		_, err = ftx.WriteString("request body could not be decoded: " + err.Error())
		return
	}

	if _id_ := ftx.Params("id"); _id_ != "" {
		request.Id = _id_
	}

	var response responseTaskServiceUpdate
	if response, err = http.update(ftx.UserContext(), request); err == nil {
		var iResponse any = response
		if redirect, ok := iResponse.(withRedirect); ok {
			return ftx.Redirect(redirect.RedirectTo())
		}

		return sendResponse(ftx, response.Task)
	}
	var statusCode int
	if errCoder, ok := err.(withErrorCode); ok {
		statusCode = errCoder.Code()
		ftx.Status(statusCode)
	} else {
		statusCode = fiber.StatusInternalServerError
		ftx.Status(statusCode)
	}
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		server.metrics.ErrorResponsesTotal.WithLabelValues("rest", strconv.Itoa(statusCode), clientID).Inc()
	}
	return sendResponse(ftx, err)
}
func (http *httpTaskService) delete(ctx context.Context, request requestTaskServiceDelete) (response responseTaskServiceDelete, err error) {

	ctx = withMethodLogger(ctx, "taskService", "delete")

	if err = http.svc.Delete(ctx, request.Id); err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpTaskService) serveDelete(ftx *fiber.Ctx) (err error) {

	clientID := srvctx.GetClientID(ftx.UserContext())
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		defer func() {
			if err == nil {
				server.metrics.EntryRequestsTotal.WithLabelValues("rest", "ok", clientID).Inc()
			}
		}()
	}
	var request requestTaskServiceDelete
	ftx.Response().SetStatusCode(204)

	if _id_ := ftx.Params("id"); _id_ != "" {
		request.Id = _id_
	}

	var response responseTaskServiceDelete
	if response, err = http.delete(ftx.UserContext(), request); err == nil {
		var iResponse any = response
		if redirect, ok := iResponse.(withRedirect); ok {
			return ftx.Redirect(redirect.RedirectTo())
		}

		return sendResponse(ftx, response)
	}
	var statusCode int
	if errCoder, ok := err.(withErrorCode); ok {
		statusCode = errCoder.Code()
		ftx.Status(statusCode)
	} else {
		statusCode = fiber.StatusInternalServerError
		ftx.Status(statusCode)
	}
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		server.metrics.ErrorResponsesTotal.WithLabelValues("rest", strconv.Itoa(statusCode), clientID).Inc()
	}
	return sendResponse(ftx, err)
}
func (http *httpTaskService) list(ctx context.Context, request requestTaskServiceList) (response responseTaskServiceList, err error) {

	ctx = withMethodLogger(ctx, "taskService", "list")

	if response.Tasks, response.Total, err = http.svc.List(ctx, request.WorkspaceID, request.Status, request.Search, request.SortBy, request.SortDesc, request.Limit, request.Offset); err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpTaskService) serveList(ftx *fiber.Ctx) (err error) {

	clientID := srvctx.GetClientID(ftx.UserContext())
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		defer func() {
			if err == nil {
				server.metrics.EntryRequestsTotal.WithLabelValues("rest", "ok", clientID).Inc()
			}
		}()
	}
	var request requestTaskServiceList

	if _workspaceID_b := ftx.Request().URI().QueryArgs().Peek("workspaceID"); _workspaceID_b != nil {
		_workspaceID_ := string(_workspaceID_b)
		request.WorkspaceID = _workspaceID_
	}
	if _status_b := ftx.Request().URI().QueryArgs().Peek("status"); _status_b != nil {
		_status_ := string(_status_b)
		request.Status = _status_
	}
	if _search_b := ftx.Request().URI().QueryArgs().Peek("search"); _search_b != nil {
		_search_ := string(_search_b)
		request.Search = _search_
	}
	if _sortBy_b := ftx.Request().URI().QueryArgs().Peek("sortBy"); _sortBy_b != nil {
		_sortBy_ := string(_sortBy_b)
		request.SortBy = _sortBy_
	}
	if _sortDesc_b := ftx.Request().URI().QueryArgs().Peek("sortDesc"); _sortDesc_b != nil {
		_sortDesc_ := string(_sortDesc_b)
		var sortDesc bool
		if sortDesc, err = strconv.ParseBool(_sortDesc_); err != nil {
			ftx.Status(fiber.StatusBadRequest)
			return sendResponse(ftx, "url arguments could not be decoded: "+err.Error())
		}
		request.SortDesc = sortDesc
	}
	if _limit_b := ftx.Request().URI().QueryArgs().Peek("limit"); _limit_b != nil {
		_limit_ := string(_limit_b)
		var limit int
		if limit, err = strconv.Atoi(_limit_); err != nil {
			ftx.Status(fiber.StatusBadRequest)
			return sendResponse(ftx, "url arguments could not be decoded: "+err.Error())
		}
		request.Limit = limit
	}
	if _offset_b := ftx.Request().URI().QueryArgs().Peek("offset"); _offset_b != nil {
		_offset_ := string(_offset_b)
		var offset int
		if offset, err = strconv.Atoi(_offset_); err != nil {
			ftx.Status(fiber.StatusBadRequest)
			return sendResponse(ftx, "url arguments could not be decoded: "+err.Error())
		}
		request.Offset = offset
	}

	var response responseTaskServiceList
	if response, err = http.list(ftx.UserContext(), request); err == nil {
		var iResponse any = response
		if redirect, ok := iResponse.(withRedirect); ok {
			return ftx.Redirect(redirect.RedirectTo())
		}

		return sendResponse(ftx, response)
	}
	var statusCode int
	if errCoder, ok := err.(withErrorCode); ok {
		statusCode = errCoder.Code()
		ftx.Status(statusCode)
	} else {
		statusCode = fiber.StatusInternalServerError
		ftx.Status(statusCode)
	}
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		server.metrics.ErrorResponsesTotal.WithLabelValues("rest", strconv.Itoa(statusCode), clientID).Inc()
	}
	return sendResponse(ftx, err)
}
func (http *httpTaskService) setScores(ctx context.Context, request requestTaskServiceSetScores) (response responseTaskServiceSetScores, err error) {

	ctx = withMethodLogger(ctx, "taskService", "setScores")

	if response.Task, err = http.svc.SetScores(ctx, request.Id, request.Scores); err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpTaskService) serveSetScores(ftx *fiber.Ctx) (err error) {

	clientID := srvctx.GetClientID(ftx.UserContext())
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		defer func() {
			if err == nil {
				server.metrics.EntryRequestsTotal.WithLabelValues("rest", "ok", clientID).Inc()
			}
		}()
	}
	var request requestTaskServiceSetScores
	bodyStream := ensureBodyReader(ftx.Context().RequestBodyStream())
	if err = json.NewDecoder(bodyStream).Decode(&request); err != nil {
		if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
			server.metrics.ErrorResponsesTotal.WithLabelValues("rest", "400", clientID).Inc()
		}
		ftx.Response().SetStatusCode(fiber.StatusBadRequest)
		_, err = ftx.WriteString("request body could not be decoded: " + err.Error())
		return
	}

	if _id_ := ftx.Params("id"); _id_ != "" {
		request.Id = _id_
	}

	var response responseTaskServiceSetScores
	if response, err = http.setScores(ftx.UserContext(), request); err == nil {
		var iResponse any = response
		if redirect, ok := iResponse.(withRedirect); ok {
			return ftx.Redirect(redirect.RedirectTo())
		}

		return sendResponse(ftx, response.Task)
	}
	var statusCode int
	if errCoder, ok := err.(withErrorCode); ok {
		statusCode = errCoder.Code()
		ftx.Status(statusCode)
	} else {
		statusCode = fiber.StatusInternalServerError
		ftx.Status(statusCode)
	}
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		server.metrics.ErrorResponsesTotal.WithLabelValues("rest", strconv.Itoa(statusCode), clientID).Inc()
	}
	return sendResponse(ftx, err)
}
func (http *httpTaskService) vote(ctx context.Context, request requestTaskServiceVote) (response responseTaskServiceVote, err error) {

	ctx = withMethodLogger(ctx, "taskService", "vote")

	if response.Task, err = http.svc.Vote(ctx, request.Id, request.UserID, request.Weight); err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpTaskService) serveVote(ftx *fiber.Ctx) (err error) {

	clientID := srvctx.GetClientID(ftx.UserContext())
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		defer func() {
			if err == nil {
				server.metrics.EntryRequestsTotal.WithLabelValues("rest", "ok", clientID).Inc()
			}
		}()
	}
	var request requestTaskServiceVote
	bodyStream := ensureBodyReader(ftx.Context().RequestBodyStream())
	if err = json.NewDecoder(bodyStream).Decode(&request); err != nil {
		if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
			server.metrics.ErrorResponsesTotal.WithLabelValues("rest", "400", clientID).Inc()
		}
		ftx.Response().SetStatusCode(fiber.StatusBadRequest)
		_, err = ftx.WriteString("request body could not be decoded: " + err.Error())
		return
	}

	if _id_ := ftx.Params("id"); _id_ != "" {
		request.Id = _id_
	}

	var response responseTaskServiceVote
	if response, err = http.vote(ftx.UserContext(), request); err == nil {
		var iResponse any = response
		if redirect, ok := iResponse.(withRedirect); ok {
			return ftx.Redirect(redirect.RedirectTo())
		}

		return sendResponse(ftx, response.Task)
	}
	var statusCode int
	if errCoder, ok := err.(withErrorCode); ok {
		statusCode = errCoder.Code()
		ftx.Status(statusCode)
	} else {
		statusCode = fiber.StatusInternalServerError
		ftx.Status(statusCode)
	}
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		server.metrics.ErrorResponsesTotal.WithLabelValues("rest", strconv.Itoa(statusCode), clientID).Inc()
	}
	return sendResponse(ftx, err)
}
func (http *httpTaskService) removeVote(ctx context.Context, request requestTaskServiceRemoveVote) (response responseTaskServiceRemoveVote, err error) {

	ctx = withMethodLogger(ctx, "taskService", "removeVote")

	if response.Task, err = http.svc.RemoveVote(ctx, request.Id, request.UserID); err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpTaskService) serveRemoveVote(ftx *fiber.Ctx) (err error) {

	clientID := srvctx.GetClientID(ftx.UserContext())
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		defer func() {
			if err == nil {
				server.metrics.EntryRequestsTotal.WithLabelValues("rest", "ok", clientID).Inc()
			}
		}()
	}
	var request requestTaskServiceRemoveVote
	bodyStream := ensureBodyReader(ftx.Context().RequestBodyStream())
	if err = json.NewDecoder(bodyStream).Decode(&request); err != nil {
		if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
			server.metrics.ErrorResponsesTotal.WithLabelValues("rest", "400", clientID).Inc()
		}
		ftx.Response().SetStatusCode(fiber.StatusBadRequest)
		_, err = ftx.WriteString("request body could not be decoded: " + err.Error())
		return
	}

	if _id_ := ftx.Params("id"); _id_ != "" {
		request.Id = _id_
	}

	var response responseTaskServiceRemoveVote
	if response, err = http.removeVote(ftx.UserContext(), request); err == nil {
		var iResponse any = response
		if redirect, ok := iResponse.(withRedirect); ok {
			return ftx.Redirect(redirect.RedirectTo())
		}

		return sendResponse(ftx, response.Task)
	}
	var statusCode int
	if errCoder, ok := err.(withErrorCode); ok {
		statusCode = errCoder.Code()
		ftx.Status(statusCode)
	} else {
		statusCode = fiber.StatusInternalServerError
		ftx.Status(statusCode)
	}
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		server.metrics.ErrorResponsesTotal.WithLabelValues("rest", strconv.Itoa(statusCode), clientID).Inc()
	}
	return sendResponse(ftx, err)
}
func (http *httpTaskService) estimate(ctx context.Context, request requestTaskServiceEstimate) (response responseTaskServiceEstimate, err error) {

	ctx = withMethodLogger(ctx, "taskService", "estimate")

	if response.Task, err = http.svc.Estimate(ctx, request.Id, request.UserID, request.Value, request.Unit); err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpTaskService) serveEstimate(ftx *fiber.Ctx) (err error) {

	clientID := srvctx.GetClientID(ftx.UserContext())
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		defer func() {
			if err == nil {
				server.metrics.EntryRequestsTotal.WithLabelValues("rest", "ok", clientID).Inc()
			}
		}()
	}
	var request requestTaskServiceEstimate
	bodyStream := ensureBodyReader(ftx.Context().RequestBodyStream())
	if err = json.NewDecoder(bodyStream).Decode(&request); err != nil {
		if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
			server.metrics.ErrorResponsesTotal.WithLabelValues("rest", "400", clientID).Inc()
		}
		ftx.Response().SetStatusCode(fiber.StatusBadRequest)
		_, err = ftx.WriteString("request body could not be decoded: " + err.Error())
		return
	}

	if _id_ := ftx.Params("id"); _id_ != "" {
		request.Id = _id_
	}

	var response responseTaskServiceEstimate
	if response, err = http.estimate(ftx.UserContext(), request); err == nil {
		var iResponse any = response
		if redirect, ok := iResponse.(withRedirect); ok {
			return ftx.Redirect(redirect.RedirectTo())
		}

		return sendResponse(ftx, response.Task)
	}
	var statusCode int
	if errCoder, ok := err.(withErrorCode); ok {
		statusCode = errCoder.Code()
		ftx.Status(statusCode)
	} else {
		statusCode = fiber.StatusInternalServerError
		ftx.Status(statusCode)
	}
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		server.metrics.ErrorResponsesTotal.WithLabelValues("rest", strconv.Itoa(statusCode), clientID).Inc()
	}
	return sendResponse(ftx, err)
}
func (http *httpTaskService) setDependencies(ctx context.Context, request requestTaskServiceSetDependencies) (response responseTaskServiceSetDependencies, err error) {

	ctx = withMethodLogger(ctx, "taskService", "setDependencies")

	if response.Task, err = http.svc.SetDependencies(ctx, request.Id, request.DependencyIDs); err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpTaskService) serveSetDependencies(ftx *fiber.Ctx) (err error) {

	clientID := srvctx.GetClientID(ftx.UserContext())
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		defer func() {
			if err == nil {
				server.metrics.EntryRequestsTotal.WithLabelValues("rest", "ok", clientID).Inc()
			}
		}()
	}
	var request requestTaskServiceSetDependencies
	bodyStream := ensureBodyReader(ftx.Context().RequestBodyStream())
	if err = json.NewDecoder(bodyStream).Decode(&request); err != nil {
		if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
			server.metrics.ErrorResponsesTotal.WithLabelValues("rest", "400", clientID).Inc()
		}
		ftx.Response().SetStatusCode(fiber.StatusBadRequest)
		_, err = ftx.WriteString("request body could not be decoded: " + err.Error())
		return
	}

	if _id_ := ftx.Params("id"); _id_ != "" {
		request.Id = _id_
	}

	var response responseTaskServiceSetDependencies
	if response, err = http.setDependencies(ftx.UserContext(), request); err == nil {
		var iResponse any = response
		if redirect, ok := iResponse.(withRedirect); ok {
			return ftx.Redirect(redirect.RedirectTo())
		}

		return sendResponse(ftx, response.Task)
	}
	var statusCode int
	if errCoder, ok := err.(withErrorCode); ok {
		statusCode = errCoder.Code()
		ftx.Status(statusCode)
	} else {
		statusCode = fiber.StatusInternalServerError
		ftx.Status(statusCode)
	}
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		server.metrics.ErrorResponsesTotal.WithLabelValues("rest", strconv.Itoa(statusCode), clientID).Inc()
	}
	return sendResponse(ftx, err)
}
func (http *httpTaskService) getRanked(ctx context.Context, request requestTaskServiceGetRanked) (response responseTaskServiceGetRanked, err error) {

	ctx = withMethodLogger(ctx, "taskService", "getRanked")

	if response.Result, err = http.svc.GetRanked(ctx, request.WorkspaceID, request.Limit, request.Offset); err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpTaskService) serveGetRanked(ftx *fiber.Ctx) (err error) {

	clientID := srvctx.GetClientID(ftx.UserContext())
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		defer func() {
			if err == nil {
				server.metrics.EntryRequestsTotal.WithLabelValues("rest", "ok", clientID).Inc()
			}
		}()
	}
	var request requestTaskServiceGetRanked

	if _workspaceID_ := ftx.Params("workspaceID"); _workspaceID_ != "" {
		request.WorkspaceID = _workspaceID_
	}

	if _limit_b := ftx.Request().URI().QueryArgs().Peek("limit"); _limit_b != nil {
		_limit_ := string(_limit_b)
		var limit int
		if limit, err = strconv.Atoi(_limit_); err != nil {
			ftx.Status(fiber.StatusBadRequest)
			return sendResponse(ftx, "url arguments could not be decoded: "+err.Error())
		}
		request.Limit = limit
	}
	if _offset_b := ftx.Request().URI().QueryArgs().Peek("offset"); _offset_b != nil {
		_offset_ := string(_offset_b)
		var offset int
		if offset, err = strconv.Atoi(_offset_); err != nil {
			ftx.Status(fiber.StatusBadRequest)
			return sendResponse(ftx, "url arguments could not be decoded: "+err.Error())
		}
		request.Offset = offset
	}

	var response responseTaskServiceGetRanked
	if response, err = http.getRanked(ftx.UserContext(), request); err == nil {
		var iResponse any = response
		if redirect, ok := iResponse.(withRedirect); ok {
			return ftx.Redirect(redirect.RedirectTo())
		}

		return sendResponse(ftx, response)
	}
	var statusCode int
	if errCoder, ok := err.(withErrorCode); ok {
		statusCode = errCoder.Code()
		ftx.Status(statusCode)
	} else {
		statusCode = fiber.StatusInternalServerError
		ftx.Status(statusCode)
	}
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		server.metrics.ErrorResponsesTotal.WithLabelValues("rest", strconv.Itoa(statusCode), clientID).Inc()
	}
	return sendResponse(ftx, err)
}
