// Code generated by 'T'ool 'G'ateway. DO NOT EDIT.
package transport

import (
	"context"

	"github.com/sah4ez/ducalis-tg/pkg/contract"
	"github.com/sah4ez/ducalis-tg/pkg/types"
)

type serverTaskService struct {
	svc             contract.TaskService
	create          TaskServiceCreate
	get             TaskServiceGet
	update          TaskServiceUpdate
	delete          TaskServiceDelete
	list            TaskServiceList
	setScores       TaskServiceSetScores
	vote            TaskServiceVote
	removeVote      TaskServiceRemoveVote
	estimate        TaskServiceEstimate
	setDependencies TaskServiceSetDependencies
	getRanked       TaskServiceGetRanked
}

type MiddlewareSetTaskService interface {
	Wrap(m MiddlewareTaskService)
	WrapCreate(m MiddlewareTaskServiceCreate)
	WrapGet(m MiddlewareTaskServiceGet)
	WrapUpdate(m MiddlewareTaskServiceUpdate)
	WrapDelete(m MiddlewareTaskServiceDelete)
	WrapList(m MiddlewareTaskServiceList)
	WrapSetScores(m MiddlewareTaskServiceSetScores)
	WrapVote(m MiddlewareTaskServiceVote)
	WrapRemoveVote(m MiddlewareTaskServiceRemoveVote)
	WrapEstimate(m MiddlewareTaskServiceEstimate)
	WrapSetDependencies(m MiddlewareTaskServiceSetDependencies)
	WrapGetRanked(m MiddlewareTaskServiceGetRanked)

	WithMetrics(metrics *Metrics)
}

func newServerTaskService(svc contract.TaskService) *serverTaskService {
	return &serverTaskService{
		create:          svc.Create,
		delete:          svc.Delete,
		estimate:        svc.Estimate,
		get:             svc.Get,
		getRanked:       svc.GetRanked,
		list:            svc.List,
		removeVote:      svc.RemoveVote,
		setDependencies: svc.SetDependencies,
		setScores:       svc.SetScores,
		svc:             svc,
		update:          svc.Update,
		vote:            svc.Vote,
	}
}

func (srv *serverTaskService) Wrap(m MiddlewareTaskService) {
	srv.svc = m(srv.svc)
	srv.create = srv.svc.Create
	srv.get = srv.svc.Get
	srv.update = srv.svc.Update
	srv.delete = srv.svc.Delete
	srv.list = srv.svc.List
	srv.setScores = srv.svc.SetScores
	srv.vote = srv.svc.Vote
	srv.removeVote = srv.svc.RemoveVote
	srv.estimate = srv.svc.Estimate
	srv.setDependencies = srv.svc.SetDependencies
	srv.getRanked = srv.svc.GetRanked
}

func (srv *serverTaskService) Create(ctx context.Context, req types.CreateTaskRequest) (task *types.Task, err error) {
	return srv.create(ctx, req)
}

func (srv *serverTaskService) Get(ctx context.Context, id string) (task *types.Task, err error) {
	return srv.get(ctx, id)
}

func (srv *serverTaskService) Update(ctx context.Context, id string, req types.UpdateTaskRequest) (task *types.Task, err error) {
	return srv.update(ctx, id, req)
}

func (srv *serverTaskService) Delete(ctx context.Context, id string) (err error) {
	return srv.delete(ctx, id)
}

func (srv *serverTaskService) List(ctx context.Context, workspaceID string, status string, search string, sortBy string, sortDesc bool, limit int, offset int) (tasks []types.Task, total int, err error) {
	return srv.list(ctx, workspaceID, status, search, sortBy, sortDesc, limit, offset)
}

func (srv *serverTaskService) SetScores(ctx context.Context, id string, scores map[string]float64) (task *types.Task, err error) {
	return srv.setScores(ctx, id, scores)
}

func (srv *serverTaskService) Vote(ctx context.Context, id string, userID string, weight float64) (task *types.Task, err error) {
	return srv.vote(ctx, id, userID, weight)
}

func (srv *serverTaskService) RemoveVote(ctx context.Context, id string, userID string) (task *types.Task, err error) {
	return srv.removeVote(ctx, id, userID)
}

func (srv *serverTaskService) Estimate(ctx context.Context, id string, userID string, value float64, unit string) (task *types.Task, err error) {
	return srv.estimate(ctx, id, userID, value, unit)
}

func (srv *serverTaskService) SetDependencies(ctx context.Context, id string, dependencyIDs []string) (task *types.Task, err error) {
	return srv.setDependencies(ctx, id, dependencyIDs)
}

func (srv *serverTaskService) GetRanked(ctx context.Context, workspaceID string, limit int, offset int) (result types.RankedTasks, err error) {
	return srv.getRanked(ctx, workspaceID, limit, offset)
}

func (srv *serverTaskService) WrapCreate(m MiddlewareTaskServiceCreate) {
	srv.create = m(srv.create)
}

func (srv *serverTaskService) WrapGet(m MiddlewareTaskServiceGet) {
	srv.get = m(srv.get)
}

func (srv *serverTaskService) WrapUpdate(m MiddlewareTaskServiceUpdate) {
	srv.update = m(srv.update)
}

func (srv *serverTaskService) WrapDelete(m MiddlewareTaskServiceDelete) {
	srv.delete = m(srv.delete)
}

func (srv *serverTaskService) WrapList(m MiddlewareTaskServiceList) {
	srv.list = m(srv.list)
}

func (srv *serverTaskService) WrapSetScores(m MiddlewareTaskServiceSetScores) {
	srv.setScores = m(srv.setScores)
}

func (srv *serverTaskService) WrapVote(m MiddlewareTaskServiceVote) {
	srv.vote = m(srv.vote)
}

func (srv *serverTaskService) WrapRemoveVote(m MiddlewareTaskServiceRemoveVote) {
	srv.removeVote = m(srv.removeVote)
}

func (srv *serverTaskService) WrapEstimate(m MiddlewareTaskServiceEstimate) {
	srv.estimate = m(srv.estimate)
}

func (srv *serverTaskService) WrapSetDependencies(m MiddlewareTaskServiceSetDependencies) {
	srv.setDependencies = m(srv.setDependencies)
}

func (srv *serverTaskService) WrapGetRanked(m MiddlewareTaskServiceGetRanked) {
	srv.getRanked = m(srv.getRanked)
}

func (srv *serverTaskService) WithMetrics(metrics *Metrics) {
	srv.Wrap(func(next contract.TaskService) contract.TaskService {
		return metricsMiddlewareTaskService(next, metrics)
	})
}
