// Code generated by 'T'ool 'G'ateway. DO NOT EDIT.
package transport

import "github.com/sah4ez/ducalis-tg/pkg/types"

type requestTaskServiceCreate struct {
	Req types.CreateTaskRequest `json:"req"`
}

type responseTaskServiceCreate struct {
	Task *types.Task `json:"task"`
}

type requestTaskServiceGet struct {
	Id string `json:"-"`
}

type responseTaskServiceGet struct {
	*types.Task `json:",inline"`
}

type requestTaskServiceUpdate struct {
	Id  string                  `json:"-"`
	Req types.UpdateTaskRequest `json:"req"`
}

type responseTaskServiceUpdate struct {
	*types.Task `json:",inline"`
}

type requestTaskServiceDelete struct {
	Id string `json:"-"`
}

type responseTaskServiceDelete struct{}

type requestTaskServiceList struct {
	WorkspaceID string `json:"-"`
	Status      string `json:"-"`
	Search      string `json:"-"`
	SortBy      string `json:"-"`
	SortDesc    bool   `json:"-"`
	Limit       int    `json:"-"`
	Offset      int    `json:"-"`
}

type responseTaskServiceList struct {
	Tasks []types.Task `json:"tasks"`
	Total int          `json:"total"`
}

type requestTaskServiceSetScores struct {
	Id     string             `json:"-"`
	Scores map[string]float64 `json:"scores"`
}

type responseTaskServiceSetScores struct {
	*types.Task `json:",inline"`
}

type requestTaskServiceVote struct {
	Id     string  `json:"-"`
	UserID string  `json:"userID"`
	Weight float64 `json:"weight"`
}

type responseTaskServiceVote struct {
	*types.Task `json:",inline"`
}

type requestTaskServiceRemoveVote struct {
	Id     string `json:"-"`
	UserID string `json:"userID"`
}

type responseTaskServiceRemoveVote struct {
	*types.Task `json:",inline"`
}

type requestTaskServiceEstimate struct {
	Id     string  `json:"-"`
	UserID string  `json:"userID"`
	Value  float64 `json:"value"`
	Unit   string  `json:"unit"`
}

type responseTaskServiceEstimate struct {
	*types.Task `json:",inline"`
}

type requestTaskServiceSetDependencies struct {
	Id            string   `json:"-"`
	DependencyIDs []string `json:"dependencyIDs"`
}

type responseTaskServiceSetDependencies struct {
	*types.Task `json:",inline"`
}

type requestTaskServiceGetRanked struct {
	WorkspaceID string `json:"-"`
	Limit       int    `json:"-"`
	Offset      int    `json:"-"`
}

type responseTaskServiceGetRanked struct {
	Result types.RankedTasks `json:"result"`
}
