// Code generated by 'T'ool 'G'ateway. DO NOT EDIT.
package transport

import (
	"github.com/gofiber/fiber/v2"
	"github.com/sah4ez/ducalis-tg/pkg/contract"
)

type httpTaskService struct {
	errorHandler ErrorHandler
	svc          *serverTaskService
	base         contract.TaskService
}

func newTaskService(svcTaskService contract.TaskService) (srv *httpTaskService) {

	srv = &httpTaskService{
		base: svcTaskService,
		svc:  newServerTaskService(svcTaskService),
	}
	return
}

func (http *httpTaskService) Service() *serverTaskService {
	return http.svc
}

func (http *httpTaskService) WithMetrics(metrics *Metrics) *httpTaskService {
	http.svc.WithMetrics(metrics)
	return http
}

func (http *httpTaskService) WithErrorHandler(handler ErrorHandler) *httpTaskService {
	http.errorHandler = handler
	return http
}

func (http *httpTaskService) WithRedirect() *httpTaskService {
	return http
}

func (http *httpTaskService) SetRoutes(route *fiber.App) {
	route.Post("/api/v1/tasks", http.serveCreate)
	route.Get("/api/v1/tasks/:id", http.serveGet)
	route.Patch("/api/v1/tasks/:id", http.serveUpdate)
	route.Delete("/api/v1/tasks/:id", http.serveDelete)
	route.Get("/api/v1/tasks", http.serveList)
	route.Put("/api/v1/tasks/:id/scores", http.serveSetScores)
	route.Post("/api/v1/tasks/:id/vote", http.serveVote)
	route.Delete("/api/v1/tasks/:id/vote", http.serveRemoveVote)
	route.Post("/api/v1/tasks/:id/estimate", http.serveEstimate)
	route.Put("/api/v1/tasks/:id/dependencies", http.serveSetDependencies)
	route.Get("/api/v1/workspaces/:workspaceID/tasks/ranked", http.serveGetRanked)
}
