// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"github.com/gofiber/fiber/v2"
	"github.com/sah4ez/ducalis-tg/pkg/contract"
)

type httpTaskService struct {
	errorHandler     ErrorHandler
	maxBatchSize     int
	maxParallelBatch int
	svc              *serverTaskService
	base             contract.TaskService
}

func NewTaskService(svcTaskService contract.TaskService) (srv *httpTaskService) {

	srv = &httpTaskService{
		base: svcTaskService,
		svc:  newServerTaskService(svcTaskService),
	}
	return
}

func (http *httpTaskService) Service() *serverTaskService {
	return http.svc
}

func (http *httpTaskService) WithLog() *httpTaskService {
	http.svc.WithLog()
	return http
}

func (http *httpTaskService) WithTrace() *httpTaskService {
	http.svc.WithTrace()
	return http
}

func (http *httpTaskService) WithMetrics() *httpTaskService {
	http.svc.WithMetrics()
	return http
}

func (http *httpTaskService) WithErrorHandler(handler ErrorHandler) *httpTaskService {
	http.errorHandler = handler
	return http
}

func (http *httpTaskService) SetRoutes(route *fiber.App) {
	route.Post("/api/v1/tasks/taskService", http.serveBatch)
}
