// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"context"

	"github.com/sah4ez/ducalis-tg/pkg/contract"
	"github.com/sah4ez/ducalis-tg/pkg/types"
)

type TaskServiceCreate func(ctx context.Context, req types.CreateTaskRequest) (task *types.Task, err error)
type TaskServiceGet func(ctx context.Context, id string) (task *types.Task, err error)
type TaskServiceUpdate func(ctx context.Context, id string, req types.UpdateTaskRequest) (task *types.Task, err error)
type TaskServiceDelete func(ctx context.Context, id string) (err error)
type TaskServiceList func(ctx context.Context, req types.ListTasksRequest) (tasks []types.Task, total int, err error)
type TaskServiceSetScores func(ctx context.Context, taskID string, scores map[string]float64) (task *types.Task, err error)
type TaskServiceVote func(ctx context.Context, taskID string, userID string, weight float64) (task *types.Task, err error)
type TaskServiceRemoveVote func(ctx context.Context, taskID string, userID string) (task *types.Task, err error)
type TaskServiceEstimate func(ctx context.Context, taskID string, userID string, value float64) (task *types.Task, err error)
type TaskServiceSetDependencies func(ctx context.Context, taskID string, dependencyIDs []string) (task *types.Task, err error)
type TaskServiceGetRanked func(ctx context.Context, workspaceID string, limit int, offset int) (tasks []types.TaskWithRank, err error)

type MiddlewareTaskService func(next contract.TaskService) contract.TaskService

type MiddlewareTaskServiceCreate func(next TaskServiceCreate) TaskServiceCreate
type MiddlewareTaskServiceGet func(next TaskServiceGet) TaskServiceGet
type MiddlewareTaskServiceUpdate func(next TaskServiceUpdate) TaskServiceUpdate
type MiddlewareTaskServiceDelete func(next TaskServiceDelete) TaskServiceDelete
type MiddlewareTaskServiceList func(next TaskServiceList) TaskServiceList
type MiddlewareTaskServiceSetScores func(next TaskServiceSetScores) TaskServiceSetScores
type MiddlewareTaskServiceVote func(next TaskServiceVote) TaskServiceVote
type MiddlewareTaskServiceRemoveVote func(next TaskServiceRemoveVote) TaskServiceRemoveVote
type MiddlewareTaskServiceEstimate func(next TaskServiceEstimate) TaskServiceEstimate
type MiddlewareTaskServiceSetDependencies func(next TaskServiceSetDependencies) TaskServiceSetDependencies
type MiddlewareTaskServiceGetRanked func(next TaskServiceGetRanked) TaskServiceGetRanked
