// Code generated by 'T'ool 'G'ateway. DO NOT EDIT.
package transport

import (
	"context"
	"strconv"
	"time"

	"github.com/gofiber/fiber/v2"
	"github.com/sah4ez/ducalis-tg/internal/transport/srvctx"
	"github.com/sah4ez/ducalis-tg/pkg/contract"
	"github.com/sah4ez/ducalis-tg/pkg/types"
)

const (
	metricServiceTaskService = "taskService"
)
const metricMethodTaskServiceCreate = "create"
const metricMethodTaskServiceGet = "get"
const metricMethodTaskServiceUpdate = "update"
const metricMethodTaskServiceDelete = "delete"
const metricMethodTaskServiceList = "list"
const metricMethodTaskServiceSetScores = "setScores"
const metricMethodTaskServiceVote = "vote"
const metricMethodTaskServiceRemoveVote = "removeVote"
const metricMethodTaskServiceEstimate = "estimate"
const metricMethodTaskServiceSetDependencies = "setDependencies"
const metricMethodTaskServiceGetRanked = "getRanked"

type metricsTaskService struct {
	next    contract.TaskService
	metrics *Metrics
}

func metricsMiddlewareTaskService(next contract.TaskService, metrics *Metrics) contract.TaskService {
	return &metricsTaskService{
		metrics: metrics,
		next:    next,
	}
}

func (m metricsTaskService) Create(ctx context.Context, req types.CreateTaskRequest) (task *types.Task, err error) {

	defer func(_begin_ time.Time) {
		if m.metrics == nil {
			return
		}
		var (
			success = true
			errCode int
		)
		if err != nil {
			success = false
			errCode = fiber.StatusInternalServerError
			ec, ok := err.(withErrorCode)
			if ok {
				errCode = ec.Code()
			}
		}
		clientID := srvctx.GetClientID(ctx)
		if success {
			m.metrics.RequestCount.WithLabelValues(metricServiceTaskService, metricMethodTaskServiceCreate, metricSuccessTrue, metricErrCodeSuccess, clientID).Add(1)
			m.metrics.RequestLatency.WithLabelValues(metricServiceTaskService, metricMethodTaskServiceCreate, metricSuccessTrue, metricErrCodeSuccess, clientID).Observe(float64(time.Since(_begin_).Seconds()))
		} else {
			errCodeStr := strconv.Itoa(errCode)
			m.metrics.RequestCount.WithLabelValues(metricServiceTaskService, metricMethodTaskServiceCreate, metricSuccessFalse, errCodeStr, clientID).Add(1)
			m.metrics.RequestLatency.WithLabelValues(metricServiceTaskService, metricMethodTaskServiceCreate, metricSuccessFalse, errCodeStr, clientID).Observe(float64(time.Since(_begin_).Seconds()))
		}
	}(time.Now())

	return m.next.Create(ctx, req)
}

func (m metricsTaskService) Get(ctx context.Context, id string) (task *types.Task, err error) {

	defer func(_begin_ time.Time) {
		if m.metrics == nil {
			return
		}
		var (
			success = true
			errCode int
		)
		if err != nil {
			success = false
			errCode = fiber.StatusInternalServerError
			ec, ok := err.(withErrorCode)
			if ok {
				errCode = ec.Code()
			}
		}
		clientID := srvctx.GetClientID(ctx)
		if success {
			m.metrics.RequestCount.WithLabelValues(metricServiceTaskService, metricMethodTaskServiceGet, metricSuccessTrue, metricErrCodeSuccess, clientID).Add(1)
			m.metrics.RequestLatency.WithLabelValues(metricServiceTaskService, metricMethodTaskServiceGet, metricSuccessTrue, metricErrCodeSuccess, clientID).Observe(float64(time.Since(_begin_).Seconds()))
		} else {
			errCodeStr := strconv.Itoa(errCode)
			m.metrics.RequestCount.WithLabelValues(metricServiceTaskService, metricMethodTaskServiceGet, metricSuccessFalse, errCodeStr, clientID).Add(1)
			m.metrics.RequestLatency.WithLabelValues(metricServiceTaskService, metricMethodTaskServiceGet, metricSuccessFalse, errCodeStr, clientID).Observe(float64(time.Since(_begin_).Seconds()))
		}
	}(time.Now())

	return m.next.Get(ctx, id)
}

func (m metricsTaskService) Update(ctx context.Context, id string, req types.UpdateTaskRequest) (task *types.Task, err error) {

	defer func(_begin_ time.Time) {
		if m.metrics == nil {
			return
		}
		var (
			success = true
			errCode int
		)
		if err != nil {
			success = false
			errCode = fiber.StatusInternalServerError
			ec, ok := err.(withErrorCode)
			if ok {
				errCode = ec.Code()
			}
		}
		clientID := srvctx.GetClientID(ctx)
		if success {
			m.metrics.RequestCount.WithLabelValues(metricServiceTaskService, metricMethodTaskServiceUpdate, metricSuccessTrue, metricErrCodeSuccess, clientID).Add(1)
			m.metrics.RequestLatency.WithLabelValues(metricServiceTaskService, metricMethodTaskServiceUpdate, metricSuccessTrue, metricErrCodeSuccess, clientID).Observe(float64(time.Since(_begin_).Seconds()))
		} else {
			errCodeStr := strconv.Itoa(errCode)
			m.metrics.RequestCount.WithLabelValues(metricServiceTaskService, metricMethodTaskServiceUpdate, metricSuccessFalse, errCodeStr, clientID).Add(1)
			m.metrics.RequestLatency.WithLabelValues(metricServiceTaskService, metricMethodTaskServiceUpdate, metricSuccessFalse, errCodeStr, clientID).Observe(float64(time.Since(_begin_).Seconds()))
		}
	}(time.Now())

	return m.next.Update(ctx, id, req)
}

func (m metricsTaskService) Delete(ctx context.Context, id string) (err error) {

	defer func(_begin_ time.Time) {
		if m.metrics == nil {
			return
		}
		var (
			success = true
			errCode int
		)
		if err != nil {
			success = false
			errCode = fiber.StatusInternalServerError
			ec, ok := err.(withErrorCode)
			if ok {
				errCode = ec.Code()
			}
		}
		clientID := srvctx.GetClientID(ctx)
		if success {
			m.metrics.RequestCount.WithLabelValues(metricServiceTaskService, metricMethodTaskServiceDelete, metricSuccessTrue, metricErrCodeSuccess, clientID).Add(1)
			m.metrics.RequestLatency.WithLabelValues(metricServiceTaskService, metricMethodTaskServiceDelete, metricSuccessTrue, metricErrCodeSuccess, clientID).Observe(float64(time.Since(_begin_).Seconds()))
		} else {
			errCodeStr := strconv.Itoa(errCode)
			m.metrics.RequestCount.WithLabelValues(metricServiceTaskService, metricMethodTaskServiceDelete, metricSuccessFalse, errCodeStr, clientID).Add(1)
			m.metrics.RequestLatency.WithLabelValues(metricServiceTaskService, metricMethodTaskServiceDelete, metricSuccessFalse, errCodeStr, clientID).Observe(float64(time.Since(_begin_).Seconds()))
		}
	}(time.Now())

	return m.next.Delete(ctx, id)
}

func (m metricsTaskService) List(ctx context.Context, workspaceID string, status string, search string, sortBy string, sortDesc bool, limit int, offset int) (tasks []types.Task, total int, err error) {

	defer func(_begin_ time.Time) {
		if m.metrics == nil {
			return
		}
		var (
			success = true
			errCode int
		)
		if err != nil {
			success = false
			errCode = fiber.StatusInternalServerError
			ec, ok := err.(withErrorCode)
			if ok {
				errCode = ec.Code()
			}
		}
		clientID := srvctx.GetClientID(ctx)
		if success {
			m.metrics.RequestCount.WithLabelValues(metricServiceTaskService, metricMethodTaskServiceList, metricSuccessTrue, metricErrCodeSuccess, clientID).Add(1)
			m.metrics.RequestLatency.WithLabelValues(metricServiceTaskService, metricMethodTaskServiceList, metricSuccessTrue, metricErrCodeSuccess, clientID).Observe(float64(time.Since(_begin_).Seconds()))
		} else {
			errCodeStr := strconv.Itoa(errCode)
			m.metrics.RequestCount.WithLabelValues(metricServiceTaskService, metricMethodTaskServiceList, metricSuccessFalse, errCodeStr, clientID).Add(1)
			m.metrics.RequestLatency.WithLabelValues(metricServiceTaskService, metricMethodTaskServiceList, metricSuccessFalse, errCodeStr, clientID).Observe(float64(time.Since(_begin_).Seconds()))
		}
	}(time.Now())

	return m.next.List(ctx, workspaceID, status, search, sortBy, sortDesc, limit, offset)
}

func (m metricsTaskService) SetScores(ctx context.Context, id string, scores map[string]float64) (task *types.Task, err error) {

	defer func(_begin_ time.Time) {
		if m.metrics == nil {
			return
		}
		var (
			success = true
			errCode int
		)
		if err != nil {
			success = false
			errCode = fiber.StatusInternalServerError
			ec, ok := err.(withErrorCode)
			if ok {
				errCode = ec.Code()
			}
		}
		clientID := srvctx.GetClientID(ctx)
		if success {
			m.metrics.RequestCount.WithLabelValues(metricServiceTaskService, metricMethodTaskServiceSetScores, metricSuccessTrue, metricErrCodeSuccess, clientID).Add(1)
			m.metrics.RequestLatency.WithLabelValues(metricServiceTaskService, metricMethodTaskServiceSetScores, metricSuccessTrue, metricErrCodeSuccess, clientID).Observe(float64(time.Since(_begin_).Seconds()))
		} else {
			errCodeStr := strconv.Itoa(errCode)
			m.metrics.RequestCount.WithLabelValues(metricServiceTaskService, metricMethodTaskServiceSetScores, metricSuccessFalse, errCodeStr, clientID).Add(1)
			m.metrics.RequestLatency.WithLabelValues(metricServiceTaskService, metricMethodTaskServiceSetScores, metricSuccessFalse, errCodeStr, clientID).Observe(float64(time.Since(_begin_).Seconds()))
		}
	}(time.Now())

	return m.next.SetScores(ctx, id, scores)
}

func (m metricsTaskService) Vote(ctx context.Context, id string, userID string, weight float64) (task *types.Task, err error) {

	defer func(_begin_ time.Time) {
		if m.metrics == nil {
			return
		}
		var (
			success = true
			errCode int
		)
		if err != nil {
			success = false
			errCode = fiber.StatusInternalServerError
			ec, ok := err.(withErrorCode)
			if ok {
				errCode = ec.Code()
			}
		}
		clientID := srvctx.GetClientID(ctx)
		if success {
			m.metrics.RequestCount.WithLabelValues(metricServiceTaskService, metricMethodTaskServiceVote, metricSuccessTrue, metricErrCodeSuccess, clientID).Add(1)
			m.metrics.RequestLatency.WithLabelValues(metricServiceTaskService, metricMethodTaskServiceVote, metricSuccessTrue, metricErrCodeSuccess, clientID).Observe(float64(time.Since(_begin_).Seconds()))
		} else {
			errCodeStr := strconv.Itoa(errCode)
			m.metrics.RequestCount.WithLabelValues(metricServiceTaskService, metricMethodTaskServiceVote, metricSuccessFalse, errCodeStr, clientID).Add(1)
			m.metrics.RequestLatency.WithLabelValues(metricServiceTaskService, metricMethodTaskServiceVote, metricSuccessFalse, errCodeStr, clientID).Observe(float64(time.Since(_begin_).Seconds()))
		}
	}(time.Now())

	return m.next.Vote(ctx, id, userID, weight)
}

func (m metricsTaskService) RemoveVote(ctx context.Context, id string, userID string) (task *types.Task, err error) {

	defer func(_begin_ time.Time) {
		if m.metrics == nil {
			return
		}
		var (
			success = true
			errCode int
		)
		if err != nil {
			success = false
			errCode = fiber.StatusInternalServerError
			ec, ok := err.(withErrorCode)
			if ok {
				errCode = ec.Code()
			}
		}
		clientID := srvctx.GetClientID(ctx)
		if success {
			m.metrics.RequestCount.WithLabelValues(metricServiceTaskService, metricMethodTaskServiceRemoveVote, metricSuccessTrue, metricErrCodeSuccess, clientID).Add(1)
			m.metrics.RequestLatency.WithLabelValues(metricServiceTaskService, metricMethodTaskServiceRemoveVote, metricSuccessTrue, metricErrCodeSuccess, clientID).Observe(float64(time.Since(_begin_).Seconds()))
		} else {
			errCodeStr := strconv.Itoa(errCode)
			m.metrics.RequestCount.WithLabelValues(metricServiceTaskService, metricMethodTaskServiceRemoveVote, metricSuccessFalse, errCodeStr, clientID).Add(1)
			m.metrics.RequestLatency.WithLabelValues(metricServiceTaskService, metricMethodTaskServiceRemoveVote, metricSuccessFalse, errCodeStr, clientID).Observe(float64(time.Since(_begin_).Seconds()))
		}
	}(time.Now())

	return m.next.RemoveVote(ctx, id, userID)
}

func (m metricsTaskService) Estimate(ctx context.Context, id string, userID string, value float64, unit string) (task *types.Task, err error) {

	defer func(_begin_ time.Time) {
		if m.metrics == nil {
			return
		}
		var (
			success = true
			errCode int
		)
		if err != nil {
			success = false
			errCode = fiber.StatusInternalServerError
			ec, ok := err.(withErrorCode)
			if ok {
				errCode = ec.Code()
			}
		}
		clientID := srvctx.GetClientID(ctx)
		if success {
			m.metrics.RequestCount.WithLabelValues(metricServiceTaskService, metricMethodTaskServiceEstimate, metricSuccessTrue, metricErrCodeSuccess, clientID).Add(1)
			m.metrics.RequestLatency.WithLabelValues(metricServiceTaskService, metricMethodTaskServiceEstimate, metricSuccessTrue, metricErrCodeSuccess, clientID).Observe(float64(time.Since(_begin_).Seconds()))
		} else {
			errCodeStr := strconv.Itoa(errCode)
			m.metrics.RequestCount.WithLabelValues(metricServiceTaskService, metricMethodTaskServiceEstimate, metricSuccessFalse, errCodeStr, clientID).Add(1)
			m.metrics.RequestLatency.WithLabelValues(metricServiceTaskService, metricMethodTaskServiceEstimate, metricSuccessFalse, errCodeStr, clientID).Observe(float64(time.Since(_begin_).Seconds()))
		}
	}(time.Now())

	return m.next.Estimate(ctx, id, userID, value, unit)
}

func (m metricsTaskService) SetDependencies(ctx context.Context, id string, dependencyIDs []string) (task *types.Task, err error) {

	defer func(_begin_ time.Time) {
		if m.metrics == nil {
			return
		}
		var (
			success = true
			errCode int
		)
		if err != nil {
			success = false
			errCode = fiber.StatusInternalServerError
			ec, ok := err.(withErrorCode)
			if ok {
				errCode = ec.Code()
			}
		}
		clientID := srvctx.GetClientID(ctx)
		if success {
			m.metrics.RequestCount.WithLabelValues(metricServiceTaskService, metricMethodTaskServiceSetDependencies, metricSuccessTrue, metricErrCodeSuccess, clientID).Add(1)
			m.metrics.RequestLatency.WithLabelValues(metricServiceTaskService, metricMethodTaskServiceSetDependencies, metricSuccessTrue, metricErrCodeSuccess, clientID).Observe(float64(time.Since(_begin_).Seconds()))
		} else {
			errCodeStr := strconv.Itoa(errCode)
			m.metrics.RequestCount.WithLabelValues(metricServiceTaskService, metricMethodTaskServiceSetDependencies, metricSuccessFalse, errCodeStr, clientID).Add(1)
			m.metrics.RequestLatency.WithLabelValues(metricServiceTaskService, metricMethodTaskServiceSetDependencies, metricSuccessFalse, errCodeStr, clientID).Observe(float64(time.Since(_begin_).Seconds()))
		}
	}(time.Now())

	return m.next.SetDependencies(ctx, id, dependencyIDs)
}

func (m metricsTaskService) GetRanked(ctx context.Context, workspaceID string, limit int, offset int) (result types.RankedTasks, err error) {

	defer func(_begin_ time.Time) {
		if m.metrics == nil {
			return
		}
		var (
			success = true
			errCode int
		)
		if err != nil {
			success = false
			errCode = fiber.StatusInternalServerError
			ec, ok := err.(withErrorCode)
			if ok {
				errCode = ec.Code()
			}
		}
		clientID := srvctx.GetClientID(ctx)
		if success {
			m.metrics.RequestCount.WithLabelValues(metricServiceTaskService, metricMethodTaskServiceGetRanked, metricSuccessTrue, metricErrCodeSuccess, clientID).Add(1)
			m.metrics.RequestLatency.WithLabelValues(metricServiceTaskService, metricMethodTaskServiceGetRanked, metricSuccessTrue, metricErrCodeSuccess, clientID).Observe(float64(time.Since(_begin_).Seconds()))
		} else {
			errCodeStr := strconv.Itoa(errCode)
			m.metrics.RequestCount.WithLabelValues(metricServiceTaskService, metricMethodTaskServiceGetRanked, metricSuccessFalse, errCodeStr, clientID).Add(1)
			m.metrics.RequestLatency.WithLabelValues(metricServiceTaskService, metricMethodTaskServiceGetRanked, metricSuccessFalse, errCodeStr, clientID).Observe(float64(time.Since(_begin_).Seconds()))
		}
	}(time.Now())

	return m.next.GetRanked(ctx, workspaceID, limit, offset)
}
