// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"context"
	"time"

	"github.com/rs/zerolog"
	"github.com/rs/zerolog/log"
	"github.com/sah4ez/ducalis-tg/internal/transport/viewer"
	"github.com/sah4ez/ducalis-tg/pkg/contract"
	"github.com/sah4ez/ducalis-tg/pkg/types"
)

type loggerTaskService struct {
	next contract.TaskService
}

func loggerMiddlewareTaskService() MiddlewareTaskService {
	return func(next contract.TaskService) contract.TaskService {
		return &loggerTaskService{next: next}
	}
}

func (m loggerTaskService) Create(ctx context.Context, req types.CreateTaskRequest) (task *types.Task, err error) {
	logger := log.Ctx(ctx).With().Str("service", "TaskService").Str("method", "create").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method":   "taskService.create",
				"request":  viewer.Sprintf("%+v", requestTaskServiceCreate{Req: req}),
				"response": viewer.Sprintf("%+v", responseTaskServiceCreate{Task: task}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call create")
			return
		}
		logger.Info().Func(logHandle).Msg("call create")
	}(time.Now())
	return m.next.Create(ctx, req)
}

func (m loggerTaskService) Get(ctx context.Context, id string) (task *types.Task, err error) {
	logger := log.Ctx(ctx).With().Str("service", "TaskService").Str("method", "get").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method":   "taskService.get",
				"request":  viewer.Sprintf("%+v", requestTaskServiceGet{Id: id}),
				"response": viewer.Sprintf("%+v", responseTaskServiceGet{Task: task}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call get")
			return
		}
		logger.Info().Func(logHandle).Msg("call get")
	}(time.Now())
	return m.next.Get(ctx, id)
}

func (m loggerTaskService) Update(ctx context.Context, id string, req types.UpdateTaskRequest) (task *types.Task, err error) {
	logger := log.Ctx(ctx).With().Str("service", "TaskService").Str("method", "update").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method": "taskService.update",
				"request": viewer.Sprintf("%+v", requestTaskServiceUpdate{
					Id:  id,
					Req: req,
				}),
				"response": viewer.Sprintf("%+v", responseTaskServiceUpdate{Task: task}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call update")
			return
		}
		logger.Info().Func(logHandle).Msg("call update")
	}(time.Now())
	return m.next.Update(ctx, id, req)
}

func (m loggerTaskService) Delete(ctx context.Context, id string) (err error) {
	logger := log.Ctx(ctx).With().Str("service", "TaskService").Str("method", "delete").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method":   "taskService.delete",
				"request":  viewer.Sprintf("%+v", requestTaskServiceDelete{Id: id}),
				"response": viewer.Sprintf("%+v", responseTaskServiceDelete{}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call delete")
			return
		}
		logger.Info().Func(logHandle).Msg("call delete")
	}(time.Now())
	return m.next.Delete(ctx, id)
}

func (m loggerTaskService) List(ctx context.Context, req types.ListTasksRequest) (tasks []types.Task, total int, err error) {
	logger := log.Ctx(ctx).With().Str("service", "TaskService").Str("method", "list").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method":  "taskService.list",
				"request": viewer.Sprintf("%+v", requestTaskServiceList{Req: req}),
				"response": viewer.Sprintf("%+v", responseTaskServiceList{
					Tasks: tasks,
					Total: total,
				}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call list")
			return
		}
		logger.Info().Func(logHandle).Msg("call list")
	}(time.Now())
	return m.next.List(ctx, req)
}

func (m loggerTaskService) SetScores(ctx context.Context, taskID string, scores map[string]float64) (task *types.Task, err error) {
	logger := log.Ctx(ctx).With().Str("service", "TaskService").Str("method", "setScores").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method": "taskService.setScores",
				"request": viewer.Sprintf("%+v", requestTaskServiceSetScores{
					Scores: scores,
					TaskID: taskID,
				}),
				"response": viewer.Sprintf("%+v", responseTaskServiceSetScores{Task: task}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call setScores")
			return
		}
		logger.Info().Func(logHandle).Msg("call setScores")
	}(time.Now())
	return m.next.SetScores(ctx, taskID, scores)
}

func (m loggerTaskService) Vote(ctx context.Context, taskID string, userID string, weight float64) (task *types.Task, err error) {
	logger := log.Ctx(ctx).With().Str("service", "TaskService").Str("method", "vote").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method": "taskService.vote",
				"request": viewer.Sprintf("%+v", requestTaskServiceVote{
					TaskID: taskID,
					UserID: userID,
					Weight: weight,
				}),
				"response": viewer.Sprintf("%+v", responseTaskServiceVote{Task: task}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call vote")
			return
		}
		logger.Info().Func(logHandle).Msg("call vote")
	}(time.Now())
	return m.next.Vote(ctx, taskID, userID, weight)
}

func (m loggerTaskService) RemoveVote(ctx context.Context, taskID string, userID string) (task *types.Task, err error) {
	logger := log.Ctx(ctx).With().Str("service", "TaskService").Str("method", "removeVote").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method": "taskService.removeVote",
				"request": viewer.Sprintf("%+v", requestTaskServiceRemoveVote{
					TaskID: taskID,
					UserID: userID,
				}),
				"response": viewer.Sprintf("%+v", responseTaskServiceRemoveVote{Task: task}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call removeVote")
			return
		}
		logger.Info().Func(logHandle).Msg("call removeVote")
	}(time.Now())
	return m.next.RemoveVote(ctx, taskID, userID)
}

func (m loggerTaskService) Estimate(ctx context.Context, taskID string, userID string, value float64) (task *types.Task, err error) {
	logger := log.Ctx(ctx).With().Str("service", "TaskService").Str("method", "estimate").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method": "taskService.estimate",
				"request": viewer.Sprintf("%+v", requestTaskServiceEstimate{
					TaskID: taskID,
					UserID: userID,
					Value:  value,
				}),
				"response": viewer.Sprintf("%+v", responseTaskServiceEstimate{Task: task}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call estimate")
			return
		}
		logger.Info().Func(logHandle).Msg("call estimate")
	}(time.Now())
	return m.next.Estimate(ctx, taskID, userID, value)
}

func (m loggerTaskService) SetDependencies(ctx context.Context, taskID string, dependencyIDs []string) (task *types.Task, err error) {
	logger := log.Ctx(ctx).With().Str("service", "TaskService").Str("method", "setDependencies").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method": "taskService.setDependencies",
				"request": viewer.Sprintf("%+v", requestTaskServiceSetDependencies{
					DependencyIDs: dependencyIDs,
					TaskID:        taskID,
				}),
				"response": viewer.Sprintf("%+v", responseTaskServiceSetDependencies{Task: task}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call setDependencies")
			return
		}
		logger.Info().Func(logHandle).Msg("call setDependencies")
	}(time.Now())
	return m.next.SetDependencies(ctx, taskID, dependencyIDs)
}

func (m loggerTaskService) GetRanked(ctx context.Context, workspaceID string, limit int, offset int) (tasks []types.TaskWithRank, err error) {
	logger := log.Ctx(ctx).With().Str("service", "TaskService").Str("method", "getRanked").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method": "taskService.getRanked",
				"request": viewer.Sprintf("%+v", requestTaskServiceGetRanked{
					Limit:       limit,
					Offset:      offset,
					WorkspaceID: workspaceID,
				}),
				"response": viewer.Sprintf("%+v", responseTaskServiceGetRanked{Tasks: tasks}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call getRanked")
			return
		}
		logger.Info().Func(logHandle).Msg("call getRanked")
	}(time.Now())
	return m.next.GetRanked(ctx, workspaceID, limit, offset)
}
