// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import "github.com/sah4ez/ducalis-tg/pkg/types"

type requestTaskServiceCreate struct {
	Req types.CreateTaskRequest `json:"req,omitempty"`
}

type responseTaskServiceCreate struct {
	Task *types.Task `json:"task,omitempty"`
}

type requestTaskServiceGet struct {
	Id string `json:"id,omitempty"`
}

type responseTaskServiceGet struct {
	Task *types.Task `json:"task,omitempty"`
}

type requestTaskServiceUpdate struct {
	Id  string                  `json:"id,omitempty"`
	Req types.UpdateTaskRequest `json:"req,omitempty"`
}

type responseTaskServiceUpdate struct {
	Task *types.Task `json:"task,omitempty"`
}

type requestTaskServiceDelete struct {
	Id string `json:"id,omitempty"`
}

// Formal exchange type, please do not delete.
type responseTaskServiceDelete struct{}

type requestTaskServiceList struct {
	Req types.ListTasksRequest `json:"req,omitempty"`
}

type responseTaskServiceList struct {
	Tasks []types.Task `json:"tasks,omitempty"`
	Total int          `json:"total,omitempty"`
}

type requestTaskServiceSetScores struct {
	TaskID string             `json:"taskID,omitempty"`
	Scores map[string]float64 `json:"scores,omitempty"`
}

type responseTaskServiceSetScores struct {
	Task *types.Task `json:"task,omitempty"`
}

type requestTaskServiceVote struct {
	TaskID string  `json:"taskID,omitempty"`
	UserID string  `json:"userID,omitempty"`
	Weight float64 `json:"weight,omitempty"`
}

type responseTaskServiceVote struct {
	Task *types.Task `json:"task,omitempty"`
}

type requestTaskServiceRemoveVote struct {
	TaskID string `json:"taskID,omitempty"`
	UserID string `json:"userID,omitempty"`
}

type responseTaskServiceRemoveVote struct {
	Task *types.Task `json:"task,omitempty"`
}

type requestTaskServiceEstimate struct {
	TaskID string  `json:"taskID,omitempty"`
	UserID string  `json:"userID,omitempty"`
	Value  float64 `json:"value,omitempty"`
}

type responseTaskServiceEstimate struct {
	Task *types.Task `json:"task,omitempty"`
}

type requestTaskServiceSetDependencies struct {
	TaskID        string   `json:"taskID,omitempty"`
	DependencyIDs []string `json:"dependencyIDs,omitempty"`
}

type responseTaskServiceSetDependencies struct {
	Task *types.Task `json:"task,omitempty"`
}

type requestTaskServiceGetRanked struct {
	WorkspaceID string `json:"workspaceID,omitempty"`
	Limit       int    `json:"limit,omitempty"`
	Offset      int    `json:"offset,omitempty"`
}

type responseTaskServiceGetRanked struct {
	Tasks []types.TaskWithRank `json:"tasks,omitempty"`
}
