// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"context"

	"github.com/sah4ez/ducalis-tg/pkg/contract"
	"github.com/sah4ez/ducalis-tg/pkg/types"
)

type serverWorkspaceService struct {
	svc              contract.WorkspaceService
	create           WorkspaceServiceCreate
	get              WorkspaceServiceGet
	update           WorkspaceServiceUpdate
	delete           WorkspaceServiceDelete
	list             WorkspaceServiceList
	setScoringConfig WorkspaceServiceSetScoringConfig
	inviteMember     WorkspaceServiceInviteMember
	listMembers      WorkspaceServiceListMembers
	removeMember     WorkspaceServiceRemoveMember
}

type MiddlewareSetWorkspaceService interface {
	Wrap(m MiddlewareWorkspaceService)
	WrapCreate(m MiddlewareWorkspaceServiceCreate)
	WrapGet(m MiddlewareWorkspaceServiceGet)
	WrapUpdate(m MiddlewareWorkspaceServiceUpdate)
	WrapDelete(m MiddlewareWorkspaceServiceDelete)
	WrapList(m MiddlewareWorkspaceServiceList)
	WrapSetScoringConfig(m MiddlewareWorkspaceServiceSetScoringConfig)
	WrapInviteMember(m MiddlewareWorkspaceServiceInviteMember)
	WrapListMembers(m MiddlewareWorkspaceServiceListMembers)
	WrapRemoveMember(m MiddlewareWorkspaceServiceRemoveMember)

	WithTrace()
	WithMetrics()
	WithLog()
}

func newServerWorkspaceService(svc contract.WorkspaceService) *serverWorkspaceService {
	return &serverWorkspaceService{
		create:           svc.Create,
		delete:           svc.Delete,
		get:              svc.Get,
		inviteMember:     svc.InviteMember,
		list:             svc.List,
		listMembers:      svc.ListMembers,
		removeMember:     svc.RemoveMember,
		setScoringConfig: svc.SetScoringConfig,
		svc:              svc,
		update:           svc.Update,
	}
}

func (srv *serverWorkspaceService) Wrap(m MiddlewareWorkspaceService) {
	srv.svc = m(srv.svc)
	srv.create = srv.svc.Create
	srv.get = srv.svc.Get
	srv.update = srv.svc.Update
	srv.delete = srv.svc.Delete
	srv.list = srv.svc.List
	srv.setScoringConfig = srv.svc.SetScoringConfig
	srv.inviteMember = srv.svc.InviteMember
	srv.listMembers = srv.svc.ListMembers
	srv.removeMember = srv.svc.RemoveMember
}

func (srv *serverWorkspaceService) Create(ctx context.Context, req types.CreateWorkspaceRequest) (workspace *types.Workspace, err error) {
	return srv.create(ctx, req)
}

func (srv *serverWorkspaceService) Get(ctx context.Context, id string) (workspace *types.Workspace, err error) {
	return srv.get(ctx, id)
}

func (srv *serverWorkspaceService) Update(ctx context.Context, id string, req types.UpdateWorkspaceRequest) (workspace *types.Workspace, err error) {
	return srv.update(ctx, id, req)
}

func (srv *serverWorkspaceService) Delete(ctx context.Context, id string) (err error) {
	return srv.delete(ctx, id)
}

func (srv *serverWorkspaceService) List(ctx context.Context, userID string, limit int, offset int) (workspaces []types.Workspace, total int, err error) {
	return srv.list(ctx, userID, limit, offset)
}

func (srv *serverWorkspaceService) SetScoringConfig(ctx context.Context, workspaceID string, config types.ScoringConfig) (workspace *types.Workspace, err error) {
	return srv.setScoringConfig(ctx, workspaceID, config)
}

func (srv *serverWorkspaceService) InviteMember(ctx context.Context, workspaceID string, email string, role string) (member *types.Member, err error) {
	return srv.inviteMember(ctx, workspaceID, email, role)
}

func (srv *serverWorkspaceService) ListMembers(ctx context.Context, workspaceID string) (members []types.Member, err error) {
	return srv.listMembers(ctx, workspaceID)
}

func (srv *serverWorkspaceService) RemoveMember(ctx context.Context, workspaceID string, memberID string) (err error) {
	return srv.removeMember(ctx, workspaceID, memberID)
}

func (srv *serverWorkspaceService) WrapCreate(m MiddlewareWorkspaceServiceCreate) {
	srv.create = m(srv.create)
}

func (srv *serverWorkspaceService) WrapGet(m MiddlewareWorkspaceServiceGet) {
	srv.get = m(srv.get)
}

func (srv *serverWorkspaceService) WrapUpdate(m MiddlewareWorkspaceServiceUpdate) {
	srv.update = m(srv.update)
}

func (srv *serverWorkspaceService) WrapDelete(m MiddlewareWorkspaceServiceDelete) {
	srv.delete = m(srv.delete)
}

func (srv *serverWorkspaceService) WrapList(m MiddlewareWorkspaceServiceList) {
	srv.list = m(srv.list)
}

func (srv *serverWorkspaceService) WrapSetScoringConfig(m MiddlewareWorkspaceServiceSetScoringConfig) {
	srv.setScoringConfig = m(srv.setScoringConfig)
}

func (srv *serverWorkspaceService) WrapInviteMember(m MiddlewareWorkspaceServiceInviteMember) {
	srv.inviteMember = m(srv.inviteMember)
}

func (srv *serverWorkspaceService) WrapListMembers(m MiddlewareWorkspaceServiceListMembers) {
	srv.listMembers = m(srv.listMembers)
}

func (srv *serverWorkspaceService) WrapRemoveMember(m MiddlewareWorkspaceServiceRemoveMember) {
	srv.removeMember = m(srv.removeMember)
}

func (srv *serverWorkspaceService) WithTrace() {
	srv.Wrap(traceMiddlewareWorkspaceService)
}

func (srv *serverWorkspaceService) WithMetrics() {
	srv.Wrap(metricsMiddlewareWorkspaceService)
}

func (srv *serverWorkspaceService) WithLog() {
	srv.Wrap(loggerMiddlewareWorkspaceService())
}
