// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"context"
	"time"

	"github.com/rs/zerolog"
	"github.com/rs/zerolog/log"
	"github.com/sah4ez/ducalis-tg/internal/transport/viewer"
	"github.com/sah4ez/ducalis-tg/pkg/contract"
	"github.com/sah4ez/ducalis-tg/pkg/types"
)

type loggerWorkspaceService struct {
	next contract.WorkspaceService
}

func loggerMiddlewareWorkspaceService() MiddlewareWorkspaceService {
	return func(next contract.WorkspaceService) contract.WorkspaceService {
		return &loggerWorkspaceService{next: next}
	}
}

func (m loggerWorkspaceService) Create(ctx context.Context, req types.CreateWorkspaceRequest) (workspace *types.Workspace, err error) {
	logger := log.Ctx(ctx).With().Str("service", "WorkspaceService").Str("method", "create").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method":   "workspaceService.create",
				"request":  viewer.Sprintf("%+v", requestWorkspaceServiceCreate{Req: req}),
				"response": viewer.Sprintf("%+v", responseWorkspaceServiceCreate{Workspace: workspace}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call create")
			return
		}
		logger.Info().Func(logHandle).Msg("call create")
	}(time.Now())
	return m.next.Create(ctx, req)
}

func (m loggerWorkspaceService) Get(ctx context.Context, id string) (workspace *types.Workspace, err error) {
	logger := log.Ctx(ctx).With().Str("service", "WorkspaceService").Str("method", "get").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method":   "workspaceService.get",
				"request":  viewer.Sprintf("%+v", requestWorkspaceServiceGet{Id: id}),
				"response": viewer.Sprintf("%+v", responseWorkspaceServiceGet{Workspace: workspace}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call get")
			return
		}
		logger.Info().Func(logHandle).Msg("call get")
	}(time.Now())
	return m.next.Get(ctx, id)
}

func (m loggerWorkspaceService) Update(ctx context.Context, id string, req types.UpdateWorkspaceRequest) (workspace *types.Workspace, err error) {
	logger := log.Ctx(ctx).With().Str("service", "WorkspaceService").Str("method", "update").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method": "workspaceService.update",
				"request": viewer.Sprintf("%+v", requestWorkspaceServiceUpdate{
					Id:  id,
					Req: req,
				}),
				"response": viewer.Sprintf("%+v", responseWorkspaceServiceUpdate{Workspace: workspace}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call update")
			return
		}
		logger.Info().Func(logHandle).Msg("call update")
	}(time.Now())
	return m.next.Update(ctx, id, req)
}

func (m loggerWorkspaceService) Delete(ctx context.Context, id string) (err error) {
	logger := log.Ctx(ctx).With().Str("service", "WorkspaceService").Str("method", "delete").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method":   "workspaceService.delete",
				"request":  viewer.Sprintf("%+v", requestWorkspaceServiceDelete{Id: id}),
				"response": viewer.Sprintf("%+v", responseWorkspaceServiceDelete{}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call delete")
			return
		}
		logger.Info().Func(logHandle).Msg("call delete")
	}(time.Now())
	return m.next.Delete(ctx, id)
}

func (m loggerWorkspaceService) List(ctx context.Context, userID string, limit int, offset int) (workspaces []types.Workspace, total int, err error) {
	logger := log.Ctx(ctx).With().Str("service", "WorkspaceService").Str("method", "list").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method": "workspaceService.list",
				"request": viewer.Sprintf("%+v", requestWorkspaceServiceList{
					Limit:  limit,
					Offset: offset,
					UserID: userID,
				}),
				"response": viewer.Sprintf("%+v", responseWorkspaceServiceList{
					Total:      total,
					Workspaces: workspaces,
				}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call list")
			return
		}
		logger.Info().Func(logHandle).Msg("call list")
	}(time.Now())
	return m.next.List(ctx, userID, limit, offset)
}

func (m loggerWorkspaceService) SetScoringConfig(ctx context.Context, workspaceID string, config types.ScoringConfig) (workspace *types.Workspace, err error) {
	logger := log.Ctx(ctx).With().Str("service", "WorkspaceService").Str("method", "setScoringConfig").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method": "workspaceService.setScoringConfig",
				"request": viewer.Sprintf("%+v", requestWorkspaceServiceSetScoringConfig{
					Config:      config,
					WorkspaceID: workspaceID,
				}),
				"response": viewer.Sprintf("%+v", responseWorkspaceServiceSetScoringConfig{Workspace: workspace}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call setScoringConfig")
			return
		}
		logger.Info().Func(logHandle).Msg("call setScoringConfig")
	}(time.Now())
	return m.next.SetScoringConfig(ctx, workspaceID, config)
}

func (m loggerWorkspaceService) InviteMember(ctx context.Context, workspaceID string, email string, role string) (member *types.Member, err error) {
	logger := log.Ctx(ctx).With().Str("service", "WorkspaceService").Str("method", "inviteMember").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method": "workspaceService.inviteMember",
				"request": viewer.Sprintf("%+v", requestWorkspaceServiceInviteMember{
					Email:       email,
					Role:        role,
					WorkspaceID: workspaceID,
				}),
				"response": viewer.Sprintf("%+v", responseWorkspaceServiceInviteMember{Member: member}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call inviteMember")
			return
		}
		logger.Info().Func(logHandle).Msg("call inviteMember")
	}(time.Now())
	return m.next.InviteMember(ctx, workspaceID, email, role)
}

func (m loggerWorkspaceService) ListMembers(ctx context.Context, workspaceID string) (members []types.Member, err error) {
	logger := log.Ctx(ctx).With().Str("service", "WorkspaceService").Str("method", "listMembers").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method":   "workspaceService.listMembers",
				"request":  viewer.Sprintf("%+v", requestWorkspaceServiceListMembers{WorkspaceID: workspaceID}),
				"response": viewer.Sprintf("%+v", responseWorkspaceServiceListMembers{Members: members}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call listMembers")
			return
		}
		logger.Info().Func(logHandle).Msg("call listMembers")
	}(time.Now())
	return m.next.ListMembers(ctx, workspaceID)
}

func (m loggerWorkspaceService) RemoveMember(ctx context.Context, workspaceID string, memberID string) (err error) {
	logger := log.Ctx(ctx).With().Str("service", "WorkspaceService").Str("method", "removeMember").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method": "workspaceService.removeMember",
				"request": viewer.Sprintf("%+v", requestWorkspaceServiceRemoveMember{
					MemberID:    memberID,
					WorkspaceID: workspaceID,
				}),
				"response": viewer.Sprintf("%+v", responseWorkspaceServiceRemoveMember{}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call removeMember")
			return
		}
		logger.Info().Func(logHandle).Msg("call removeMember")
	}(time.Now())
	return m.next.RemoveMember(ctx, workspaceID, memberID)
}
