// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"context"
	"fmt"

	"github.com/sah4ez/ducalis-tg/pkg/contract"
	"github.com/sah4ez/ducalis-tg/pkg/types"
	otel "go.opentelemetry.io/otel"
	trace "go.opentelemetry.io/otel/trace"
)

type traceWorkspaceService struct {
	next contract.WorkspaceService
}

func traceMiddlewareWorkspaceService(next contract.WorkspaceService) contract.WorkspaceService {
	return &traceWorkspaceService{next: next}
}

func (svc traceWorkspaceService) Create(ctx context.Context, req types.CreateWorkspaceRequest) (workspace *types.Workspace, err error) {

	var span trace.Span
	ctx, span = otel.Tracer(fmt.Sprintf("tg:%s", VersionTg)).Start(ctx, "workspaceService.create")
	defer func() {
		span.RecordError(err)
		span.End()
	}()
	return svc.next.Create(ctx, req)
}

func (svc traceWorkspaceService) Get(ctx context.Context, id string) (workspace *types.Workspace, err error) {

	var span trace.Span
	ctx, span = otel.Tracer(fmt.Sprintf("tg:%s", VersionTg)).Start(ctx, "workspaceService.get")
	defer func() {
		span.RecordError(err)
		span.End()
	}()
	return svc.next.Get(ctx, id)
}

func (svc traceWorkspaceService) Update(ctx context.Context, id string, req types.UpdateWorkspaceRequest) (workspace *types.Workspace, err error) {

	var span trace.Span
	ctx, span = otel.Tracer(fmt.Sprintf("tg:%s", VersionTg)).Start(ctx, "workspaceService.update")
	defer func() {
		span.RecordError(err)
		span.End()
	}()
	return svc.next.Update(ctx, id, req)
}

func (svc traceWorkspaceService) Delete(ctx context.Context, id string) (err error) {

	var span trace.Span
	ctx, span = otel.Tracer(fmt.Sprintf("tg:%s", VersionTg)).Start(ctx, "workspaceService.delete")
	defer func() {
		span.RecordError(err)
		span.End()
	}()
	return svc.next.Delete(ctx, id)
}

func (svc traceWorkspaceService) List(ctx context.Context, userID string, limit int, offset int) (workspaces []types.Workspace, total int, err error) {

	var span trace.Span
	ctx, span = otel.Tracer(fmt.Sprintf("tg:%s", VersionTg)).Start(ctx, "workspaceService.list")
	defer func() {
		span.RecordError(err)
		span.End()
	}()
	return svc.next.List(ctx, userID, limit, offset)
}

func (svc traceWorkspaceService) SetScoringConfig(ctx context.Context, workspaceID string, config types.ScoringConfig) (workspace *types.Workspace, err error) {

	var span trace.Span
	ctx, span = otel.Tracer(fmt.Sprintf("tg:%s", VersionTg)).Start(ctx, "workspaceService.setScoringConfig")
	defer func() {
		span.RecordError(err)
		span.End()
	}()
	return svc.next.SetScoringConfig(ctx, workspaceID, config)
}

func (svc traceWorkspaceService) InviteMember(ctx context.Context, workspaceID string, email string, role string) (member *types.Member, err error) {

	var span trace.Span
	ctx, span = otel.Tracer(fmt.Sprintf("tg:%s", VersionTg)).Start(ctx, "workspaceService.inviteMember")
	defer func() {
		span.RecordError(err)
		span.End()
	}()
	return svc.next.InviteMember(ctx, workspaceID, email, role)
}

func (svc traceWorkspaceService) ListMembers(ctx context.Context, workspaceID string) (members []types.Member, err error) {

	var span trace.Span
	ctx, span = otel.Tracer(fmt.Sprintf("tg:%s", VersionTg)).Start(ctx, "workspaceService.listMembers")
	defer func() {
		span.RecordError(err)
		span.End()
	}()
	return svc.next.ListMembers(ctx, workspaceID)
}

func (svc traceWorkspaceService) RemoveMember(ctx context.Context, workspaceID string, memberID string) (err error) {

	var span trace.Span
	ctx, span = otel.Tracer(fmt.Sprintf("tg:%s", VersionTg)).Start(ctx, "workspaceService.removeMember")
	defer func() {
		span.RecordError(err)
		span.End()
	}()
	return svc.next.RemoveMember(ctx, workspaceID, memberID)
}
