// Code generated by 'T'ool 'G'ateway. DO NOT EDIT.
package transport

import "github.com/sah4ez/ducalis-tg/pkg/types"

type requestWorkspaceServiceCreate struct {
	Req types.CreateWorkspaceRequest `json:"req"`
}

type responseWorkspaceServiceCreate struct {
	Workspace *types.Workspace `json:"workspace"`
}

type requestWorkspaceServiceGet struct {
	Id string `json:"-"`
}

type responseWorkspaceServiceGet struct {
	Workspace *types.Workspace `json:"workspace"`
}

type requestWorkspaceServiceUpdate struct {
	Id  string                       `json:"-"`
	Req types.UpdateWorkspaceRequest `json:"req"`
}

type responseWorkspaceServiceUpdate struct {
	Workspace *types.Workspace `json:"workspace"`
}

type requestWorkspaceServiceDelete struct {
	Id string `json:"-"`
}

type responseWorkspaceServiceDelete struct{}

type requestWorkspaceServiceList struct {
	UserID string `json:"-"`
	Limit  int    `json:"-"`
	Offset int    `json:"-"`
}

type responseWorkspaceServiceList struct {
	Workspaces []types.Workspace `json:"workspaces"`
	Total      int               `json:"total"`
}

type requestWorkspaceServiceSetScoringConfig struct {
	Id     string              `json:"-"`
	Config types.ScoringConfig `json:"config"`
}

type responseWorkspaceServiceSetScoringConfig struct {
	*types.Workspace `json:",inline"`
}

type requestWorkspaceServiceInviteMember struct {
	Id    string `json:"-"`
	Email string `json:"email"`
	Role  string `json:"role"`
}

type responseWorkspaceServiceInviteMember struct {
	Member *types.Member `json:"member"`
}

type requestWorkspaceServiceListMembers struct {
	Id string `json:"-"`
}

type responseWorkspaceServiceListMembers struct {
	Members []types.Member `json:"members"`
}

type requestWorkspaceServiceRemoveMember struct {
	Id       string `json:"-"`
	MemberID string `json:"-"`
}

type responseWorkspaceServiceRemoveMember struct{}
