// Code generated by 'T'ool 'G'ateway. DO NOT EDIT.
package transport

import (
	"context"
	"encoding/json"
	"strconv"

	"github.com/gofiber/fiber/v2"
	"github.com/sah4ez/ducalis-tg/internal/transport/srvctx"
)

func (http *httpWorkspaceService) create(ctx context.Context, request requestWorkspaceServiceCreate) (response responseWorkspaceServiceCreate, err error) {

	ctx = withMethodLogger(ctx, "workspaceService", "create")

	if response.Workspace, err = http.svc.Create(ctx, request.Req); err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpWorkspaceService) serveCreate(ftx *fiber.Ctx) (err error) {

	clientID := srvctx.GetClientID(ftx.UserContext())
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		defer func() {
			if err == nil {
				server.metrics.EntryRequestsTotal.WithLabelValues("rest", "ok", clientID).Inc()
			}
		}()
	}
	var request requestWorkspaceServiceCreate
	ftx.Response().SetStatusCode(201)
	bodyStream := ensureBodyReader(ftx.Context().RequestBodyStream())
	if err = json.NewDecoder(bodyStream).Decode(&request); err != nil {
		if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
			server.metrics.ErrorResponsesTotal.WithLabelValues("rest", "400", clientID).Inc()
		}
		ftx.Response().SetStatusCode(fiber.StatusBadRequest)
		_, err = ftx.WriteString("request body could not be decoded: " + err.Error())
		return
	}

	var response responseWorkspaceServiceCreate
	if response, err = http.create(ftx.UserContext(), request); err == nil {
		var iResponse any = response
		if redirect, ok := iResponse.(withRedirect); ok {
			return ftx.Redirect(redirect.RedirectTo())
		}

		return sendResponse(ftx, response)
	}
	var statusCode int
	if errCoder, ok := err.(withErrorCode); ok {
		statusCode = errCoder.Code()
		ftx.Status(statusCode)
	} else {
		statusCode = fiber.StatusInternalServerError
		ftx.Status(statusCode)
	}
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		server.metrics.ErrorResponsesTotal.WithLabelValues("rest", strconv.Itoa(statusCode), clientID).Inc()
	}
	return sendResponse(ftx, err)
}
func (http *httpWorkspaceService) get(ctx context.Context, request requestWorkspaceServiceGet) (response responseWorkspaceServiceGet, err error) {

	ctx = withMethodLogger(ctx, "workspaceService", "get")

	if response.Workspace, err = http.svc.Get(ctx, request.Id); err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpWorkspaceService) serveGet(ftx *fiber.Ctx) (err error) {

	clientID := srvctx.GetClientID(ftx.UserContext())
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		defer func() {
			if err == nil {
				server.metrics.EntryRequestsTotal.WithLabelValues("rest", "ok", clientID).Inc()
			}
		}()
	}
	var request requestWorkspaceServiceGet

	if _id_ := ftx.Params("id"); _id_ != "" {
		request.Id = _id_
	}

	var response responseWorkspaceServiceGet
	if response, err = http.get(ftx.UserContext(), request); err == nil {
		var iResponse any = response
		if redirect, ok := iResponse.(withRedirect); ok {
			return ftx.Redirect(redirect.RedirectTo())
		}

		return sendResponse(ftx, response)
	}
	var statusCode int
	if errCoder, ok := err.(withErrorCode); ok {
		statusCode = errCoder.Code()
		ftx.Status(statusCode)
	} else {
		statusCode = fiber.StatusInternalServerError
		ftx.Status(statusCode)
	}
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		server.metrics.ErrorResponsesTotal.WithLabelValues("rest", strconv.Itoa(statusCode), clientID).Inc()
	}
	return sendResponse(ftx, err)
}
func (http *httpWorkspaceService) update(ctx context.Context, request requestWorkspaceServiceUpdate) (response responseWorkspaceServiceUpdate, err error) {

	ctx = withMethodLogger(ctx, "workspaceService", "update")

	if response.Workspace, err = http.svc.Update(ctx, request.Id, request.Req); err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpWorkspaceService) serveUpdate(ftx *fiber.Ctx) (err error) {

	clientID := srvctx.GetClientID(ftx.UserContext())
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		defer func() {
			if err == nil {
				server.metrics.EntryRequestsTotal.WithLabelValues("rest", "ok", clientID).Inc()
			}
		}()
	}
	var request requestWorkspaceServiceUpdate
	bodyStream := ensureBodyReader(ftx.Context().RequestBodyStream())
	if err = json.NewDecoder(bodyStream).Decode(&request); err != nil {
		if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
			server.metrics.ErrorResponsesTotal.WithLabelValues("rest", "400", clientID).Inc()
		}
		ftx.Response().SetStatusCode(fiber.StatusBadRequest)
		_, err = ftx.WriteString("request body could not be decoded: " + err.Error())
		return
	}

	if _id_ := ftx.Params("id"); _id_ != "" {
		request.Id = _id_
	}

	var response responseWorkspaceServiceUpdate
	if response, err = http.update(ftx.UserContext(), request); err == nil {
		var iResponse any = response
		if redirect, ok := iResponse.(withRedirect); ok {
			return ftx.Redirect(redirect.RedirectTo())
		}

		return sendResponse(ftx, response)
	}
	var statusCode int
	if errCoder, ok := err.(withErrorCode); ok {
		statusCode = errCoder.Code()
		ftx.Status(statusCode)
	} else {
		statusCode = fiber.StatusInternalServerError
		ftx.Status(statusCode)
	}
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		server.metrics.ErrorResponsesTotal.WithLabelValues("rest", strconv.Itoa(statusCode), clientID).Inc()
	}
	return sendResponse(ftx, err)
}
func (http *httpWorkspaceService) delete(ctx context.Context, request requestWorkspaceServiceDelete) (response responseWorkspaceServiceDelete, err error) {

	ctx = withMethodLogger(ctx, "workspaceService", "delete")

	if err = http.svc.Delete(ctx, request.Id); err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpWorkspaceService) serveDelete(ftx *fiber.Ctx) (err error) {

	clientID := srvctx.GetClientID(ftx.UserContext())
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		defer func() {
			if err == nil {
				server.metrics.EntryRequestsTotal.WithLabelValues("rest", "ok", clientID).Inc()
			}
		}()
	}
	var request requestWorkspaceServiceDelete
	ftx.Response().SetStatusCode(204)

	if _id_ := ftx.Params("id"); _id_ != "" {
		request.Id = _id_
	}

	var response responseWorkspaceServiceDelete
	if response, err = http.delete(ftx.UserContext(), request); err == nil {
		var iResponse any = response
		if redirect, ok := iResponse.(withRedirect); ok {
			return ftx.Redirect(redirect.RedirectTo())
		}

		return sendResponse(ftx, response)
	}
	var statusCode int
	if errCoder, ok := err.(withErrorCode); ok {
		statusCode = errCoder.Code()
		ftx.Status(statusCode)
	} else {
		statusCode = fiber.StatusInternalServerError
		ftx.Status(statusCode)
	}
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		server.metrics.ErrorResponsesTotal.WithLabelValues("rest", strconv.Itoa(statusCode), clientID).Inc()
	}
	return sendResponse(ftx, err)
}
func (http *httpWorkspaceService) list(ctx context.Context, request requestWorkspaceServiceList) (response responseWorkspaceServiceList, err error) {

	ctx = withMethodLogger(ctx, "workspaceService", "list")

	if response.Workspaces, response.Total, err = http.svc.List(ctx, request.UserID, request.Limit, request.Offset); err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpWorkspaceService) serveList(ftx *fiber.Ctx) (err error) {

	clientID := srvctx.GetClientID(ftx.UserContext())
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		defer func() {
			if err == nil {
				server.metrics.EntryRequestsTotal.WithLabelValues("rest", "ok", clientID).Inc()
			}
		}()
	}
	var request requestWorkspaceServiceList

	if _userID_b := ftx.Request().URI().QueryArgs().Peek("userID"); _userID_b != nil {
		_userID_ := string(_userID_b)
		request.UserID = _userID_
	}
	if _limit_b := ftx.Request().URI().QueryArgs().Peek("limit"); _limit_b != nil {
		_limit_ := string(_limit_b)
		var limit int
		if limit, err = strconv.Atoi(_limit_); err != nil {
			ftx.Status(fiber.StatusBadRequest)
			return sendResponse(ftx, "url arguments could not be decoded: "+err.Error())
		}
		request.Limit = limit
	}
	if _offset_b := ftx.Request().URI().QueryArgs().Peek("offset"); _offset_b != nil {
		_offset_ := string(_offset_b)
		var offset int
		if offset, err = strconv.Atoi(_offset_); err != nil {
			ftx.Status(fiber.StatusBadRequest)
			return sendResponse(ftx, "url arguments could not be decoded: "+err.Error())
		}
		request.Offset = offset
	}

	var response responseWorkspaceServiceList
	if response, err = http.list(ftx.UserContext(), request); err == nil {
		var iResponse any = response
		if redirect, ok := iResponse.(withRedirect); ok {
			return ftx.Redirect(redirect.RedirectTo())
		}

		return sendResponse(ftx, response)
	}
	var statusCode int
	if errCoder, ok := err.(withErrorCode); ok {
		statusCode = errCoder.Code()
		ftx.Status(statusCode)
	} else {
		statusCode = fiber.StatusInternalServerError
		ftx.Status(statusCode)
	}
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		server.metrics.ErrorResponsesTotal.WithLabelValues("rest", strconv.Itoa(statusCode), clientID).Inc()
	}
	return sendResponse(ftx, err)
}
func (http *httpWorkspaceService) setScoringConfig(ctx context.Context, request requestWorkspaceServiceSetScoringConfig) (response responseWorkspaceServiceSetScoringConfig, err error) {

	ctx = withMethodLogger(ctx, "workspaceService", "setScoringConfig")

	if response.Workspace, err = http.svc.SetScoringConfig(ctx, request.Id, request.Config); err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpWorkspaceService) serveSetScoringConfig(ftx *fiber.Ctx) (err error) {

	clientID := srvctx.GetClientID(ftx.UserContext())
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		defer func() {
			if err == nil {
				server.metrics.EntryRequestsTotal.WithLabelValues("rest", "ok", clientID).Inc()
			}
		}()
	}
	var request requestWorkspaceServiceSetScoringConfig
	bodyStream := ensureBodyReader(ftx.Context().RequestBodyStream())
	if err = json.NewDecoder(bodyStream).Decode(&request); err != nil {
		if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
			server.metrics.ErrorResponsesTotal.WithLabelValues("rest", "400", clientID).Inc()
		}
		ftx.Response().SetStatusCode(fiber.StatusBadRequest)
		_, err = ftx.WriteString("request body could not be decoded: " + err.Error())
		return
	}

	if _id_ := ftx.Params("id"); _id_ != "" {
		request.Id = _id_
	}

	var response responseWorkspaceServiceSetScoringConfig
	if response, err = http.setScoringConfig(ftx.UserContext(), request); err == nil {
		var iResponse any = response
		if redirect, ok := iResponse.(withRedirect); ok {
			return ftx.Redirect(redirect.RedirectTo())
		}

		return sendResponse(ftx, response.Workspace)
	}
	var statusCode int
	if errCoder, ok := err.(withErrorCode); ok {
		statusCode = errCoder.Code()
		ftx.Status(statusCode)
	} else {
		statusCode = fiber.StatusInternalServerError
		ftx.Status(statusCode)
	}
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		server.metrics.ErrorResponsesTotal.WithLabelValues("rest", strconv.Itoa(statusCode), clientID).Inc()
	}
	return sendResponse(ftx, err)
}
func (http *httpWorkspaceService) inviteMember(ctx context.Context, request requestWorkspaceServiceInviteMember) (response responseWorkspaceServiceInviteMember, err error) {

	ctx = withMethodLogger(ctx, "workspaceService", "inviteMember")

	if response.Member, err = http.svc.InviteMember(ctx, request.Id, request.Email, request.Role); err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpWorkspaceService) serveInviteMember(ftx *fiber.Ctx) (err error) {

	clientID := srvctx.GetClientID(ftx.UserContext())
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		defer func() {
			if err == nil {
				server.metrics.EntryRequestsTotal.WithLabelValues("rest", "ok", clientID).Inc()
			}
		}()
	}
	var request requestWorkspaceServiceInviteMember
	ftx.Response().SetStatusCode(201)
	bodyStream := ensureBodyReader(ftx.Context().RequestBodyStream())
	if err = json.NewDecoder(bodyStream).Decode(&request); err != nil {
		if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
			server.metrics.ErrorResponsesTotal.WithLabelValues("rest", "400", clientID).Inc()
		}
		ftx.Response().SetStatusCode(fiber.StatusBadRequest)
		_, err = ftx.WriteString("request body could not be decoded: " + err.Error())
		return
	}

	if _id_ := ftx.Params("id"); _id_ != "" {
		request.Id = _id_
	}

	var response responseWorkspaceServiceInviteMember
	if response, err = http.inviteMember(ftx.UserContext(), request); err == nil {
		var iResponse any = response
		if redirect, ok := iResponse.(withRedirect); ok {
			return ftx.Redirect(redirect.RedirectTo())
		}

		return sendResponse(ftx, response)
	}
	var statusCode int
	if errCoder, ok := err.(withErrorCode); ok {
		statusCode = errCoder.Code()
		ftx.Status(statusCode)
	} else {
		statusCode = fiber.StatusInternalServerError
		ftx.Status(statusCode)
	}
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		server.metrics.ErrorResponsesTotal.WithLabelValues("rest", strconv.Itoa(statusCode), clientID).Inc()
	}
	return sendResponse(ftx, err)
}
func (http *httpWorkspaceService) listMembers(ctx context.Context, request requestWorkspaceServiceListMembers) (response responseWorkspaceServiceListMembers, err error) {

	ctx = withMethodLogger(ctx, "workspaceService", "listMembers")

	if response.Members, err = http.svc.ListMembers(ctx, request.Id); err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpWorkspaceService) serveListMembers(ftx *fiber.Ctx) (err error) {

	clientID := srvctx.GetClientID(ftx.UserContext())
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		defer func() {
			if err == nil {
				server.metrics.EntryRequestsTotal.WithLabelValues("rest", "ok", clientID).Inc()
			}
		}()
	}
	var request requestWorkspaceServiceListMembers

	if _id_ := ftx.Params("id"); _id_ != "" {
		request.Id = _id_
	}

	var response responseWorkspaceServiceListMembers
	if response, err = http.listMembers(ftx.UserContext(), request); err == nil {
		var iResponse any = response
		if redirect, ok := iResponse.(withRedirect); ok {
			return ftx.Redirect(redirect.RedirectTo())
		}

		return sendResponse(ftx, response)
	}
	var statusCode int
	if errCoder, ok := err.(withErrorCode); ok {
		statusCode = errCoder.Code()
		ftx.Status(statusCode)
	} else {
		statusCode = fiber.StatusInternalServerError
		ftx.Status(statusCode)
	}
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		server.metrics.ErrorResponsesTotal.WithLabelValues("rest", strconv.Itoa(statusCode), clientID).Inc()
	}
	return sendResponse(ftx, err)
}
func (http *httpWorkspaceService) removeMember(ctx context.Context, request requestWorkspaceServiceRemoveMember) (response responseWorkspaceServiceRemoveMember, err error) {

	ctx = withMethodLogger(ctx, "workspaceService", "removeMember")

	if err = http.svc.RemoveMember(ctx, request.Id, request.MemberID); err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpWorkspaceService) serveRemoveMember(ftx *fiber.Ctx) (err error) {

	clientID := srvctx.GetClientID(ftx.UserContext())
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		defer func() {
			if err == nil {
				server.metrics.EntryRequestsTotal.WithLabelValues("rest", "ok", clientID).Inc()
			}
		}()
	}
	var request requestWorkspaceServiceRemoveMember

	if _id_ := ftx.Params("id"); _id_ != "" {
		request.Id = _id_
	}
	if _memberID_ := ftx.Params("memberID"); _memberID_ != "" {
		request.MemberID = _memberID_
	}

	var response responseWorkspaceServiceRemoveMember
	if response, err = http.removeMember(ftx.UserContext(), request); err == nil {
		var iResponse any = response
		if redirect, ok := iResponse.(withRedirect); ok {
			return ftx.Redirect(redirect.RedirectTo())
		}

		return sendResponse(ftx, response)
	}
	var statusCode int
	if errCoder, ok := err.(withErrorCode); ok {
		statusCode = errCoder.Code()
		ftx.Status(statusCode)
	} else {
		statusCode = fiber.StatusInternalServerError
		ftx.Status(statusCode)
	}
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		server.metrics.ErrorResponsesTotal.WithLabelValues("rest", strconv.Itoa(statusCode), clientID).Inc()
	}
	return sendResponse(ftx, err)
}
