// Code generated by 'T'ool 'G'ateway. DO NOT EDIT.
package transport

import (
	"github.com/gofiber/fiber/v2"
	"github.com/sah4ez/ducalis-tg/pkg/contract"
)

type httpWorkspaceService struct {
	errorHandler ErrorHandler
	svc          *serverWorkspaceService
	base         contract.WorkspaceService
}

func newWorkspaceService(svcWorkspaceService contract.WorkspaceService) (srv *httpWorkspaceService) {

	srv = &httpWorkspaceService{
		base: svcWorkspaceService,
		svc:  newServerWorkspaceService(svcWorkspaceService),
	}
	return
}

func (http *httpWorkspaceService) Service() *serverWorkspaceService {
	return http.svc
}

func (http *httpWorkspaceService) WithMetrics(metrics *Metrics) *httpWorkspaceService {
	http.svc.WithMetrics(metrics)
	return http
}

func (http *httpWorkspaceService) WithErrorHandler(handler ErrorHandler) *httpWorkspaceService {
	http.errorHandler = handler
	return http
}

func (http *httpWorkspaceService) WithRedirect() *httpWorkspaceService {
	return http
}

func (http *httpWorkspaceService) SetRoutes(route *fiber.App) {
	route.Post("/api/v1/workspaces", http.serveCreate)
	route.Get("/api/v1/workspaces/:id", http.serveGet)
	route.Patch("/api/v1/workspaces/:id", http.serveUpdate)
	route.Delete("/api/v1/workspaces/:id", http.serveDelete)
	route.Get("/api/v1/workspaces", http.serveList)
	route.Put("/api/v1/workspaces/:id/scoring", http.serveSetScoringConfig)
	route.Post("/api/v1/workspaces/:id/members", http.serveInviteMember)
	route.Get("/api/v1/workspaces/:id/members", http.serveListMembers)
	route.Delete("/api/v1/workspaces/:id/members/:memberID", http.serveRemoveMember)
}
