// Code generated by 'T'ool 'G'ateway. DO NOT EDIT.
package transport

import (
	"context"

	"github.com/sah4ez/ducalis-tg/pkg/contract"
	"github.com/sah4ez/ducalis-tg/pkg/types"
)

type WorkspaceServiceCreate func(ctx context.Context, req types.CreateWorkspaceRequest) (workspace *types.Workspace, err error)
type WorkspaceServiceGet func(ctx context.Context, id string) (workspace *types.Workspace, err error)
type WorkspaceServiceUpdate func(ctx context.Context, id string, req types.UpdateWorkspaceRequest) (workspace *types.Workspace, err error)
type WorkspaceServiceDelete func(ctx context.Context, id string) (err error)
type WorkspaceServiceList func(ctx context.Context, userID string, limit int, offset int) (workspaces []types.Workspace, total int, err error)
type WorkspaceServiceSetScoringConfig func(ctx context.Context, id string, config types.ScoringConfig) (workspace *types.Workspace, err error)
type WorkspaceServiceInviteMember func(ctx context.Context, id string, email string, role string) (member *types.Member, err error)
type WorkspaceServiceListMembers func(ctx context.Context, id string) (members []types.Member, err error)
type WorkspaceServiceRemoveMember func(ctx context.Context, id string, memberID string) (err error)

type MiddlewareWorkspaceService func(next contract.WorkspaceService) contract.WorkspaceService

type MiddlewareWorkspaceServiceCreate func(next WorkspaceServiceCreate) WorkspaceServiceCreate
type MiddlewareWorkspaceServiceGet func(next WorkspaceServiceGet) WorkspaceServiceGet
type MiddlewareWorkspaceServiceUpdate func(next WorkspaceServiceUpdate) WorkspaceServiceUpdate
type MiddlewareWorkspaceServiceDelete func(next WorkspaceServiceDelete) WorkspaceServiceDelete
type MiddlewareWorkspaceServiceList func(next WorkspaceServiceList) WorkspaceServiceList
type MiddlewareWorkspaceServiceSetScoringConfig func(next WorkspaceServiceSetScoringConfig) WorkspaceServiceSetScoringConfig
type MiddlewareWorkspaceServiceInviteMember func(next WorkspaceServiceInviteMember) WorkspaceServiceInviteMember
type MiddlewareWorkspaceServiceListMembers func(next WorkspaceServiceListMembers) WorkspaceServiceListMembers
type MiddlewareWorkspaceServiceRemoveMember func(next WorkspaceServiceRemoveMember) WorkspaceServiceRemoveMember
