// Code generated by 'T'ool 'G'ateway. DO NOT EDIT.
package transport

import (
	"context"
	"strconv"
	"time"

	"github.com/gofiber/fiber/v2"
	"github.com/sah4ez/ducalis-tg/internal/transport/srvctx"
	"github.com/sah4ez/ducalis-tg/pkg/contract"
	"github.com/sah4ez/ducalis-tg/pkg/types"
)

const (
	metricServiceWorkspaceService = "workspaceService"
)
const metricMethodWorkspaceServiceCreate = "create"
const metricMethodWorkspaceServiceGet = "get"
const metricMethodWorkspaceServiceUpdate = "update"
const metricMethodWorkspaceServiceDelete = "delete"
const metricMethodWorkspaceServiceList = "list"
const metricMethodWorkspaceServiceSetScoringConfig = "setScoringConfig"
const metricMethodWorkspaceServiceInviteMember = "inviteMember"
const metricMethodWorkspaceServiceListMembers = "listMembers"
const metricMethodWorkspaceServiceRemoveMember = "removeMember"

type metricsWorkspaceService struct {
	next    contract.WorkspaceService
	metrics *Metrics
}

func metricsMiddlewareWorkspaceService(next contract.WorkspaceService, metrics *Metrics) contract.WorkspaceService {
	return &metricsWorkspaceService{
		metrics: metrics,
		next:    next,
	}
}

func (m metricsWorkspaceService) Create(ctx context.Context, req types.CreateWorkspaceRequest) (workspace *types.Workspace, err error) {

	defer func(_begin_ time.Time) {
		if m.metrics == nil {
			return
		}
		var (
			success = true
			errCode int
		)
		if err != nil {
			success = false
			errCode = fiber.StatusInternalServerError
			ec, ok := err.(withErrorCode)
			if ok {
				errCode = ec.Code()
			}
		}
		clientID := srvctx.GetClientID(ctx)
		if success {
			m.metrics.RequestCount.WithLabelValues(metricServiceWorkspaceService, metricMethodWorkspaceServiceCreate, metricSuccessTrue, metricErrCodeSuccess, clientID).Add(1)
			m.metrics.RequestLatency.WithLabelValues(metricServiceWorkspaceService, metricMethodWorkspaceServiceCreate, metricSuccessTrue, metricErrCodeSuccess, clientID).Observe(float64(time.Since(_begin_).Seconds()))
		} else {
			errCodeStr := strconv.Itoa(errCode)
			m.metrics.RequestCount.WithLabelValues(metricServiceWorkspaceService, metricMethodWorkspaceServiceCreate, metricSuccessFalse, errCodeStr, clientID).Add(1)
			m.metrics.RequestLatency.WithLabelValues(metricServiceWorkspaceService, metricMethodWorkspaceServiceCreate, metricSuccessFalse, errCodeStr, clientID).Observe(float64(time.Since(_begin_).Seconds()))
		}
	}(time.Now())

	return m.next.Create(ctx, req)
}

func (m metricsWorkspaceService) Get(ctx context.Context, id string) (workspace *types.Workspace, err error) {

	defer func(_begin_ time.Time) {
		if m.metrics == nil {
			return
		}
		var (
			success = true
			errCode int
		)
		if err != nil {
			success = false
			errCode = fiber.StatusInternalServerError
			ec, ok := err.(withErrorCode)
			if ok {
				errCode = ec.Code()
			}
		}
		clientID := srvctx.GetClientID(ctx)
		if success {
			m.metrics.RequestCount.WithLabelValues(metricServiceWorkspaceService, metricMethodWorkspaceServiceGet, metricSuccessTrue, metricErrCodeSuccess, clientID).Add(1)
			m.metrics.RequestLatency.WithLabelValues(metricServiceWorkspaceService, metricMethodWorkspaceServiceGet, metricSuccessTrue, metricErrCodeSuccess, clientID).Observe(float64(time.Since(_begin_).Seconds()))
		} else {
			errCodeStr := strconv.Itoa(errCode)
			m.metrics.RequestCount.WithLabelValues(metricServiceWorkspaceService, metricMethodWorkspaceServiceGet, metricSuccessFalse, errCodeStr, clientID).Add(1)
			m.metrics.RequestLatency.WithLabelValues(metricServiceWorkspaceService, metricMethodWorkspaceServiceGet, metricSuccessFalse, errCodeStr, clientID).Observe(float64(time.Since(_begin_).Seconds()))
		}
	}(time.Now())

	return m.next.Get(ctx, id)
}

func (m metricsWorkspaceService) Update(ctx context.Context, id string, req types.UpdateWorkspaceRequest) (workspace *types.Workspace, err error) {

	defer func(_begin_ time.Time) {
		if m.metrics == nil {
			return
		}
		var (
			success = true
			errCode int
		)
		if err != nil {
			success = false
			errCode = fiber.StatusInternalServerError
			ec, ok := err.(withErrorCode)
			if ok {
				errCode = ec.Code()
			}
		}
		clientID := srvctx.GetClientID(ctx)
		if success {
			m.metrics.RequestCount.WithLabelValues(metricServiceWorkspaceService, metricMethodWorkspaceServiceUpdate, metricSuccessTrue, metricErrCodeSuccess, clientID).Add(1)
			m.metrics.RequestLatency.WithLabelValues(metricServiceWorkspaceService, metricMethodWorkspaceServiceUpdate, metricSuccessTrue, metricErrCodeSuccess, clientID).Observe(float64(time.Since(_begin_).Seconds()))
		} else {
			errCodeStr := strconv.Itoa(errCode)
			m.metrics.RequestCount.WithLabelValues(metricServiceWorkspaceService, metricMethodWorkspaceServiceUpdate, metricSuccessFalse, errCodeStr, clientID).Add(1)
			m.metrics.RequestLatency.WithLabelValues(metricServiceWorkspaceService, metricMethodWorkspaceServiceUpdate, metricSuccessFalse, errCodeStr, clientID).Observe(float64(time.Since(_begin_).Seconds()))
		}
	}(time.Now())

	return m.next.Update(ctx, id, req)
}

func (m metricsWorkspaceService) Delete(ctx context.Context, id string) (err error) {

	defer func(_begin_ time.Time) {
		if m.metrics == nil {
			return
		}
		var (
			success = true
			errCode int
		)
		if err != nil {
			success = false
			errCode = fiber.StatusInternalServerError
			ec, ok := err.(withErrorCode)
			if ok {
				errCode = ec.Code()
			}
		}
		clientID := srvctx.GetClientID(ctx)
		if success {
			m.metrics.RequestCount.WithLabelValues(metricServiceWorkspaceService, metricMethodWorkspaceServiceDelete, metricSuccessTrue, metricErrCodeSuccess, clientID).Add(1)
			m.metrics.RequestLatency.WithLabelValues(metricServiceWorkspaceService, metricMethodWorkspaceServiceDelete, metricSuccessTrue, metricErrCodeSuccess, clientID).Observe(float64(time.Since(_begin_).Seconds()))
		} else {
			errCodeStr := strconv.Itoa(errCode)
			m.metrics.RequestCount.WithLabelValues(metricServiceWorkspaceService, metricMethodWorkspaceServiceDelete, metricSuccessFalse, errCodeStr, clientID).Add(1)
			m.metrics.RequestLatency.WithLabelValues(metricServiceWorkspaceService, metricMethodWorkspaceServiceDelete, metricSuccessFalse, errCodeStr, clientID).Observe(float64(time.Since(_begin_).Seconds()))
		}
	}(time.Now())

	return m.next.Delete(ctx, id)
}

func (m metricsWorkspaceService) List(ctx context.Context, userID string, limit int, offset int) (workspaces []types.Workspace, total int, err error) {

	defer func(_begin_ time.Time) {
		if m.metrics == nil {
			return
		}
		var (
			success = true
			errCode int
		)
		if err != nil {
			success = false
			errCode = fiber.StatusInternalServerError
			ec, ok := err.(withErrorCode)
			if ok {
				errCode = ec.Code()
			}
		}
		clientID := srvctx.GetClientID(ctx)
		if success {
			m.metrics.RequestCount.WithLabelValues(metricServiceWorkspaceService, metricMethodWorkspaceServiceList, metricSuccessTrue, metricErrCodeSuccess, clientID).Add(1)
			m.metrics.RequestLatency.WithLabelValues(metricServiceWorkspaceService, metricMethodWorkspaceServiceList, metricSuccessTrue, metricErrCodeSuccess, clientID).Observe(float64(time.Since(_begin_).Seconds()))
		} else {
			errCodeStr := strconv.Itoa(errCode)
			m.metrics.RequestCount.WithLabelValues(metricServiceWorkspaceService, metricMethodWorkspaceServiceList, metricSuccessFalse, errCodeStr, clientID).Add(1)
			m.metrics.RequestLatency.WithLabelValues(metricServiceWorkspaceService, metricMethodWorkspaceServiceList, metricSuccessFalse, errCodeStr, clientID).Observe(float64(time.Since(_begin_).Seconds()))
		}
	}(time.Now())

	return m.next.List(ctx, userID, limit, offset)
}

func (m metricsWorkspaceService) SetScoringConfig(ctx context.Context, id string, config types.ScoringConfig) (workspace *types.Workspace, err error) {

	defer func(_begin_ time.Time) {
		if m.metrics == nil {
			return
		}
		var (
			success = true
			errCode int
		)
		if err != nil {
			success = false
			errCode = fiber.StatusInternalServerError
			ec, ok := err.(withErrorCode)
			if ok {
				errCode = ec.Code()
			}
		}
		clientID := srvctx.GetClientID(ctx)
		if success {
			m.metrics.RequestCount.WithLabelValues(metricServiceWorkspaceService, metricMethodWorkspaceServiceSetScoringConfig, metricSuccessTrue, metricErrCodeSuccess, clientID).Add(1)
			m.metrics.RequestLatency.WithLabelValues(metricServiceWorkspaceService, metricMethodWorkspaceServiceSetScoringConfig, metricSuccessTrue, metricErrCodeSuccess, clientID).Observe(float64(time.Since(_begin_).Seconds()))
		} else {
			errCodeStr := strconv.Itoa(errCode)
			m.metrics.RequestCount.WithLabelValues(metricServiceWorkspaceService, metricMethodWorkspaceServiceSetScoringConfig, metricSuccessFalse, errCodeStr, clientID).Add(1)
			m.metrics.RequestLatency.WithLabelValues(metricServiceWorkspaceService, metricMethodWorkspaceServiceSetScoringConfig, metricSuccessFalse, errCodeStr, clientID).Observe(float64(time.Since(_begin_).Seconds()))
		}
	}(time.Now())

	return m.next.SetScoringConfig(ctx, id, config)
}

func (m metricsWorkspaceService) InviteMember(ctx context.Context, id string, email string, role string) (member *types.Member, err error) {

	defer func(_begin_ time.Time) {
		if m.metrics == nil {
			return
		}
		var (
			success = true
			errCode int
		)
		if err != nil {
			success = false
			errCode = fiber.StatusInternalServerError
			ec, ok := err.(withErrorCode)
			if ok {
				errCode = ec.Code()
			}
		}
		clientID := srvctx.GetClientID(ctx)
		if success {
			m.metrics.RequestCount.WithLabelValues(metricServiceWorkspaceService, metricMethodWorkspaceServiceInviteMember, metricSuccessTrue, metricErrCodeSuccess, clientID).Add(1)
			m.metrics.RequestLatency.WithLabelValues(metricServiceWorkspaceService, metricMethodWorkspaceServiceInviteMember, metricSuccessTrue, metricErrCodeSuccess, clientID).Observe(float64(time.Since(_begin_).Seconds()))
		} else {
			errCodeStr := strconv.Itoa(errCode)
			m.metrics.RequestCount.WithLabelValues(metricServiceWorkspaceService, metricMethodWorkspaceServiceInviteMember, metricSuccessFalse, errCodeStr, clientID).Add(1)
			m.metrics.RequestLatency.WithLabelValues(metricServiceWorkspaceService, metricMethodWorkspaceServiceInviteMember, metricSuccessFalse, errCodeStr, clientID).Observe(float64(time.Since(_begin_).Seconds()))
		}
	}(time.Now())

	return m.next.InviteMember(ctx, id, email, role)
}

func (m metricsWorkspaceService) ListMembers(ctx context.Context, id string) (members []types.Member, err error) {

	defer func(_begin_ time.Time) {
		if m.metrics == nil {
			return
		}
		var (
			success = true
			errCode int
		)
		if err != nil {
			success = false
			errCode = fiber.StatusInternalServerError
			ec, ok := err.(withErrorCode)
			if ok {
				errCode = ec.Code()
			}
		}
		clientID := srvctx.GetClientID(ctx)
		if success {
			m.metrics.RequestCount.WithLabelValues(metricServiceWorkspaceService, metricMethodWorkspaceServiceListMembers, metricSuccessTrue, metricErrCodeSuccess, clientID).Add(1)
			m.metrics.RequestLatency.WithLabelValues(metricServiceWorkspaceService, metricMethodWorkspaceServiceListMembers, metricSuccessTrue, metricErrCodeSuccess, clientID).Observe(float64(time.Since(_begin_).Seconds()))
		} else {
			errCodeStr := strconv.Itoa(errCode)
			m.metrics.RequestCount.WithLabelValues(metricServiceWorkspaceService, metricMethodWorkspaceServiceListMembers, metricSuccessFalse, errCodeStr, clientID).Add(1)
			m.metrics.RequestLatency.WithLabelValues(metricServiceWorkspaceService, metricMethodWorkspaceServiceListMembers, metricSuccessFalse, errCodeStr, clientID).Observe(float64(time.Since(_begin_).Seconds()))
		}
	}(time.Now())

	return m.next.ListMembers(ctx, id)
}

func (m metricsWorkspaceService) RemoveMember(ctx context.Context, id string, memberID string) (err error) {

	defer func(_begin_ time.Time) {
		if m.metrics == nil {
			return
		}
		var (
			success = true
			errCode int
		)
		if err != nil {
			success = false
			errCode = fiber.StatusInternalServerError
			ec, ok := err.(withErrorCode)
			if ok {
				errCode = ec.Code()
			}
		}
		clientID := srvctx.GetClientID(ctx)
		if success {
			m.metrics.RequestCount.WithLabelValues(metricServiceWorkspaceService, metricMethodWorkspaceServiceRemoveMember, metricSuccessTrue, metricErrCodeSuccess, clientID).Add(1)
			m.metrics.RequestLatency.WithLabelValues(metricServiceWorkspaceService, metricMethodWorkspaceServiceRemoveMember, metricSuccessTrue, metricErrCodeSuccess, clientID).Observe(float64(time.Since(_begin_).Seconds()))
		} else {
			errCodeStr := strconv.Itoa(errCode)
			m.metrics.RequestCount.WithLabelValues(metricServiceWorkspaceService, metricMethodWorkspaceServiceRemoveMember, metricSuccessFalse, errCodeStr, clientID).Add(1)
			m.metrics.RequestLatency.WithLabelValues(metricServiceWorkspaceService, metricMethodWorkspaceServiceRemoveMember, metricSuccessFalse, errCodeStr, clientID).Observe(float64(time.Since(_begin_).Seconds()))
		}
	}(time.Now())

	return m.next.RemoveMember(ctx, id, memberID)
}
